### ISSUE TITLE
Phase out shr_map_checkRad

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#100]
Note the Bugzilla bug:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=2102

To summarize, `shr_map_mod` has a function called `shr_map_checkRad`, which attempts to figure out whether an array of angles is in degrees or radians by testing whether the maximum and minimum values in the array are separated by greater than 2.02 \* pi. Setting aside the fact that attempting to "guess" the units on a variable is terribly bad practice, the code of course breaks for small regional grids.

What we should be doing is checking the units on the input file. If there are files out there without appropriate units, we can perhaps fall back on the current method with a warning, and ideally change that warning into an appropriate error once those files fall out of use.

**Comment by mnlevy1981** [comment]
Looks like @ekluzek already moved this to [ESMCI #2506](https://github.com/ESMCI/cime/issues/2506) so closing the issue here.
