### ISSUE TITLE
Use the data file for drof as the domain file, rather than a separate domain file

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#102]
See Bugzilla:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=2113

**Comment by billsacks** [comment]
@ekluzek - should this be fixed for cesm2?

**Comment by billsacks** [comment]
@mvertens says this should be closed:

> This will be fixed in the new xml domain variable and that issue was related to the older perl scripts.
