### ISSUE TITLE
Data model code checks for fillalgo=='none', but this is not a valid value in the namelists.

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#103]
From Bugzilla:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=2114

It's not clear to me at first glance whether the solution is to add it as an allowed namelist option, or to remove the Fortran code that handles this case.

**Comment by billsacks** [comment]
@apcraig suggests supporting both 'none' and 'copy', meaning the same thing. So the solution is to add 'none' in the list of valid values in namelist definition.

**Comment by sholly** [comment]
Adding none option as a valid 'fillalgo'...

**Comment by billsacks** [comment]
Looks like this was fixed in #178
