### ISSUE TITLE
 Precipitation anomaly forcing and bias correction operates on a block of variables rather than testing each one seperatly

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#104]
From Bugzilla:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=2115

**Comment by billsacks** [comment]
Was this fixed with a4bdd41dfed64635d597327faff5411f6aaa7da0 ???

**Comment by billsacks** [comment]
@ekluzek - was this fixed? if not, should this be fixed for cesm2?

**Comment by ekluzek** [comment]
We should fix this for cesm2.

_Erik Kluzek, (CGD at NCAR)_

_National Center for Atmospheric Research_

*Boulder CO, *

_(off) (303)497-1326 (fax) (303)497-1348_

_(skype) ekluzek    (cell) (303)859-0183_

_Pronouns: he/his/him_

_------------------ Home page ------------------------_
- ```
       http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*
  ```
- ```
       https://staff.ucar.edu/users/erik
  ```
  
  https://staff.ucar.edu/users/erik*

_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_

**Comment by billsacks** [comment]
Closing this old issue; I'm not sure if it has been fixed. Feel free to reopen in ESMCI/cime if necessary.
