### ISSUE TITLE
env_*.xml files should be enumerated, not globbed

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#109]
Right now, if you create backup or reference copies of your xml files within your case directory, they can easily be picked up by various scripts (and may not be consistent), if they have names like:

```
tmp.env_run.xml
env_copies_of_stuff.xml
env_build.xml.backup
env_mach_pes.yellowstone.xml
```

This has bitten a few people, and there's also a [Bugzilla](http://bugs.cgd.ucar.edu/show_bug.cgi?id=2162) ticket on this. Typically what will happen depends on which command you are running, what name you gave the files, and specifically which files are first in alphabetical (or ASCII) order.

Code that reads the env_*.xml files should really be explicitly enumerating the expected files, rather than looking at every file with `.xml` somewhere in the name. There also should be rather few places in the code that do this.

We should check at least the generic environment-variable-manipulating commands (e.g. xmlchange/xmlquery), as well as the driver_cpl build-namelist and SetupTools.pm, to make sure that we're not globbing.

**Comment by jedwards4b** [comment]
fixed in cime5
