### ISSUE TITLE
Allow "additive" SourceMods for modifying data model streams

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#110]
See Bugzilla:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=1856

There's a lot of discussion there, but the gist seems to be that it would be nice to not only allow namelist_defaults_datm.xml to be replaced in SourceMods, but for a file to be added that doesn't require replacing the entire file that's in the source tree. (And similarly for other data models.)

**Comment by billsacks** [comment]
@jedwards4b says that the infrastructure to do this is in the python. However this isn't high priority for cesm2.

**Comment by billsacks** [comment]
Addressing this will mostly require changes in components' build-namelist

**Comment by ekluzek** [comment]
I think this is a worthwhile thing, but people seem more used to handling an entire file change rather than small changes. So I'm just going to close this.

**Comment by jedwards4b** [comment]
I read back through the bugzilla this morning - we no longer have a namelist_defaults.xml file so it's not clear to me what you want here.   Would you consider opening a new issue with a clear statement and example of the requested enhancement?

**Comment by ekluzek** [comment]
What it would amount to is having a partially filled namelist_definition_datm.xml file that would override particular fields you wanted to in the:

cime/src/components/data_comps/datm/cime_config/namelist_definition_datm.xml

file. I'm fine with leaving it closed though.
