### ISSUE TITLE
Incorrect comment lines in env_run.xml for DATM variables

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#112]
From [Bugzilla](http://bugs.cgd.ucar.edu/show_bug.cgi?id=2195):

> VERSION: clm4_5_1_r111 (development SVN for CLM)
> 
> The variables DATM_CLMNCEP_YR_ALIGN, DATM_CLMNCEP_YR_START and DATM_CLMNCEP_YR_END in env_run.xml have incorrect comments. It says they are only used for CLM_QIAN mode, however there are multiple other data modes for which they are used, amongst which CLMCRUNCEP and CLMCRUNCEP_V5. Comment should be updated.
> 
> Relevant files:
> /clm4_5_1_r111/cime/components/data_comps/datm/bld/namelist_files/namelist_defaults_datm.xml
> 
> env_run.xml

**Comment by ekluzek** [comment]
Description was shortened by Mariana in 2015-07-11
