### ISSUE TITLE
ERP test doesn't fail soon enough if user runs case.build instead of case.test_build

### ISSUE THREAD

**Issue by bandre-ucar** [CESM-Development/cime#113]
Unlike some of the other tests where one can run $CASE.build and get away with it, the ERP test requires that the user run $CASE.test_build. The error doesn't get caught until the job is running, and is reported in the cesm.stdout.xxxxx file. The length of time between the source of the error and the reporting of the error, along with the report location confused a very advanced user.

When the tests are refactored, the error should be reported during the build or submit process, not at test run time.

Note: the existing error message is accurate and helpful.

**Comment by jedwards4b** [comment]
Resolved by #231
