### ISSUE TITLE
cime1.1.12 breaks a CLM test

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#114]
cime1.1.12 breaks this CLM test: ERS_D_Mmpi-serial_Ld5.1x1_brazil.ICLM45ED.yellowstone_gnu.clm-edTest

Steps to reproduce:

(1) checkout https://svn-ccsm-models.cgd.ucar.edu/clm2/trunk_tags/clm4_5_1_r117

notice that cime is at cime1.1.11

(2) run the above test

notice that it runs to completion, although the restart test fails (this is a long-standing problem)

(3) switch to cime1.1.12 and rerun

notice that the run dies, with this error:

   0: NetCDF: Variable not found
   0: pio_support::pio_die:: myrank=          -1 : ERROR: pionfatt_mod.F90:         170 : NetCDF: Variable not found

I have tried cime1.1.11 + cherry-picking c148460 (Use Fortran 90 netCDF bindings in `shr_mct_mod`), since that seemed like the most likely culprit. However, the test ran to completion with that change (assuming I did it correctly, which I'm not sure of). So I guess it was some other change in cime1.1.12.

I'm assigning @jedwards4b to this; it seems like he and @sholly were the main contributors to this tag.

Also cc'ing @ekluzek @bandre-ucar and @mvertens

**Comment by jedwards4b** [comment]
The attached clm patch solves the problem.

On Wed, Aug 5, 2015 at 7:16 AM, Bill Sacks notifications@github.com wrote:

> Assigned #114 https://github.com/CESM-Development/cime/issues/114 to
> @jedwards4b https://github.com/jedwards4b.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/114#event-374177558.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by billsacks** [comment]
Thank you for tracking this down, Jim! And sorry to have wrongly assigned it to you. I am closing this and moving it to a CLM bug.
