### ISSUE TITLE
mpilib in config_machines.xml 

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#126]
We need to be able to specify options to the mpiexec command based on the mpilib.

For example on hobart when I use the nag/openmpi combination I would like to add the
--tag-output option and when I use the intel/mvapich2 combination I would like -prepend-rank

**Comment by apcraig** [comment]
There is also the case where different mpilib options require different launch commands completely.  On an SGI ICEX I've been using, there are two options,

intel mpi with mpirun
sgi mpt with mpiexec_mpt

**Comment by billsacks** [comment]
@jedwards4b says this is fixed - e.g., hobart now works.
