### ISSUE TITLE
-project argument to create_newcase not honored after batch refactor

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#129]
Since the batch system refactor, the '-project' argument to create_newcase is not honored.

This can be seen by creating a case on yellowstone when you do NOT have a $PROJECT or $ACCOUNT environment variable set, and do NOT have either ~/.cesm_proj or ~/.ccsm_proj files. In this case, the PROJECT env_case.xml variable is set correctly, but it is not propagated to the batch commands in the run script.

I believe the problem is that BatchMaker uses this:

./utils/perl5lib/Batch/BatchMaker.pm:   my $project = ProjectTools::find_project();

However, it should instead be using the already-set PROJECT variable in env_case.xml: find_project is meant to be called earlier, when setting up the case (you can see that it's called from create_newcase, create_clone, create_test) - and it is only called if the -project argument isn't given. After this point, others are meant to get the project from the PROJECT xml variable, not from ProjectTools.

**Comment by quantheory** [comment]
I'm closing this issue under the presumption that #140 has fixed it.
