### ISSUE TITLE
single-core yellowstone jobs not put on caldera

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#132]
With a recent version of cime (observed with cime2.0.3 in cesm1_4_alpha07a), I notice that single-core yellowstone jobs are being assigned to the regular queue rather than caldera. 

It looks like the appropriate logic is attempted in config_machines.xml:

```
      <queue walltimemax="24:00" jobmin="1" jobmax="8">caldera</queue>
```

but for whatever reason, this isn't being applied. Maybe a later setting overrides this one?

This is a small issue for testing, and a larger issue for production runs, for which you will be charged 16x what you should be charged.

**Comment by billsacks** [comment]
cc @jedwards4b

**Comment by mvertens** [comment]
This is fixed in cime3.0.3
