### ISSUE TITLE
create_newcase fails if cime is a symlink to another location

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#15]
I would like to be able to do the following:

From /path/to/cesm/checkout:

mv cime cime.svn
ln -s /path/to/cime/git/clone cime

cd cime/scripts
create_newcase ...

But I get something like:

cp: cannot stat `/path/to/cime/git/clone/../components/cism/bld/cism.buildlib': No such file or directory

The problem is in this code in create_newcase, which is also in create_test and elsewhere:

```
(my $ProgName = $0) =~ s!(.*)/!!;      # name of this script
my $ProgDir = $1;                      # name of directory containing this script -- may be a
                                       # relative or absolute path, or null if the script is in
                                       # the user's PATH
my $cwd = getcwd();                    # current working directory
my $cfgdir;                            # absolute pathname of directory that contains this script
if ($ProgDir) { 
    $cfgdir = abs_path($ProgDir);
} else {
    $cfgdir = $cwd;
}

my $cimeroot = abs_path("$cfgdir/../");
```

And later:

```
    $compdir = "$cimeroot/../components/$comp/bld";
```

Jay has convinced me that it may often be a bad idea to link to the same cime clone from a bunch of CESM checkouts. But this is still something that feels useful sometimes: It feels like the git workflow encourages you to have a single git clone of a repository on a given machine, and then switch branches in that clone as needed. So, particularly for some quick testing, it seems nice to be able to point to an existing clone rather than setting up a fresh clone, setting up your local tracking branches there, etc.

I can see a few possible solutions to the sym link problem:

(1) The solution recommended here http://www.perlmonks.org/?node_id=886883 (see first comment) is to use the shell's $PWD variable, if it exists, in place of the getcwd call above. That sounds like the only way to get your current directory without following sym links.

(2) Include an optional argument to create_newcase, create_test and create_clone that allows you to specify the absolute path to the 'components' directory.

This is nice in that it should allow you to run create_newcase from a cime directory that is in a totally different place from your components, and point to a components directory wherever you want.

For this to work, I think you would need to get rid of the CESMROOT (CCSMROOT?) xml variable. Instead, you would have a CIME_ROOT variable and a COMPONENTS_ROOT variable, and those two variables would be used as needed. i.e., we would remove the assumption from nearly all places that you have a directory structure that looks like this:

cesm
   cime
   components

The only place where that assumption would remain would be in setting the default value of COMPONENTS_ROOT if it is not specified explicitly.

(3) I would also be happy with a solution that would allow a slightly different usage:

mv cime cime.svn
ln -s /path/to/cime/git/clone cime

cime/scripts/create_newcase ...

i.e., rather than cd'ing to cime/scripts and running the scripts from there, instead run them from the top-level cesm checkout.

This currently also fails, with the same error as above.

However, I think this would be easier to solve, by changing:

```
    $cfgdir = abs_path($ProgDir);
```

to:

```
    $cfgdir = canonpath(rel2abs($ProgDir));
```

(I'm not sure the canonpath is needed.)

**Comment by quantheory** [comment]
Personally, I like option 2. But I'm curious whether just using a hard link would work for your purposes.

**Comment by billsacks** [comment]
@mvertens @jedwards4b @sholly @bandre-ucar @mnlevy1981  -- I'd be interested in your feelings on:

(a) Whether this is a problem that should be solved, or whether I'm just doing something screwy.

(b) If this problem should be solved, then which of my proposed solutions do you think is best. Actually, some of the solutions can be combined, so it's not a one-or-the-other question, but rather: which proposal(s) do you like / dislike. Or do you have other suggestions?

**Comment by billsacks** [comment]
@quantheory : You can't hard link to a directory, right?

**Comment by jedwards4b** [comment]
I think that any or all of these solutions would be fine.  You aren't
removing any current functionality just extending it in a way that makes
sense for developers.   It would be nice if we could figure out a way to do
the checkout so that you don't have to get cime using svn every time.

On Fri, May 22, 2015 at 4:24 PM, Bill Sacks notifications@github.com
wrote:

> @mvertens https://github.com/mvertens @jedwards4b
> https://github.com/jedwards4b @sholly https://github.com/sholly
> @bandre-ucar https://github.com/bandre-ucar @mnlevy1981
> https://github.com/mnlevy1981 -- I'd be interested in your feelings on:
> 
> (a) Whether this is a problem that should be solved, or whether I'm just
> doing something screwy.
> 
> (b) If this problem should be solved, then which of my proposed solutions
> do you think is best. Actually, some of the solutions can be combined, so
> it's not a one-or-the-other question, but rather: which proposal(s) do you
> like / dislike. Or do you have other suggestions?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/15#issuecomment-104788644
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by quantheory** [comment]
@billsacks Oh, right, on most systems you can't.

**Comment by billsacks** [comment]
Here are references to '../components' from cime that would need to be changed with idea (2) above (and probably the other ideas as well). These would need to either allow the user to point to the components directory via an optional argument to the top-level script, or use COMPONENTS_ROOT in place of CIME_ROOT:

```
./machines/Makefile:    $(CMAKE_ENV_VARS) cmake $(CMAKE_OPTS) $(CIMEROOT)/../components/cism/glimmer-cism
./machines/Makefile:    $(MAKE) -f $(CIMEROOT)/../components/pop/source/cvmix/Makefile SRC_DIR=$(CIMEROOT)/../components/pop/source/cvmix FC=$(SFC) FCFLAGS="$(FFLAGS) $(FREEFLAGS)" LIB_DIR=$(LIBROOT)
./scripts/create_newcase:   $compdir = "$cimeroot/../components/$comp/bld";
./scripts/create_newcase:   $sysmod = "cp $cimeroot/../components/cice/bld/generate_cice_decomp.pl $buildconf/."; 
./scripts/create_newcase:   $sysmod = "cp $cimeroot/../components/pop/bld/generate_pop_decomp.pl $buildconf/."; 
./scripts/create_newcase:       "This includes any files that are in the glimmer-cism subdirectory of $cimeroot/../components/cism.\n\n",
./scripts/create_test:  if (-d "$cimeroot/../components") {
./scripts/create_test:      my $d = IO::Dir->new("$cimeroot/../components");
./scripts/create_test:      my $dir = "$cimeroot/../components/$comp/cimetest";
./scripts/manage_testlists:            my $dir = "$cimeroot/../components/$component/cimetest";
./scripts/manage_testlists: $list = "$cimeroot/../components/$component/cimetest/testlist_$component.xml"; 
./scripts/Tools/cesm_setup:         if (-f "$CIMEROOT/../components/${comp}/bld/user_nl_${comp}") {
./scripts/Tools/cesm_setup:             my $sysmod = "cp $CIMEROOT/../components/${comp}/bld/user_nl_${comp} $CASEROOT/user_nl_${comp}${inst_string}";
./scripts/Tools/cesm_setup:         if (-f "$CIMEROOT/../components/${comp}/bld/user_nl_${comp}") {
./scripts/Tools/cesm_setup:         my $sysmod = "cp $CIMEROOT/../components/${comp}/bld/user_nl_${comp} $CASEROOT/user_nl_${comp}";
```

That is from the tag move_glint_to_cpl2_n02, using a recursive grep for '../components'

**Comment by billsacks** [comment]
Also, from a grep for -i 'cimeroot/../'

there are these additional lines in the top-level scripts:

```
./scripts/create_clone:$cfg_ref->set('SRCROOT'     , "$cimeroot/../");
./scripts/create_clone:$cfg_ref->set('CCSMROOT'    , "$cimeroot/../");
./scripts/create_newcase:$cfg_ref->set('SRCROOT' , "$cimeroot/../");
./scripts/create_newcase:$cfg_ref->set('CCSMROOT', "$cimeroot/../");
```

**Comment by billsacks** [comment]
For idea (2), we'll need to replace various uses of CCSMROOT and SRCROOT with COMPONENT_ROOT. From a grep for these, this looks pretty straightforward.

**Comment by billsacks** [comment]
A little harder may be replacing uses of abs_path. There aren't a ton of these, but they will need to be replaced -- things like this:

./clm/bld/CLMBuildNamelist.pm:  my $cesmroot = abs_path( "$cfgdir/../../../");

In that particular case (and maybe others), it looks like we could instead use the CIME_ROOT xml variable that I am proposing.

**Comment by billsacks** [comment]
My current thinking is that, for now, I will try to implement (2), but won't try for (1) or (3). Part of my rationale here is that "fixing" this via (1) and (3) feel like it could break other workflows. For example, if someone has a checkout of CESM without any sym links (i.e., a standard checkout), but a sym link like this:

current_cesm_cime -> /path/to/my/cesm/checkout/cime

then do:

cd current_cesm_cime/scripts
create_newcase ...

Then it feels like some of my ideas will break that case.

**Comment by billsacks** [comment]
Ben, Sean and Jay have all convinced me that what I'm trying to do is generally a bad idea. Instead, I should create a separate cime clone in each cesm checkout. 

So I'm not going to try to address this (non)issue for now.
