### ISSUE TITLE
There is no good MP_EAGER_LIMIT setting on yellowstone

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#151]
I noticed in this commit that `MP_EAGER_LIMIT` is being set to 0 again to deal with a memory leak:

https://github.com/CESM-Development/cime/commit/bbf48ef57f6b4139502d48ed46347623de114d4e

However, the reason that we stopped setting it is that Francis and I found that it made a big difference for the performance of WACCM runs at medium-to-high core counts. Setting `MP_EAGER_LIMIT` to 0 slows things down by a factor of >20% at moderately high core counts (~250 nodes), and tends to shut down scaling past that point.

Do we need to push harder on CISL or IBM to get this memory leak fixed? I think it's worth prioritizing this if we're looking at such a large cost/time difference for CAM-FV runs, including configurations important for CMIP6.

cc @sholly

**Comment by jedwards4b** [comment]
I think that we need to leave this in as the default and change it on a
case by case basis when it's clear that the particular case is not leaking
memory.   IBM dropped support of the poe/mpich library we are using and it
is highly unlikely that we will get any satisfactory resolution from them.

On Thu, Sep 3, 2015 at 11:09 AM, Sean Patrick Santos <
notifications@github.com> wrote:

> Assigned #151 https://github.com/CESM-Development/cime/issues/151 to
> @jedwards4b https://github.com/jedwards4b.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/151#event-400313568.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by bandre-ucar** [comment]
Is there a reason we aren't using a supported mpich library...?

**Comment by jedwards4b** [comment]
Because there isn't one.  That is a question for CISL and IBM and in my
opinion not worth pursuing.

On Thu, Sep 3, 2015 at 11:23 AM, Ben Andre notifications@github.com wrote:

> Is there a reason we aren't using a supported mpich library...?
> 
> On Thu, Sep 3, 2015 at 11:22 AM, jedwards4b notifications@github.com
> wrote:
> 
> > I think that we need to leave this in as the default and change it on a
> > case by case basis when it's clear that the particular case is not
> > leaking
> > memory. IBM dropped support of the poe/mpich library we are using and it
> > is highly unlikely that we will get any satisfactory resolution from
> > them.
> > 
> > On Thu, Sep 3, 2015 at 11:09 AM, Sean Patrick Santos <
> > notifications@github.com> wrote:
> > 
> > > Assigned #151 https://github.com/CESM-Development/cime/issues/151 to
> > > @jedwards4b https://github.com/jedwards4b.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/CESM-Development/cime/issues/151#event-400313568.
> > 
> > ## 
> > 
> > Jim Edwards
> > 
> > CESM Software Engineer
> > National Center for Atmospheric Research
> > Boulder, CO
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/CESM-Development/cime/issues/151#issuecomment-137518685
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/151#issuecomment-137519240
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by quantheory** [comment]
Um. I hope that the agreement for the next procurement specifies that critical software actually has to be supported for the full lifetime of the machine. Yellowstone still has years left, and apparently we're already relying on unsupported libraries. Not fun.

_Anyway_, back to the things that we can actually do something about, here, would it be possible to adjust MP_EAGER_LIMIT based on the grid or core count? Will it be possible to do that after Jay's module changes land? I'd prefer to switch this somewhat automatically, rather than requiring users running big jobs to know about this setting and to remember to change it by hand in each of their cases.

I guess I'm unsure about how to make that decision, because I haven't actually noticed any serious memory leak, so I don't know which configurations actually _do_ have this problem. I vaguely remember someone mentioning some case where the memory leak was pretty bad, but I don't remember who it was or what configuration was being run.

**Comment by jedwards4b** [comment]
In env_mach_specific.xml MP_EAGER_LIMIT is being set to 0 again on yellowstone.  I think that the
default should be unset and users should try setting it to 0 if they think they are seeing the memory leak.

**Comment by mvertens** [comment]
I agree with Jim's recommendation.

**Comment by quantheory** [comment]
I also agree. A very slim performance advantage for CAM-SE, and the memory leak, are the only reasons to set this variable. I started this issue because I believe that the impact on CAM-FV drastically outweighs both concerns for coupled and F compsets.

**Comment by billsacks** [comment]
The MP_EAGER_LIMIT problem came up again in an I compset (which is where we have seen big memory leaks in the past). @ekluzek tracked the run's crash down to this MP_EAGER_LIMIT problem, but each time this comes up, it feels like it is wasting considerable time for the scientists involved.

I understand the rationale for no longer setting this to 0 by default. However, in a recent CSEG meeting, we discussed the possibility of making the default for this variable key off of some aspect of the case. e.g., keying off of compset would probably be the easiest... it wouldn't be the most general or robust, but would likely solve the vast majority of problems. e.g., leave this variable unset in general, but set it to 0 for all compsets that use datm, or maybe just all compsets that use clm + datm.

I don't know whether this is possible right now, but would like to float this idea. @jedwards4b and @mvertens : what do you think about this?

**Comment by ekluzek** [comment]
Here's some documentation on MP_EAGER_LIMIT. From the man page on "poe".

MP_EAGER_LIMIT 
         Changes the threshold value for message size, above which
         rendezvous protocol is used. 

```
     For IBM PE MPI and MPICH2 (when the MP_USE_TOKEN_FLOW
     environment variable is set to yes), if the MP_EAGER_LIMIT
     environment variable is not set during initialization, IBM PE
     MPI or MPICH2 automatically chooses a default eager limit
     value, based on the number of tasks. For specific information
     about the default eager limit values, see IBM Parallel
     Environment Runtime Edition: MPI Programming Guide.

     Consider running a new application once with eager limit set to
     0 (zero) because this is useful for confirming that an
     application is safe, but normally higher eager limit gives
     better performance. Note that a safe application, as defined by
     the MPI standard, is one that does not depend on some minimum
     of MPI buffer space to avoid deadlock.         

     The maximum value for MP_EAGER_LIMIT is 256K (262144 bytes).
     Any value that is less than 64 bytes but greater than zero
     bytes is automatically increased to 64 bytes. A non-power of 2
     value will be rounded up to the nearest power of 2. A value may
     be adjusted if the early arrival buffer (MP_BUFFER_MEM) size is
     set too small.

     For information about buffering eager send messages and eager
     limit, see IBM Parallel Environment Runtime Edition: MPI
     Programming Guide.
```

And from the table from "IBM PE Runtime Edition" for jobs of 513 to 1024 tasks  the MP_EAGER_LIMIT by default is 8192 Bytes. And under system limits we have this...

MPI uses the MP_BUFFER_MEM and the MP_EAGER_LIMIT values that are selected for a job to determine how many complete point-to-point messages, each with a size that is equal to or less than the eager_limit, can be sent eagerly from every task of the job to a single task, without causing the single target to run out of buffer space. This is done by allocating to each sending task a number of message credits for each target. The sending task will consume one message credit for each eager send to a particular target. It will get that credit back after the message has been matched at that target.
The sending task can continue to send eager messages to a particular target as long as it still has message credits for that target. The following equation is used to calculate the number of credits to be allocated:
  MP_BUFFER_MEM / (MP_PROCS \* MAX(MP_EAGER_LIMIT, 64))
MPI uses this equation to ensure that there are at least two credits for each target. If needed, MPI reduces the initially selected value of MP_EAGER_LIMIT, or increases the initially selected value of MP_BUFFER_MEM, in order to achieve this minimum threshold of two credits for each target.

And the default for MP_BUFFER_MEM is 64MB

**Comment by ekluzek** [comment]
Putting this all together I think both MP_BUFFER_MEM and MP_EAGER_LIMIT should be changed. I'm thinking I'll try MP_BUFFER_MEM=8MB and MP_EAGER_LIMIT of 512.

**Comment by jedwards4b** [comment]
The issue in question is a bug not a feature and therefore may not perform
as documented.

On Tue, Dec 15, 2015 at 10:31 PM, Erik Kluzek notifications@github.com
wrote:

> Putting this all together I think both MP_BUFFER_MEM and MP_EAGER_LIMIT
> should be changed. I'm thinking I'll try MP_BUFFER_MEM=8MB and
> MP_EAGER_LIMIT of 512.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/151#issuecomment-164998767
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by billsacks** [comment]
This has been resolved via the mechanism to put in barriers
