### ISSUE TITLE
compare_namelist.pl seems to mishandle new variables

### ISSUE THREAD

**Issue by mnlevy1981** [CESM-Development/cime#156]
Keith L added two namelist variables to &ecosys_nml in pop_in, and we expected the namelist comparison tool to output

```
PASS namelist compare: /glade/p/work/mlevy/nl_comp/pop_in and /glade/p/work/mlevy/nl_comp/baseline.pop_in are the same
   The following variables were added to /glade/u/home/mlevy/projects/nl_comp/pop_in
     caco3_bury_thres_depth = 3300.0e2
     caco3_bury_thres_opt = 'fixed_depth'
```

Instead, we see

```
$ ./compare_namelists.pl /glade/p/work/mlevy/nl_comp/pop_in /glade/p/work/mlevy/nl_comp/baseline.pop_in 150909-133956

FAIL namelist compare:  pop_in differs
   NEW:        &ecosys_driver_nml
   BASELINE: &ecosys_restore_nml
```

Interestingly, switching the order of the files is fine

```
$ ./compare_namelists.pl /glade/p/work/mlevy/nl_comp/baseline.pop_in /glade/p/work/mlevy/nl_comp/pop_in 20150901a

PASS namelist compare: /glade/p/work/mlevy/nl_comp/baseline.pop_in and /glade/p/work/mlevy/nl_comp/pop_in are the same
   The following variables were removed from /glade/p/work/mlevy/nl_comp/baseline.pop_in
     caco3_bury_thres_depth = 3300.0e2
     comp_surf_avg_freq = 1
```

**Comment by mnlevy1981** [comment]
I made a couple of tweaks to the script and now it behaves as expected for the example namelist above... but I have no idea if it breaks functionality in any other cases. Is there a test suite for the compare_namelist test? My update is on yellowstone in `/glade/p/work/mlevy/codes/CESM/cesm1_4_beta06+latest_pop/cime/scripts/Tools`

```
$ ./compare_namelists.pl /glade/p/work/mlevy/nl_comp/pop_in /glade/p/work/mlevy/nl_comp/baseline.pop_in 150909-133956

PASS namelist compare: /glade/p/work/mlevy/nl_comp/pop_in and /glade/p/work/mlevy/nl_comp/baseline.pop_in are the same
   The following variables were added to /glade/p/work/mlevy/nl_comp/pop_in
     caco3_bury_thres_depth = 3300.0e2
     caco3_bury_thres_opt = 'fixed_depth'
```

**Comment by mnlevy1981** [comment]
Realized I deleted the `/glade/p/work/mlevy/codes/CESM/cesm1_4_beta06+latest_pop` directory; working on recreating this fix

**Comment by mnlevy1981** [comment]
I created a new branch with the fix: https://github.com/mnlevy1981/cime/tree/mlevy/compare_namelist

It seems to work for the case of adding variables and the case of deleting variables, but that's the extent of the testing I've done. Also including the diff below, since having that in an earlier comment would have saved me some time...

```
diff --git a/scripts/Tools/compare_namelists.pl b/scripts/Tools/compare_namelists.pl
index 56ed7c1..b1fbc16 100755
--- a/scripts/Tools/compare_namelists.pl
+++ b/scripts/Tools/compare_namelists.pl
@@ -23,13 +23,17 @@ my $cnt1=$#nlfile;
 my $cnt2=$#basenml;
 my $shiftbl=1;
 foreach $line (@nlfile){
+    chomp $line;
     my $bline = shift(@basenml) if($shiftbl);
+    chomp $bline;
     $line =~ s/\s+/ /g;
     $bline =~ s/\s+/ /g;
     $shiftbl=1;
     next if($line eq $bline);
     $bline=shift(@basenml) if(($bline =~ /^\s*[#!\[\/]/) or ($bline =~ /^\s*$/));
+    chomp $bline;

+    next if($line eq $bline);
     next if(defined $baseid && $line =~ /$baseid/); 
     next if($line =~ /^\s*[#!\[\/]/);
     next if($line =~ /^\s*$/);
@@ -44,8 +48,6 @@ foreach $line (@nlfile){
     if($bline =~ /(.*)=(.*)/){
         $name2 = $1;
     }
-    chomp $line;
-    chomp $bline;
     if($name1 eq $name2){
        push(@diffs1,$line);
        push(@diffs2,$bline);
@@ -53,6 +55,7 @@ foreach $line (@nlfile){
        push(@added,$line);
        $shiftbl=0;
        $cnt1--;
+       unshift(@basenml, $bline);
     }elsif($cnt2>$cnt1){
        push(@removed,$bline);
        shift(@basenml);
```

**Comment by klindsay28** [comment]
I am encountering situations where compare_namelists.pl reports FAIL when a namelist variable has been added. The script sometimes reports PASS and sometimes reports FAIL. This inconsistency makes it challenging to interpret output from the script. The csh commands below demonstrate this behavior.

I'm using CIME 4.4.8. It looks like the script hasn't changed in more recent versions of CIME.

PASS example (with expected output)
setenv TESTID ERS.T62_g37.GECO.yellowstone_intel.pop-cice_ciso
cd /glade/p/work/klindsay/nlcomp_tests/20160504/$TESTID
$CIMEROOT/scripts/Tools/compare_namelists.pl  new/pop_in old/pop_in $TESTID

returns
PASS namelist compare: new/pop_in and old/pop_in are the same
   The following variables were added to new/pop_in
     dust_flux_source = 'monthly-calendar' 

FAIL example (with unexpected output)
setenv TESTID SMS_Ld20.T62_g16.CECO.yellowstone_intel.pop-ecosys_shr_stream
cd /glade/p/work/klindsay/nlcomp_tests/20160504/$TESTID
$CIMEROOT/scripts/Tools/compare_namelists.pl  new/pop_in old/pop_in $TESTID

returns
FAIL namelist compare:  pop_in differs
   NEW:        &ecosys_restore_nml 
   BASELINE:

**Comment by mnlevy1981** [comment]
I ran my updated `compare_namelists.pl` tool through Keith's script and both tests pass:

Keith's PASS:

```
$ ${MYCIME}/compare_namelists.pl new/pop_in old/pop_in \
   ERS.T62_g37.GECO.yellowstone_intel.pop-cice_ciso

PASS namelist compare: new/pop_in and old/pop_in are the same
   The following variables were added to new/pop_in
     dust_flux_source = 'monthly-calendar'
```

Keith's FAIL:

```
$ ${MYCIME}/compare_namelists.pl new/pop_in old/pop_in \
   SMS_Ld20.T62_g16.CECO.yellowstone_intel.pop-ecosys_shr_stream

PASS namelist compare: new/pop_in and old/pop_in are the same
   The following variables were added to new/pop_in
     dust_flux_source = 'monthly-calendar'
```
