### ISSUE TITLE
missing metadata_set calls in seq_flds_mods.F90

### ISSUE THREAD

**Issue by apcraig** [CESM-Development/cime#165]
There does not seem to be a "metadata_set" call for the ram1 variable in seq_flds_mod.F90.  This should be updated.  We should make sure other coupling variables are not missing the metadata call as well.  This is where units and descriptions are documented for each coupling variable.

**Comment by jedwards4b** [comment]
What are the:
longname
stdname
units 
attname 

for the following cpl variables?
  ! Aerodynamical resistance (land/atm only)
     call seq_flds_add(l2x_states,"Sl_ram1")
     call seq_flds_add(x2a_states,"Sl_ram1")

 carma_fields
megan_fields
fire emissions fields.

**Comment by billsacks** [comment]
fixed by #280
