### ISSUE TITLE
Split of csm_share

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#18]
For a long while, I've felt that `csm_share` is throwing a lot of things together that don't really go together, just because they happen to be used by multiple components.

This perhaps makes it a little harder to reuse share code, simply because it's harder to find what you're looking for. It also causes problems for programs that would like to use utility code, but have to be built outside CESM (such as HOMME, or certain test programs). For example, you might want to use some string formatting function, but you don't want to build all of `csm_share` to do it (in particular because you then have to include GPTL, PIO, MCT, and the ESMF time manager). This leads to the awkward situation where "reusing" share code often means making extra copies of files (e.g. tweaked copies of random `csm_share` modules in the HOMME repo), or compiling specific bits and pieces rather than the whole library.

For reference, I think that there are about five different types of module here:
1. Fortran supplements. Some of these are wrappers for Fortran features, which could be simplified or removed as newer standards become reliable. Some work around non-portable behavior in the standard, or provide access to common compiler extensions. Others are designed to make up for the fact that Fortran doesn't really have a standard library, and those modules define functions that are typically standard in systems languages and higher level languages, or are in the POSIX standard.
   - The dynamic vector template - Imitates C++'s `std::vector`
   - `shr_assert.h`/`shr_assert_mod` - C-style asserts and more; we should probably rename the header to `shr_assert.inc`
   - `shr_file_mod` - Generic file utilities (except for the NCAR-specific archiving information)
   - `shr_infnan_mod` - Fortran 2003 IEEE module utility wrapper.
   - `shr_kind_mod` - Partly utility definitions, partly redundant with F2003/F2008 `iso_fortran_env`.
   - `shr_log_mod` - Logging utility.
   - `shr_nl_mod` - Simple seek routine, mostly for NAG compatibility
   - `shr_RandNum_mod` (future pull request from Chris Kerr) - Random number generators
   - `shr_spfn_mod` - Special function calculations; most of these functions are now in the F2008 standard
   - `shr_strconvert_mod` - String conversion utility; intended to avoid error-prone `write` statements and standardize output across compilers
   - `shr_string_mod` - String manipulation and formatting; contains code for handling colon-separated lists that could be in a separate module
   - `shr_sys_mod` - Standardize basic functionality across OSes and compilers; mostly this wraps non-standard implementations or extensions of POSIX functions
   - `shr_vmath_mod` - Wrapper for system-specific vector versions of mathematical functions (e.g. from Intel)
2. Modules somewhat specific to earth system models or science codes in general, but not necessarily parallel codes using our coupling infrastructure.
   - `shr_const_mod` - Physical and mathematical constants
   - `shr_map_mod` - 2D remapping using lat/lon coordinates
   - `shr_orb_mod` - Calculations based on orbital parameters, e.g. zenith angle
   - `shr_wv_sat_mod` (pending pull request #17) - Water saturation vapor pressure calculations
3. Modules which are wrappers or utilities for the various libraries we use, e.g. MPI, PIO, MCT, ESMF.
   - `mct_mod` - MCT wrapper
   - `shr_cal_mod` - Calendar conversions using the ESMF time manager
   - `shr_mct_mod` - netCDF I/O of certain MCT objects
   - `shr_mem_mod` - Get memory usage using GPTL
   - `shr_mpi_mod` - Wrappers of MPI functions; mostly for checking error codes
   - `shr_pcdf_mod` - PIO routine combining many read/write functions into a single function
   - `shr_reprosum_mod`/`shr_reprosumx86.c` - Reproducible sums for MPI-only and MPI/OpenMP hybrid parallel codes
   - `shr_tInterp_mod` - Time interpolation using ESMF and `shr_orb_mod`
4. Modules which are specific to CIME or to CESM, and which potentially should be somewhere else (e.g. in the shared code in `driver_cpl`, or even a specific science component).
   - `shr_dmodel_mod` - Mostly grid-related code for data models
   - `shr_flux_mod` - Ocean-atmosphere flux calculations
   - `shr_pio_mod` - PIO wrapper, mostly for driver-specific initialization
   - `shr_strdata_mod` - Utilities to handle input files for data models
   - `shr_stream_mod` - Representation of streams, especially for data models
5. Code that should probably be heavily refactored or removed completely.
   - `shr_msg_mod` - The comments state that `shr_file_mod` should have replaced this
   - `shr_ncread_mod` - Utility code for netCDF reads; we should probably use PIO instead
   - `shr_scam_mod` - Single point/column mode utilities; buggy and doesn't seem targeted to our current needs
   - `shr_timer_mod` - Minimal timer functionality; we should be using `perf_mod` instead, which can be done even in portable code using callbacks

What I would like to propose is to split up csm_share a bit to reflect a) the distinction between code that depends on external libraries and code that doesn't, and b) the distinction between code that's shared because it's very generic and low-level, versus code shared for some other reason.

What that would mean is that categories 1 and 2 above would be put together in a separate library with no dependencies. Category 3 would become a library of utilities with the usual CIME dependencies. Category 4 would be moved to the driver (some of it in `driver_cpl/shr`, some in `driver_cpl/driver`). And category 5 would get split among those three places as appropriate, but hopefully some redundant/dead code could be removed in the process. A minor bonus is that we could get rid of the outdated name `csm_share`.

Thoughts? Is this a reasonable way to split things up? Any ideas for library names?

**Comment by jedwards4b** [comment]
Hi Sean,

I think that this would be a great thing to do.   But I think that we need
to make the line of division as clear as possible.
Files in the first group should not have any dependancies other than other
files in that group and the timing utilities.

The other four groups (all labeled 1)  should be combined into one or at
most 2.   Maybe one is science utilities and the other is cime utilities.
I assume those science utilities are something you envision building and
using outside of cime.

On Wed, May 27, 2015 at 4:34 PM, Sean Patrick Santos <
notifications@github.com> wrote:

> For a long while, I've felt that csm_share is throwing a lot of things
> together that don't really go together, just because they happen to be used
> by multiple components.
> 
> This perhaps makes it a little harder to reuse share code, simply because
> it's harder to find what you're looking for. It also causes problems for
> programs that would like to use utility code, but have to be built outside
> CESM (such as HOMME, or certain test programs). For example, you might want
> to use some string formatting function, but you don't want to build all of
> csm_share to do it (in particular because you then have to include GPTL,
> PIO, MCT, and the ESMF time manager). This leads to the awkward situation
> where "reusing" share code often means making extra copies of files (e.g.
> tweaked copies of random csm_share modules in the HOMME repo), or
> compiling specific bits and pieces rather than the whole library.
> 
> For reference, I think that there are about five different types of module
> here:
> 
>    1.
> 
>    Fortran supplements. Some of these are wrappers for Fortran features,
>    which could be simplified or removed as newer standards become reliable.
>    Some work around non-portable behavior in the standard, or provide access
>    to common compiler extensions. Others are designed to make up for the fact
>    that Fortran doesn't really have a standard library, and those modules
>    define functions that are typically standard in systems languages and
>    higher level languages, or are in the POSIX standard.
> - The dynamic vector template - Imitates C++'s std::vector
> - shr_assert.h/shr_assert_mod - C-style asserts and more; we should
>   probably rename the header to shr_assert.inc
> - shr_file_mod - Generic file utilities (except for the NCAR-specific
>   archiving information)
> - shr_infnan_mod - Fortran 2003 IEEE module utility wrapper.
> - shr_kind_mod - Partly utility definitions, partly redundant with
>   F2003/F2008 iso_fortran_env.
> - shr_log_mod - Logging utility.
> - shr_nl_mod - Simple seek routine, mostly for NAG compatibility
> - shr_RandNum_mod (future pull request from Chris Kerr) - Random
>   number generators
> - shr_spfn_mod - Special function calculations; most of these
>   functions are now in the F2008 standard
> - shr_strconvert_mod - String conversion utility; intended to avoid
>   error-prone write statements and standardize output across compilers
> - shr_string_mod - String manipulation and formatting; contains code
>   
>   ## for handling colon-separated lists that could be in a separate module
>   
>   shr_sys_mod - Standardize basic functionality across OSes and
>   compilers; mostly this wraps non-standard implementations or extensions of
>   POSIX functions
>   - shr_vmath_mod - Wrapper for system-specific vector versions of
>     mathematical functions (e.g. from Intel)
>   
>   1.
>   
>   Modules somewhat specific to earth system models or science codes in
>   general, but not necessarily parallel codes using our coupling
>   infrastructure.
> - shr_const_mod - Physical and mathematical constants
> - shr_map_mod - 2D remapping using lat/lon coordinates
> - shr_orb_mod - Calculations based on orbital parameters, e.g. zenith
>   
>   ## angle
>   
>   shr_wv_sat_mod (pending pull request #17
>   https://github.com/CESM-Development/cime/pull/17) - Water saturation
>   vapor pressure calculations
>   
>   1.
>   
>   Modules which are wrappers or utilities for the various libraries we
>   use, e.g. MPI, PIO, MCT, ESMF.
> - mct_mod - MCT wrapper
> - shr_cal_mod - Calendar conversions using the ESMF time manager
> - shr_mct_mod - netCDF I/O of certain MCT objects
> - shr_mem_mod - Get memory usage using GPTL
> - shr_mpi_mod - Wrappers of MPI functions; mostly for checking error
>   codes
> - shr_pcdf_mod - PIO routine combining many read/write functions into
>   a single function
> - shr_reprosum_mod/shr_reprosumx86.c - Reproducible sums for MPI-only
>   
>   ## and MPI/OpenMP hybrid parallel codes
>   
>   shr_tInterp_mod - Time interpolation using ESMF and shr_orb_mod
>   
>   1.
>   
>   Modules which are specific to CIME or to CESM, and which potentially
>   should be somewhere else (e.g. in the shared code in driver_cpl, or
>   even a specific science component).
> - shr_dmodel_mod - Mostly grid-related code for data models
> - shr_flux_mod - Ocean-atmosphere flux calculations
> - shr_pio_mod - PIO wrapper, mostly for driver-specific initialization
> - ## shr_strdata_mod - Utilities to handle input files for data models
>   
>   shr_stream_mod - Representation of streams, especially for data models
>   
>   1.
>   
>   Code that should probably be heavily refactored or removed completely.
> - shr_msg_mod - The comments state that shr_file_mod should have
>   replaced this
> - shr_ncread_mod - Utility code for netCDF reads; we should probably
>   use PIO instead
> - shr_scam_mod - Single point/column mode utilities; buggy and doesn't
>   seem targeted to our current needs
> - shr_timer_mod - Minimal timer functionality; we should be using
>   perf_mod instead, which can be done even in portable code using
>   callbacks
> 
> What I would like to propose is to split up csm_share a bit to reflect a)
> the distinction between code that depends on external libraries and code
> that doesn't, and b) the distinction between code that's shared because
> it's very generic and low-level, versus code shared for some other reason.
> 
> What that would mean is that categories 1 and 2 above would be put
> together in a separate library with no dependencies. Category 3 would
> become a library of utilities with the usual CIME dependencies. Category 4
> would be moved to the driver (some of it in driver_cpl/shr, some in
> driver_cpl/driver). And category 5 would get split among those three
> places as appropriate, but hopefully some redundant/dead code could be
> removed in the process. A minor bonus is that we could get rid of the
> outdated name csm_share.
> 
> Thoughts? Is this a reasonable way to split things up? Any ideas for
> library names?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/18.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by quantheory** [comment]
@jedwards4b I actually agree that 2 should be a separate library; I just wasn't sure if it was worth compiling separately because it's so small right now. Your "science utilities" vs. "cime utilities" distinction sounds right to me. I think (hope) that 2 will not stay small if component models are willing to move other science/math utilities into CIME (e.g. writing custom linear interpolation code is my pet peeve, but there are no utilities in `csm_share` for that yet). I do not really have a strong opinion about whether 3 and 4 are separate from each other, though.

`shr_wv_sat_mod` is kind of unique in that I expect it to compile not only outside of CIME, but completely on its own, with only Fortran intrinsics available.

(I fixed the "all labeled 1" issue on the web, but it was too late for the email notifications that were sent out. Markdown was designed to be trivial to convert into HTML, and probably the weirdest consequence of that design is that the number "5" can be rendered as "1" if you get your indentation wrong, which is the mistake I made. I guess that's one reason to always look at the preview when typing things into the GitHub web interface.)

**Comment by quantheory** [comment]
Apologies for being slow to respond recently; I'm quite wrapped up in trying to get some new WACCM5.X configurations to work so that we can try some preliminary runs before Breckenridge.

Continuing the discussion, quoting @apcraig (Tony) from #17:

> ok, i hadn't seen issue 18 before.
> 
> that clarifies the motivation. the problem with splitting these things up is that where they belong is often not static. and people are going to end up dropping code in the wrong place. we have some history of moving code back and forth between shr and drv/shr and other places. at one time, code might belong in one directory and after some code cleanup or some new code, it might need to be moved somewhere else.
> 
> in my opinion, our processes and requirements are not robust enough to do this in a way that will be maintained. i also don't think we should change a long standing standard just because someone doesn't like the shr_ standard or the name of csm_share. could it be different or better, probably. would it fundamentally improve CESM, i doubt it. would it confuse people, yes almost certainly for a while. for all those reasons, i feel this is just an exercise in refactoring that brings little benefit to the project.
> 
> i understand the motivation in wanting to be able to build "low level" code that doesn't depend on anything else. maybe we can add a Filelist that a Makefile could use to the csm_share directory that lists the files that can be built without other dependencies. It seems like there are other ways to support this feature without splitting everything apart and renaming everything.
> 
> tony.......

I'll take this a bit at a time:

> we have some history of moving code back and forth between shr and drv/shr and other places.

Two things:
- This should not happen to the modules in category 1, which are the ones that I'm most concerned about splitting off into a new library. They aren't CIME-specific, and should never be moved to `driver_cpl`. It's usually not too hard to figure out whether something is a generic utility or something specific to climate modeling or to CIME data structures.
- At some point after being split off into a separate library, this code should have its API stabilized. Hopefully most of it should be in good shape already, but some modules should be audited before we commit to keeping their interfaces stable for the long term. (E.g. we shouldn't have three different chdir functions.) But the point is, we should be able to promise to library and parameterization developers that if we provide a library and tell people to rely on it, the interface isn't going to constantly change out from under them.

> in my opinion, our processes and requirements are not robust enough to do this in a way that will be maintained.

If so, we need to adjust our processes and requirements! As a group, we're already expending effort on distinguishing code that can be compiled with few or no dependencies, and code that can't. And in fact I know that at least half of the category 1 modules were deliberately designed to be readily built outside of CESM.

Anyway, I disagree that this is a hard distinction to maintain. It's easy to test that a library has no dependencies: just build it without linking in any externals. I also don't think that it's too hard to figure out what "belongs" to one library or another in most cases. If there's any real doubt, it should probably go into the CIME-specific group until you have a clear idea of why it should be moved elsewhere.

> for all those reasons, i feel this is just an exercise in refactoring that brings little benefit to the project.

We work on different parts of CESM with different needs. The driver and data models don't have to worry about whether or not something builds outside of CIME, because they are part of CIME themselves. Many of the science modules and externals do have to track this, because they are developed at least partly within CESM, but have to work in other programs as well.

> maybe we can add a Filelist that a Makefile could use to the csm_share directory that lists the files that can be built without other dependencies.

The only way I can think of to keep such a list accurate is to actually use it to build different sets of files at different stages, which is at least as complex as just making those files a separate library. Also, I _want_ the distinction to be more visible than that, because otherwise it's too easy for developers to accidentally blur the line between the sets of files, and it's too cumbersome for users to pick out the generic code from CIME utilities. Having separate directories with separate naming conventions that build separate libraries is an effective way of making the difference visible.

**Comment by jedwards4b** [comment]
As I think about this more I think that the category 1 library should be in it's own standalone repository and included as a subtree in cime.   This will allow it to be more easily used without cime.

**Comment by rljacob** [comment]
It could also be presented as a generic library useful for any Fortran application.

**Comment by quantheory** [comment]
That was actually where I wanted to go with this. I didn't make much of a case in the CSEG meeting on Monday, because I was getting a bit burned out on the subject (and due to the pre-Breck crunch), and I just wanted to get some incremental changes started first.

**Comment by rljacob** [comment]
I've thought about doing something similar with MPEU which overlaps with many of the things in category 1 and is useful even if you're not doing coupling.

**Comment by jedwards4b** [comment]
Move to ESMCI issue 852.
