### ISSUE TITLE
Setting different threads per component doesn't work

### ISSUE THREAD

**Issue by rljacob** [CESM-Development/cime#181]
The submit command for jobs with different threads per component (at least one component with different number of threads than others) in not generated correctly by CIME (as of CIME 2.0.16).

For example, on Titan we used to be able to get this run command generated:
aprun -n 680 -N 8 -d 2 $EXEROOT/cesm.exe : -n 256 -N 16 -d 1 $EXEROOT/cesm.exe >&! cesm.log.$LID

taskmaker.pl was used for this but is not used now (?)

@jayeshkrishna has developed a patch to re-enable this but first:  is this expected and do you guys have plans for fixing it?

**Comment by jedwards4b** [comment]
It's a feature that we do not generally use and we were unaware that it was broken.   I think that your patch would be appreciated.

**Comment by jayeshkrishna** [comment]
Thanks. We are in the process of testing the patch, and once we finish the test I will push it into the ACME fork and issue a pull request for it.

**Comment by billsacks** [comment]
@jedwards4b says: This is partly a problem with job launching, but also partly a problem due to components getting number of threads from OMP_GET_NUM_THREADS rather than from the coupler.

**Comment by rljacob** [comment]
I'm pretty sure we changed it so the driver always sets the threads.

**Comment by jedwards4b** [comment]
Moved to ESMCI issue 864
