### ISSUE TITLE
grid-compset consistency check not done for user_compset

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#205]
With cime3.0.7 (haven't tested later versions), if I do:

./create_newcase -case test_1002b -compset IGCLM45 -res f19_g16 -mach yellowstone

I correctly get an error because I didn't specify a GLC grid:

Uncaught exception from user code:
    ERROR: 2000_DATM%QIA_CLM45%SP_SICE_SOCN_RTM_CISM1_SWAV 
 is not supported for 
 a%1.9x2.5_l%1.9x2.5_oi%gx1v6_r%r05_m%gx1v6_g%null_w%null 
 at /glade/p/work/sacks/cesm_code/clm_crop_collapse_transient/cime/utils/perl5lib/Config/ConfigCompsetGrid.pm line 377
    ConfigCompsetGrid::setCompsetGeneralVars('ConfigCase=HASH(0x21f74c0)') called at ./create_newcase line 476

However, if I do the same thing with -user_compset:

./create_newcase -case test_1002 -user_compset 2000_DATM%QIA_CLM45%SP_SICE_SOCN_RTM_CISM1_SWAV -res f19_g16 -mach yellowstone -user_pes_setby clm

it creates the case without a complaint.

It should die in the same way in this case.

**Comment by jedwards4b** [comment]
Why isn't  setCompsetGeneralVars called for user_compset ?

**Comment by billsacks** [comment]
@jedwards4b thinks this is fixed in the perl, but re-broken in the python

**Comment by billsacks** [comment]
It seems this is fixed in the latest version of cime.
