### ISSUE TITLE
Tests fail with "setenv: Too many arguments"

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#209]
With cime3.2.3, all of my tests are still failing, this time with the following in my stderr file (and nothing in stdout):

setenv: Too many arguments

Reproducer:

ERS_D_Ld3.f19_g16.X.yellowstone_pgi

**Comment by billsacks** [comment]
cc @mvertens @sholly

**Comment by jedwards4b** [comment]
Yes I'm sorry.
​ Fixed in cime3.2.4 - no really - i even tested it.   ​
