### ISSUE TITLE
Error check should be added if turn on short-term archiving but do not use submit script

### ISSUE THREAD

**Issue by cacraigucar** [CESM-Development/cime#21]
In 6/1/2015's cseg notes there was the following:

"Note that, for this to work properly, you need to run the 'submit' script (which is what submits the run script and the short-term archive script) – you do NOT want to do bsub < runscript any more."

I spoke with Jay and asked him what would happen if you turned on short-term archiving, but do not use the submit script and used the old bsub<runscript logic.  He said that it would run, but short-term archiving would not happen.  He and I brainstormed putting in checks that halt the run immediately if short-term archiving is turned on and the submit script is not used, but rather the bsub<runscript.

I spoke with Andrew Gettelman about the implications of this and he agreed that this needs to error out immediately.

I would like to encourage that this checking be put in before the beta tag is made as numerous scientists will fall into this trap and wonder why their short-term archiving did not occur.

**Comment by sholly** [comment]
This was fixed with the 'sta_ok' enhancement to the batch system code.
