### ISSUE TITLE
gen_domain Makefile needs to use Macros.make

### ISSUE THREAD

**Issue by ekluzek** [CESM-Development/cime#219]
The Makefile in cime/tools/mapping/gen_domain_files/src needs to point to Macros.make rather than Macros.  Also the INSTALL readme file needs to be updated to say to use the configure in cime/tools. There might be other tools that need this change as well. This is with at least cime4.0.1.

**Comment by mnlevy1981** [comment]
I was just talking to Brian K about this today... I haven't touched the mapping tools documentation in entirely too long. And besides `gen_domain`, I think the `check_maps` and `runoff_to_ocn` tools need `cime/tools/configure` as well.

**Comment by jedwards4b** [comment]
Yes this is an outstanding issue with all of the CESM standalone support
tools

On Thu, Oct 8, 2015 at 9:30 PM, Michael Levy notifications@github.com
wrote:

> I was just talking to Brian K about this today... I haven't touched the
> mapping tools documentation in entirely too long. And besides gen_domain,
> I think the check_maps and runoff_to_ocn tools need cime/tools/configure
> as well.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/219#issuecomment-146746379
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO
