### ISSUE TITLE
Test status: Need better differentiation between RUN and FAIL results

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#22]
The test status of "RUN" is used both to mean "the test is running" and "the test died while running".

This has always been a problem, but it seems to have gotten more prevalent with the recent changes made to the test reporting.

If we want to move towards more automation of test reporting (e.g., emailing you when your test suite is done, with a summary of failures), I think we need to improve the differentiation of this status - so that "RUN" really means "still running", and something else ("FAIL"?) is used when the test died while running.

**Comment by quantheory** [comment]
If a test hangs, or otherwise runs out of time, it can't change its own status away from RUN. But I guess that if we record the job number somewhere, a later script can check on it and change the status to FAIL, if the batch system says that the job already completed.

**Comment by ekluzek** [comment]
Often the RUN status happens with cases that did fail, but because of the
nature of the fail (a seg-fault) it doesn't seem to realize what happened.
It might be MPI to blame where the job is only finally killed on a
time-out? We wouldn't get RUN status's so often if it was only due to
running out of time.

_Erik Kluzek, (CGD at NCAR)_

_National Center for Atmospheric Research_

*Boulder CO, *

_(off) (303)497-1326 (fax) (303)497-1348_

_(skype) ekluzek    (cell) (303)859-0183_

_Pronouns: he/his/him_

_------------------ Home page ------------------------_
- ```
       http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*
  ```
- ```
       https://staff.ucar.edu/users/erik
  ```
  
  https://staff.ucar.edu/users/erik*

_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_

**Comment by billsacks** [comment]
@quantheory - that's a good point. But I agree with @ekluzek 's assessment: it seems like jobs running out of time only account for a small number of these RUN statuses. We're now getting RUN status for some failed SMS jobs, which never used to happen before. For example, SMS_Ld5.f19_g16.ICLM45ED.yellowstone_gnu.clm-edTest gives RUN rather than FAIL. Clearly the test knows that it failed:

$ tail -1 TestStatus.log
 ERROR: SMS_Ld5.f19_g16.ICLM45ED.yellowstone_gnu.clm-edTest.GC.0529-1939.45.g.run failed

$ tail -1 CaseStatus
run FAILED 2015-05-29 20:12:07

Yet this is being (incorrectly, in my opinion) being recorded as a RUN rather than FAIL.

So I'd say there are three steps towards solving this issue:

(1) Fix new problems, such as the above, where the old behavior was correct, and the new behavior is (to my eye) incorrect.

(2) Fix long-standing problems with the reporting of status of multi-run tests, like ERS, which have long been reported as RUN when the first run segment fails (if I remember correctly).

(3) Handle the case of jobs running out of time, such as through the mechanism @quantheory proposed. I have a vague recollection that ACME may have solved this issue in some way, but may be remembering wrong.

**Comment by billsacks** [comment]
Another problem with the "RUN" status was raised recently by Sean Swenson: If you simply grep for FAIL in the test results (which seems like a reasonable thing to do, intuitively), you miss many failures. So at the very least the status should be changed to something like RUNFAIL.

**Comment by billsacks** [comment]
According to @jedwards4b : This has been fixed in the python. In the python, tests are labeled as PEND either if they're either in the queue or running.

@mnlevy1981 suggests differentiating: QUEUED and RUNNING or something like that.

**Comment by jedwards4b** [comment]
I believe that this has been sufficiently addressed.
