### ISSUE TITLE
CLM source code gets rebuilt even if nothing changed

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#223]
I don't know if this is a CLM bug or a CIME bug, but I'll file it as a CIME bug for now.

I have noticed that, if you build a test involving CLM (e.g., SMS_D_Ld3.f10_f10.ICLM45BGCCROP.yellowstone_intel), then rebuild without changing anything, at least some of the CLM source files get rebuilt. So, while the builds for other components happen almost instantly, the CLM rebuild takes about 40 seconds.

**Comment by billsacks** [comment]
cc @jedwards4b @mvertens @ekluzek @bandre-ucar

**Comment by billsacks** [comment]
Some more information on this:

I have reproduced it from r74030 (I believe) of https://svn-ccsm-models.cgd.ucar.edu/clm2/branches/initinterp_vertical. This is basically clm4_5_3_r136, with a few changes that I don't expect to have affected this bug. It uses cime4.0.1.

I created this test:

SMS_D_Ld3.f10_f10.ICLM45BGCCROP.yellowstone_intel

built it, then rebuilt it without changing anything. In the second build, the CLM build took 46 seconds. 

The rebuild began with:

src/main/column_varcon.F90

which has these dependencies (in Depends):

column_varcon.o : clm_varpar.mod shr_assert_mod.mod landunit_varcon.mod ncdio_pio.mod   

Jim's hypothesis is that the dependence on shr_assert, which comes in through this include line:

#include "shr_assert.h"

is causing the rebuild.

**Comment by jedwards4b** [comment]
Fixed with #225

**Comment by rljacob** [comment]
Do you think any cpp commands in file might trigger a re-compile-always?   We're finding that files with #ifdef get recompiled even if nothing changes.

**Comment by ekluzek** [comment]
Hi Rob

Is this for CLM40 or CLM45 code?

We don't have very many #ifdef's in CLM anymore. I only see three files
with #ifdefs, even in clm40 code.

clm40 code does have dependency on CPP token settings which it does put in
a file. If that's put into the dependency chain that could cause the
behavior you are talking about. But, it should be for everything.

For clm45 we now build it in a shared library and reduce the times you have
to rebuild it as we've eliminated most CPP switches in favor of run-time
logical variables.

Could you show an example of the compiler line where a file is recompiled
when it shouldn't have been?

_Erik Kluzek, (CGD at NCAR)_

_National Center for Atmospheric Research_

*Boulder CO, *

_(off) (303)497-1326 (fax) (303)497-1348_

_(skype) ekluzek    (cell) (303)859-0183_

_Pronouns: he/his/him_

_------------------ Home page ------------------------_
- ```
       http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*
  ```
- ```
       https://staff.ucar.edu/users/erik
  ```
  
  https://staff.ucar.edu/users/erik*

_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_

**Comment by rljacob** [comment]
cc'ing @bishtgautam who may have an example.

**Comment by bishtgautam** [comment]
CLM45 doesn't have CPP tokens, but ALMv1 does. New physics added in ALMv1 requires PETSc and at present that new physics is protected by `#ifdef USE_PETSC_LIB`.

**Comment by jedwards4b** [comment]
Do you have new #include statements?   shr_assert.h is treated as a special
case in the cime mkDepends script, if you have other #include files you may
need to generalize this or add them to the special cases.

On Wed, Dec 9, 2015 at 9:22 PM, Gautam Bisht notifications@github.com
wrote:

> CLM45 doesn't have CPP tokens, but ALMv1 does. New physics added in ALMv1
> requires PETSc and at present that new physics is protected by #ifdef
> USE_PETSC_LIB.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/223#issuecomment-163484375
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by bishtgautam** [comment]
Yes, there are  `#include` statements for PETSc. For e.g.

```
!++++++++++++++++++++++++++++++++++++++++
#ifdef USE_PETSC_LIB
module FooType
  ! !PUBLIC TYPES:
  implicit none
  private
#include "finclude/petscsys.h"
#include "finclude/petscvec.h"
#include "finclude/petscvec.h90"
#include "finclude/petscmat.h"
#include "finclude/petscmat.h90"
#include "finclude/petscts.h"
#include "finclude/petscts.h90"
#include "finclude/petscdm.h"
#include "finclude/petscdm.h90"
#include "finclude/petscdmda.h"
#include "finclude/petscdmda.h90"
#include "finclude/petscviewer.h"
  type, public :: foo_type
   ...
   contains
  end type foo_type
end module FooType
!++++++++++++++++++++++++++++++++++++++++
```
