### ISSUE TITLE
B1850G doesn't turn on CLM CROP code

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#238]
CLM should by default turn on both CROP and BGC but in cesm1_5_alpha02d it
isn't turning on crop.

**Comment by jedwards4b** [comment]
This turns out to be because the CLM tag which defined BGC-CROP wasn't made.   Which leads to a new problem which I'll open in a new issue.

**Comment by bandre-ucar** [comment]
This will be fixed in clm r145 in the next day or two.

**Comment by bandre-ucar** [comment]
should be fixed in clm4_5_3_r145.
