### ISSUE TITLE
config_component regex matching is ambiguous and error prone 

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#240]
Currently regular expression matching in the ConfigCase.pm add_config_variables subroutine
is too generous and matching things that should not be matched.  So for example

CLM50%BGC-CROP is matching  CLM50%BGC  and it would match CLM50%BGC-CROP if it were
defined in clm, but its not and so there is a silent error since there is no easy way to see if a match is incomplete.   An attempt to tighten restrictions on regular expression matching for this case revealed that the patterns in config_component.xml across components are ambiguous.   That is restricting this match so that only CLM50%BGC-CROP is matched caused many other cases not to match which 
should be matchs.

**Comment by billsacks** [comment]
see also issue #402

**Comment by jedwards4b** [comment]
Addition of schema for xml files has greatly improved although perhaps not completely eliminated this problem, closing as resolved.
