### ISSUE TITLE
xmlchange commands done by scripts should have '-noecho' flag

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#241]
Background: A few months ago, I put in place an 'echo' capability in xmlchange so that, by default, any xmlchange command the user runs is echoed to the CaseStatus file. The purpose of this is for traceability and reproducibility of the case. However, my intent was to only echo xmlchange commands that were manually run by the user: My feeling (which others agreed with) was that this should just show the commands that a user did manually, and should not be cluttered by xmlchange commands run as part of other commands... again, the idea is that you should be able to use CaseStatus to see what you need to manually do if you want to exactly reproduce the history of a case. (There were some exceptions - e.g., I echo xmlchange commands run by the test scripts, to aid understandability of what the test scripts are doing... in some sense, the test scripts are the "user" in this case.) To accomplish this, I added an optional '-noecho' argument to xmlchange. At the time, I went through the scripts, adding '-noecho' wherever they called xmlchange.

Now to the issue: Since then, a number of other xmlchange commands have been added to the scripts, which do not use '-noecho'. I have fixed some, but more have crept in since then - e.g., with the batch refactor(?).

Short-term solution: Change newly-added xmlchange commands, adding '-noecho'. This includes:
- utils/perl5lib/Batch/BatchUtils.pm:     `./xmlchange CONTINUE_RUN=TRUE`;
- RUN_WITH_SUBMIT=TRUE (set in a few places)
- changing the RESUBMIT number
- maybe others, but those are the ones I have noticed

Longer-term, I'm not sure what the right thing to do is. Possibilities I see are:
1. Education: Making sure that everyone who modifies scripts understands that you almost always should specify -noecho if you have the scripts do an xmlchange command
2. Just live with keeping fixing problems like this as we notice them
3. Come up with some more robust solution. e.g., somehow (I'm not sure how) make xmlchange recognize whether it's being called directly by the user or by some other script, and adjust its default behavior accordingly.

One solution that I would _not_ want is changing the default behavior of xmlchange to noecho: I feel it's better to have some extra crud in CaseStatus than to force the user to remember to specify -echo every time they run xmlchange.

**Comment by billsacks** [comment]
cc @jedwards4b @sholly @mvertens @bertinia

**Comment by jedwards4b** [comment]
Seems to me that if you should almost always use an option - then it's
backward and should do the opposite thing?

On Sat, Oct 17, 2015 at 1:18 PM, Bill Sacks notifications@github.com
wrote:

> cc @jedwards4b https://github.com/jedwards4b @sholly
> https://github.com/sholly @mvertens https://github.com/mvertens
> @bertinia https://github.com/bertinia
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/241#issuecomment-148945197
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by billsacks** [comment]
@jedwards4b : This is what makes it tricky: The scripts should almost always use -noecho, yet a user never should.

**Comment by billsacks** [comment]
Here's one idea for a longer-term solution... it doesn't exactly solve the problem, but it at least makes the problem detectable / auditable:

Introduce perl functions, xml_noecho_change and xml_echo_change. These would simply be wrappers to ./xmlchange, where the first one specifies the '-noecho' argument and the second does not.

Then we would have a convention that all calls to xmlchange from the scripts actually use these xml_noecho_change or xml_echo_change wrappers, rather than calling xmlchange directly. This forces you to consider whether you want a given xmlchange command to be echoed to CaseStatus.

This would allow us to periodically grep for calls to xmlchange in the scripts; any such calls are in error and need to be changed to either xml_noecho_change or xml_echo_change.

**Comment by jedwards4b** [comment]
In my refactor branch in which xmlchange is called through a
subroutine/module call instead of the shell this will be an easy fix.  In
the meantime we can just add the -noecho as you suggest.

On Sat, Oct 17, 2015 at 3:04 PM, Bill Sacks notifications@github.com
wrote:

> Here's one idea for a longer-term solution... it doesn't exactly solve the
> problem, but it at least makes the problem detectable / auditable:
> 
> Introduce perl functions, xml_noecho_change and xml_echo_change. These
> would simply be wrappers to ./xmlchange, where the first one specifies the
> '-noecho' argument and the second does not.
> 
> Then we would have a convention that all calls to xmlchange from the
> scripts actually use these xml_noecho_change or xml_echo_change wrappers,
> rather than calling xmlchange directly. This forces you to consider whether
> you want a given xmlchange command to be echoed to CaseStatus.
> 
> This would allow us to periodically grep for calls to xmlchange in the
> scripts; any such calls are in error and need to be changed to either
> xml_noecho_change or xml_echo_change.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/241#issuecomment-148950835
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by billsacks** [comment]
@jedwards4b : Perfect: I was wondering if this issue would largely go away with the big refactor you're doing... glad to hear that it likely will.

**Comment by mnlevy1981** [comment]
I know we're trying to move away from environment variables, but maybe it makes sense to have xmlchange echo to CaseStatus unless 1 of the following 2 things are true:
1. Run with the -noecho option
2. The $CIME_XMLCHANGE_NOECHO environment variable is set to TRUE

Then we could have a `set CIME_XMLCHANGE_NOECHO=TRUE` call at the top of any scripts that use xmlchange and an `unset CIME_XMLCHANGE_NOECHO` at the end.

It would probably also be useful to have a `-echo` option that would override the environment variable, so in scripts you have to go out of your way to turn on the echo but a user from a shell prompt would need to go out of his or her way to turn off the echo.

**Comment by jedwards4b** [comment]
Addressed in #259 but I'm not sure I got all of them.

**Comment by billsacks** [comment]
fixed in python
