### ISSUE TITLE
Stop requiring user_pes_setby argument to create_newcase

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#242]
If we are going to move to having -user_compset be a more common way of setting up a case (as @mvertens has suggested on a number of occasions), then I feel we really need to make the scripts smart enough to not require the user to specify -user_pes_setby in this case. This -user_pes_setby argument is reasonable for an expert user who understands who sets the PE layout in various situations, but I think it's a lot to ask a new user to know which component is responsible for setting the PE layout for a given user_compset that they're creating.

**Comment by rljacob** [comment]
I agree.  When did -user_pes_setby become a requirement?

**Comment by billsacks** [comment]
@rljacob : I believe the history is: Prior to cime3, -user_compset led to incorrect PE layouts, because the compset wasn't being picked up correctly in the determination of the PE layout. I believe @mvertens fixed this in cime3 (but I may be remembering the exact version wrong), when she reworked how PE layouts were set. She decentralized the config_pes.xml information at that time, and made it so that the scripts knew where to find PE layout information for standard compsets (specified via '-compset'), but not so for '-user_compset' -- so, starting then, -user_pes_setby became a required argument when using -user_compset.

**Comment by billsacks** [comment]
This has been superseded by https://github.com/ESMCI/cime/issues/608
