### ISSUE TITLE
valid_values in SetUpTools too restrictive 

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#247]
I used to be able to set REST_OPTION=$STOP_OPTION

This is no longer allowed:

./xmlchange REST_OPTION=\$STOP_OPTION
ERROR is_valid_value: REST_OPTION has value $STOP_OPTION which is not a valid value 
ERROR is_valid_value: REST_OPTION has value $STOP_OPTION which is not a valid value  at /glade/p/work/jedwards/sandboxes/cesm1_5_alpha/cime.pio2/utils/perl5lib/Config/SetupTools.pm line 358

**Comment by ekluzek** [comment]
We also get this problem...

ERROR is_valid_value: CLM_NML_USE_CASE has value 20thC_glacierMEC_transient which is not a valid value 

Where CLM_NML_USE_CASE should be able to be set to any valid string (the CLM build-namelist will verify it's correct).

**Comment by sholly** [comment]
I've fixed the first issue pending a bit of testing.  Erik, I was not able to reproduce the second issue, I can run './xmlchange CLM_NML_USE_CASE=20thC_glacierMEC_transient' from an I compset case, with no issues.
