### ISSUE TITLE
Most output from test / case setup goes to stderr rather than stdout

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#249]
I expect most output from scripts to go to stdout, with just error messages going to stderr. But I am finding that most of the output from test and case setup, build, etc. is going to the stderr stream.

**Comment by jedwards4b** [comment]
I've been trying to figure out why that happens, something is triggering
the swtich from stdout to stderr, but I don't understand what it is yet.

On Tue, Oct 20, 2015 at 11:59 AM, Bill Sacks notifications@github.com
wrote:

> I expect most output from scripts to go to stdout, with just error
> messages going to stderr. But I am finding that most of the output from
> test and case setup, build, etc. is going to the stderr stream.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/249.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jedwards4b** [comment]
Fixed in #259
