### ISSUE TITLE
Refactor of expected fails

### ISSUE THREAD

**Issue by mvertens** [CESM-Development/cime#257]
The testdb needs to be able to handle what the testreporter spits back.
Carry over the notes that you put in for tests.
Management of expected fails. This needs to be moved out of cime. 
These tasks are dependent on the fix of testreporter.pl.

**Comment by bertinia** [comment]
The testdb code was updated to handle notes carrying forward from one 
test to the next if there is a failure.

**Comment by bertinia** [comment]
This issue was moved to ESMCI/cime#1329
