### ISSUE TITLE
Change job, stdout, stderr via xmlchange

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#258]
Kevin Raeder (DART) requests:

It would be handy if we could change the names of the job, error file,
and output file (and ...?)
in the BSUB commands via xmlchange.  This is obviously not a show stopper.

**Comment by billsacks** [comment]
@jedwards4b says this was addressed via the data assimilation script tool that he put in. We'll check with the DART team post-ESMCI integration

**Comment by jedwards4b** [comment]
Addressed in ongoing data assimilation work in cime5
