### ISSUE TITLE
create_test feature request

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#274]
create_test has an option -testroot that specifies where $CASEROOT goes.

I think it would be useful if there were also an option to specify $CESMSCRATCHROOT. If present, I would set it to a subdirectory of /glade/scratch/$USER and then it would easier to clean up the generated $RUNDIR's, $EXEROOT's, etc. after I'm done with the tests.

Also, should SHAREDLIBROOT use $CESMSCRATCHROOT instead of /glade/scratch/$USER ?

Thanks, Keith

**Comment by billsacks** [comment]
@jedwards4b thinks the SHAREDLIBROOT is fixed in python; the requested option to specify a scratchroot option is not present, but would be a good thing to have
