### ISSUE TITLE
pe layout self-documentation error in run script

### ISSUE THREAD

**Issue by apcraig** [CESM-Development/cime#285]
For a simple X case running on 12 tasks, the self-documentation of the pe layout in the .run file is incorrect.  the "hw pe range" should be 0 to 11 in my test case.  what i'm getting is below.  this was in https://github.com/jedwards4b/cime.git, branch corip1_port.   By the way, I added a "!" in front of each line to suppress it becoming a "H1" type line.

!# PE Layout:
!#   Total number of tasks: 12
!#   Maximum threads per task: 1
!#     cpl ntasks=12 nthreads=1 rootpe=0 ninst=1
!#     xatm ntasks=12 nthreads=1 rootpe=0 ninst=1
!#     xlnd ntasks=12 nthreads=1 rootpe=0 ninst=1
!#     xrof ntasks=12 nthreads=1 rootpe=0 ninst=1
!#     xice ntasks=12 nthreads=1 rootpe=0 ninst=1
!#     xocn ntasks=12 nthreads=1 rootpe=0 ninst=1
!#     xglc ntasks=12 nthreads=1 rootpe=0 ninst=1
!#  
!#    total number of hw pes = 12
!#     cpl hw pe range ~ from 0 to 13
!#     xatm hw pe range ~ from 0 to 13
!#     xlnd hw pe range ~ from 0 to 13
!#     xrof hw pe range ~ from 0 to 13
!#     xice hw pe range ~ from 0 to 13
!#     xocn hw pe range ~ from 0 to 13
!#     xglc hw pe range ~ from 0 to 13

**Comment by jedwards4b** [comment]
Corrected in the corip1_port branch
