### ISSUE TITLE
yellowstone pgi tests fail due to lack of pnetcdf

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#301]
Using cesm1_5_beta02, with cime at cime4.1.8 (also, cism on a branch https://svn-ccsm-models.cgd.ucar.edu/glc/branch_tags/update_external_2015_11_tags/update_external_2015_11_n01_cism2_1_09, but I don't think that's relevant here): All of the pgi tests I have run fail with:

   5: pio_support::pio_die:: myrank=           -1 : ERROR: nf_mod.F90:          725
   5: : PNETCDF not enabled in the build

The pio_typename xml variable is properly getting set to pnetcdf, but the PIO build has:

WITH_PNETCDF:LOGICAL=FALSE

If I source .env_mach_specific.sh for one of the failing cases, I get:

Lmod Error: Cannot find netcdf built for PGI version: 15.1

which is probably the source of the problem.

Tests where this showed up for me are:

RUN ERI_Ly15.f09_g16_gl20.TGHISTIS2.yellowstone_pgi.GC.1111-2047.pgi 
RUN ERS_D_Ld9.f19_g16_gl5.IGCLM45.yellowstone_pgi.cism-override_glc_frac.GC.1111-2047.pgi 
RUN SMS_D_Ly1.f09_g16_gl20.TG1850IS2.yellowstone_pgi.GC.1111-2047.pgi 
RUN ERS_Ly20_N2_P2.f09_g16_gl10.TG.yellowstone_pgi.GC.1111-2047.pgi 
RUN NCK_Ly3.f09_g16_gl20.TGRCP85IS2.yellowstone_pgi.GC.1111-2047.pgi 

However, this problem can also be reproduced by one of the tests in the cime test suite:

ERS_Ld3.f19_g16.X.yellowstone_pgi

I'm labeling this as critical since (as much as I dislike pgi) not being able to run any pgi tests on yellowstone seems like a Bad Thing.

**Comment by jedwards4b** [comment]
This appears to be a system module problem.  I have opened a ticket with
CISL.
You can modify env_mach_specific.xml and change pnetcdf/1.6.0 to
pnetcdf/1.6.1
as a workaround.

On Thu, Nov 12, 2015 at 5:34 AM, Bill Sacks notifications@github.com
wrote:

> Assigned #301 https://github.com/CESM-Development/cime/issues/301 to
> @jedwards4b https://github.com/jedwards4b.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/301#event-462385550.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by billsacks** [comment]
Thanks, @jedwards4b , for getting on top of this quickly. Although it isn't a cime problem, I'll leave this open until the machines problem is resolved so others are aware.

**Comment by billsacks** [comment]
This machines issue appears to be resolved.
