### ISSUE TITLE
Inconsistent treatment of default cism grid

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#302]
For resolutions like f09_g16 and f19_g16, currently a default CISM grid is picked up (gland5UM). However, this is not the case for F compset resolutions (f09_f09, f19_f19, T31_T31).

I looked quickly at what it would take to add this, and it looks like it will take some thought to list the compset regular expressions needed to get this right. So I'm deferring this for now.

This also re-opens the larger issue of whether the GLC (and rof and wav) grids should be picked up implicitly at all. This case shows me why Mariana decided not to do this in the first place.

**Comment by jedwards4b** [comment]
This took me all of about 5 minutes to add, I feel that your protestations
are unwarranted.

On Thu, Nov 12, 2015 at 2:16 PM, Bill Sacks notifications@github.com
wrote:

> For resolutions like f09_g16 and f19_g16, currently a default CISM grid is
> picked up (gland5UM). However, this is not the case for F compset
> resolutions (f09_f09, f19_f19, T31_T31).
> 
> I looked quickly at what it would take to add this, and it looks like it
> will take some thought to list the compset regular expressions needed to
> get this right. So I'm deferring this for now.
> 
> This also re-opens the larger issue of whether the GLC (and rof and wav)
> grids should be picked up implicitly at all. This case shows me why Mariana
> decided not to do this in the first place.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/302.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO
