### ISSUE TITLE
Submit a single job to manage all archiving needs

### ISSUE THREAD

**Issue by mnlevy1981** [CESM-Development/cime#317]
Per discussion from the Nov 30 CSEG meeting, there is currently a long chain of dependencies with some job submissions because the short-term and long-term archivers are submitted as separate jobs but `lt_archiver` needs to wait for `st_archiver` to finish. This is done because CISL has requested that jobs sending data to HPSS use the `hpss` queue. (Additionally, there is a `clobber_archive` script that can be run, the timing of the call is important because it needs both archivers to be finished.)

One possible workaround would be to have a single script that calls `st_archiver`, `lt_archiver`, and `clobber_archive`. Taking advantage of the batch refactor, we could have two new XML variables `JOB_QUEUE_STARCHIVE` and `JOB_QUEUE_LTARCHIVE` so we only use the `hpss` queue if the long-term archiver is active.

**Comment by rljacob** [comment]
Are the archiver scripts very tuned to yellowstone/CISL?

**Comment by jedwards4b** [comment]
They are designed to be portable,

On Tue, Dec 1, 2015 at 1:00 PM, Robert Jacob notifications@github.com
wrote:

> Are the archiver scripts very tuned to yellowstone/CISL?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/317#issuecomment-161078822
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by mnlevy1981** [comment]
I talked with @bertinia and it sounds like this issue isn't too important at the moment... so instead of moving it to the ESMCI issue page I'll just close it here. If at some point in the future we decide to tackle it after all, we'll make a new ticket (in the correct place)
