### ISSUE TITLE
xmlquery doesn't know how to read the env_batch.xml file

### ISSUE THREAD

**Issue by ekluzek** [CESM-Development/cime#318]
The env_batch.xml file has an extra level of XML fields. And as such xmlquery doesn't know how to read it. xmlquery assumes a single level of fields with id and value. This is in cime4.2.3. There was an earlier bug where env_batch.xml wasn't in the list of files, and now it's in the list, but it doesn't know how to read it, so it essentially gets ignored.

**Comment by jedwards4b** [comment]
Fixed in python
