### ISSUE TITLE
ATM_NCPL/ICE_NCPL for G Compsets

### ISSUE THREAD

**Issue by dabail10** [CESM-Development/cime#331]
We want the default for G compsets to be 24 instead of 48 as in the fully-coupled case. This is a one-liner. Can someone add it as a part of the next CIME tag?

cime/driver_cpl/cime_config/config_compsets.xml
# Index: config_component.xml

--- config_component.xml    (revision 6010)
+++ config_component.xml    (working copy)
@@ -2818,7 +2818,7 @@
       <value compset="_DATM%COPYALL_NPS"    >72</value> 
       <value compset="_DATM.*_CLM"          >48</value>  
       <value compset="_DATM.*_DICE.*_POP2"  >4</value>
-      <value compset="_DATM.*_CICE.*_POP2"  >48</value>
-      <value compset="_DATM.*_CICE.*_POP2"  >24</value>
     <value compset="_DATM.*_CICE.*_DOCN"  >24</value>
     <value compset="_DATM.*_DOCN%US20"    >24</value> 
     <value compset="_MPAS"                >1</value>  

Ugh. How do you turn off the Markdown?

**Comment by jedwards4b** [comment]
This is going to be answer changing for G compsets - can you put it in a
pull request that we can defer until alpha05a?

Thanks

On Fri, Dec 11, 2015 at 2:19 PM, dabail10 notifications@github.com wrote:

> We want the default for G compsets to be 24 instead of 48 as in the
> fully-coupled case This is a one-liner Can someone add it as a part of the
> next CIME tag?
> 
> cime/driver_cpl/cime_config/config_compsetsxml
> Index: config_componentxml
> 
> --- config_componentxml (revision 6010)
> +++ config_componentxml (working copy)
> @@ -2818,7 +2818,7 @@
> 72
> 48
> 
> 4
> - 48
> - 24 24 24 1
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/331.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by dabail10** [comment]
Ok.

Dave

On Fri, Dec 11, 2015 at 2:30 PM, jedwards4b notifications@github.com
wrote:

> This is going to be answer changing for G compsets - can you put it in a
> pull request that we can defer until alpha05a?
> 
> Thanks
> 
> On Fri, Dec 11, 2015 at 2:19 PM, dabail10 notifications@github.com
> wrote:
> 
> > We want the default for G compsets to be 24 instead of 48 as in the
> > fully-coupled case This is a one-liner Can someone add it as a part of
> > the
> > next CIME tag?
> > 
> > cime/driver_cpl/cime_config/config_compsetsxml
> > Index: config_componentxml
> > 
> > --- config_componentxml (revision 6010)
> > +++ config_componentxml (working copy)
> > @@ -2818,7 +2818,7 @@
> > 72
> > 48
> > 
> > 4
> > - 48
> > - 24 24 24 1
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/CESM-Development/cime/issues/331.
> 
> ## 
> 
> Jim Edwards
> 
> CESM Software Engineer
> National Center for Atmospheric Research
> Boulder, CO
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/331#issuecomment-164052165
> .

## 

David A Bailey
 email: dbailey_at_ucar.edu
National Center for Atmospheric Research   phone: 303-497-1737
PO Box 3000
fax  : 303-497-1700
Boulder, CO 80307-3000
                   http://www.cgd.ucar.edu/staff/dbailey

**Comment by billsacks** [comment]
@jedwards4b thinks this is done
