### ISSUE TITLE
reset_setup called from ConfigPes.pm does not exist

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#333]
Uncaught exception from user code:
    Can't locate object method "reset_setup" via package "ConfigCase" at /glade/p/work/jedwards/sandboxes/cesm1_5_alpha/cime/utils/perl5lib/Config/ConfigPes.pm line 30.
 at /glade/p/work/jedwards/sandboxes/cesm1_5_alpha/cime/utils/perl5lib/Config/ConfigPes.pm line 30

**Comment by billsacks** [comment]
fixed in python; closing
