### ISSUE TITLE
create_newcase should check for valid case names

### ISSUE THREAD

**Issue by bertinia** [CESM-Development/cime#334]
create_newcase should use the rules defined in the CESM case name conventions doc (http://www.cesm.ucar.edu/models/cesm2.0/casename_conventions_cesm.html) to determine 
and reject any requested case names that include the wildcard characters +, *, ?, {, and } because
these characters interfere with some of the regular expression matching in some of the scripts.

**Comment by mnlevy1981** [comment]
Maybe I should make a new issue for this, but to piggyback -- it would also be nice if `create_newcase` would check for the validity of the case name and all the arguments BEFORE creating `$CASE`. Currently, if `create_newcase` errors out (you give an invalid compset or resolution or whatever), it does so after it creates the case directory so you need to manually remove it before re-running `create_newcase` with the correct arguments.

**Comment by billsacks** [comment]
@mnlevy1981 's comment is fixed in python. Primary issue is not yet fixed

**Comment by jedwards4b** [comment]
This is a duplicate issue ESMCI issue 853
