### ISSUE TITLE
prestager no longer pulls down files from inputdata repository?

### ISSUE THREAD

**Issue by mnlevy1981** [CESM-Development/cime#349]
When building a case on hobart, the output contained

```
    .... calling data prestaging  
File is missing: /fs/cgd/csm/inputdata/ocn/pop/gx1v6/forcing/fesedflux_gx1v6_etopo2v2_Nov2015_vents.nc 
    .... calling build checks 
```

And when I submit the job, POP errors out when it tries to read the above file because it doesn't exist. Shouldn't the scripts try to pull it down from the inputdata SVN repository and then the script errors out if the file wasn't available? (I have since imported it to inputdata, and will manually copy it to hobart... but reporting the issue for future changes to data sets.)

**Comment by jedwards4b** [comment]
I tried reproducing the problem by intentionally setting one of the input files to something that doesn't exist.   It seems to work fine...

```
.... calling data prestaging  
```

Attempting to download missing data
svn: URL 'https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/ocn/pop/gx1v6/forcing/shf_mm_all_85-88_20010308.nc' non-existent in that revision
File was not found in svn repo: https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/ocn/pop/gx1v6/forcing/shf_mm_all_85-88_20010308.nc

**Comment by billsacks** [comment]
@jedwards4b thinks this is fixed
