### ISSUE TITLE
case built with user_compset should match case built with compset alias

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#378]
./create_newcase -case usercase -user_compset 1850_CAM55_CLM50%BGC_CICE_POP2%ECO_MOSART_CISM1%NOEVOLVE_SWAV_BGC%BDRD  -res f09_g16 -mach yellowstone -user_pes_setby allactive

cd /glade/p/work/hannay/cesm_tags/cesm1_5_beta03_cntlexp05/cime/scripts
./create_newcase -case defaultcase -compset B1850  -res f09_g16 -mach yellowstone -user_pes_setby allactive 

Should give the same result, but create_newcase is intentionally bypassing the setCompsetGeneralVars call for user_compset's.    

I don't think that it should do this and I have corrected it in branch cime4.2.3_cntlexp
Can you please review this change in create_newcase and determine if it should be put on the trunk.

**Comment by billsacks** [comment]
fixed
