### ISSUE TITLE
create_newcase should make sure case name is valid

### ISSUE THREAD

**Issue by mnlevy1981** [CESM-Development/cime#38]
A while back I found out that having a '+' in the name of a case will cause the short-term archiver to abort before copying files out of the run directory, and I bet there are other characters that should be avoided as well. It would be nice if create_newcase would prevent the user from using these characters in the first place.

**Comment by billsacks** [comment]
@mnlevy1981 also suggests checking length of case name

**Comment by billsacks** [comment]
Should add a test in ESMCI for this

**Comment by jedwards4b** [comment]
Moved to ESMCI issue 853
