### ISSUE TITLE
ERR test doesn't assure that restart actually worked 

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#382]
The ERR test is designed to test restart capability with short term archiving.  It does the following:
Runs a 5 day test with restart at day 3
archives
Runs a 2 day test restarting from the day 3 restart files and compares the results.

If the variable COMP_RUN_BARRIERS is true then the CONTINUE_RUN flag is not toggled from FALSE to TRUE and this test just does two initial runs.    

It's not clear from the test results that this test fails in that case.   Can we add code to the test to make sure that it did in fact restart and complete the test.   You can force the failure condition by setting COMP_RUN_BARRIERS to TRUE after you set up the case.

**Comment by fischer-ncar** [comment]
This was fixed in the python version.
