### ISSUE TITLE
Should have different RESUBMIT xml variable for use with timing tests

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#386]
https://github.com/CESM-Development/cime/pull/383 and other related recent discussion has highlighted the very unintuitive connection between COMP_RUN_BARRIERS and RESUBMIT. The documentation that @jedwards4b added in https://github.com/CESM-Development/cime/pull/383 helps a bit in this respect, but I still dislike the unintuitiveness of this connection, requiring expert knowledge to understand and use it correctly.

If I understand things correctly: If you're doing timing runs, you sometimes (always? maybe, but I've never known about this myself) want to set COMP_RUN_BARRIERS. It's also helpful to be able to do multiple timing runs at once, so there was an undocumented feature that let you use RESUBMIT for this purpose: If COMP_RUN_BARRIERS was set, then RESUBMIT doesn't set CONTINUE_RUN.

I'd like to propose the addition of a different xml variable that can be used for this purpose: something like RESUBMIT_WITHOUT_CONTINUE_RUN, or something like NUMBER_ADDITIONAL_TRIALS. The logic that checks RESUBMIT would be extended to also look at this variable (and it's an error for both of them to be set): This variable would trigger a resubmit without setting CONTINUE_RUN. Then timing runs could use this new xml variable, and we could get rid of logic that connects COMP_RUN_BARRIERS with RESUBMIT in unintuitive ways.

An alternative - and maybe clearer - implementation would be to add an xml variable like RESUBMIT_SETS_CONTINUE_RUN. By default this would be TRUE, but you could set it to FALSE when using RESUBMIT for the sake of timing runs.

**Comment by billsacks** [comment]
@jedwards4b @apcraig @ekluzek : I'm curious what you think about this proposal.

**Comment by bandre-ucar** [comment]
Remove:

```
RESUBMIT
```

Add:

```
RESUBMIT_IDENTICAL_RUN
RESUBMIT_CONTINUATION_RUN
```

**Comment by mnlevy1981** [comment]
> I'd like to propose the addition of a different xml variable that can be used for this purpose: something like RESUBMIT_WITHOUT_CONTINUE_RUN, or something like NUMBER_ADDITIONAL_TRIALS. The logic that checks RESUBMIT would be extended to also look at this variable (and it's an error for both of them to be set): This variable would trigger a resubmit without setting CONTINUE_RUN. Then timing runs could use this new xml variable, and we could get rid of logic that connects COMP_RUN_BARRIERS with RESUBMIT in unintuitive ways.

Maybe the variable can just be named `REPEAT` or `REPEAT_NOT_CONTINUE`? And when you are checking for errors, it seems like `CONTINUE_RUN` needs to be `FALSE` if `REPEAT` is non-zero?

**Comment by apcraig** [comment]
This all seems so complicated.  I think what we should do is just hide the COMP_RUN_BARRIERS feature, or maybe change it's name to TIMING_ONLY_FLAG or FINEGRAIN_TIMING_OUTPUT or something.  The COMP_RUN_BARRIERS is something that is largely a cseg thing, in my opinion, and is an expert only feature.  I think it's fine to continue to have RESUBMIT depend on that flag.  I think the main thing is just to find a way for it not to be misused.

**Comment by billsacks** [comment]
@apcraig : I disagree with your statement:

> I think it's fine to continue to have RESUBMIT depend on that flag

I see no fundamental reason why RESUBMIT should depend on COMP_RUN_BARRIERS, and I feel like it makes the operation of the scripts unintuitive and error-prone to have these connected.

As just one example: I might want to do a set of timing runs with COMP_RUN_BARRIERS=FALSE, but as it stands I cannot take advantage of the "RESUBMIT without setting CONTINUE_RUN" idea.

In addition, I don't see how my suggestion:

> add an xml variable like RESUBMIT_SETS_CONTINUE_RUN

is more complicated than the current operation: it just makes this more explicit. If you feel that this adds too many independent things you need to set in order to do a timing run, then we could create a user_mods directory with all of the necessary xmlchange commands to do for a typical timing run.

If you still feel like there's a fundamental reason why COMP_RUN_BARRIERS should be tied to RESUBMIT, I'd be interested to hear it. I have added this to the agenda for Monday's CSEG meeting, and maybe we can discuss this more then.

**Comment by apcraig** [comment]
I think it's more complicated because there are more variables and more dependencies and more checks anc compares are required.  I also don't understand why this is suddenly so critical.  This feature has been there for 10 years and it's rarely used.

It's also important to understand what else COMP_RUN_BARRIERS does.  It barriers each run call for every model and then writes the time for each run call on all pes for all models and every timestep.  It's a way to look for temporal and pe load imbalance from real data.

Having said that, I agree that your suggestion,

"As just one example: I might want to do a set of timing runs with COMP_RUN_BARRIERS=FALSE, but as it stands I cannot take advantage of the "RESUBMIT without setting CONTINUE_RUN" idea."

is a good idea.  But again, I think there is a simpler solution.  How about if we add a new option to CONTINUE_RUN called NEVER.  So

TRUE means it's running from restarts
FALSE means it's not running from restart but a RESUBMIT will switch it
NEVER means it's not running from restart and RESUBMIT will NOT switch it.

**Comment by billsacks** [comment]
Tony, your final suggestion is fine with me. For the record, I'm also fine with the suggestions made by @mnlevy1981 and @bandre-ucar .

I wouldn't say this is suddenly "critical", but I opened this issue in response to the major bug caused by CLM improperly setting COMP_RUN_BARRIERS - which triggered the logic that made RESUBMIT not set CONTINUE_RUN, which took people a few days to track down. As far as I can tell, the main reason this hasn't been brought up earlier is that most people were unaware of this feature until now.

**Comment by billsacks** [comment]
To summarize the options on the table (for the sake of the upcoming CSEG meeting discussion):

(1) Do nothing: Continue to have RESUBMIT's behavior depend on COMP_RUN_BARRIERS (possibly renaming that xml variable)

(2) Get rid of this feature entirely

(3) Have two resubmit variables: one that sets CONTINUE_RUN, one that does not
(3a) Keep "RESUBMIT", add RESUBMIT_WITHOUT_CONTINUE_RUN, NUMBER_ADDITIONAL_TRIALS, REPEAT or REPEAT_NOT_CONTINUE
(3b) Delete "RESUBMIT", add RESUBMIT_CONTINUATION_RUNS & RESUBMIT_IDENTICAL_RUNS

(4) Add an xml variable like RESUBMIT_SETS_CONTINUE_RUN (defaults to TRUE)

(5) Add a CONTINUE_RUN option: "NEVER": RESUBMIT will not switch CONTINUE_RUN to TRUE in this case

**Comment by billsacks** [comment]
Feeling from CSEG meeting is to go with option 4: 

> (4) Add an xml variable like RESUBMIT_SETS_CONTINUE_RUN (defaults to TRUE)
