### ISSUE TITLE
Saturation vapor pressure in `shr_flux_mod`

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#39]
In CAM, we've mostly consolidated water vapor saturation calculations into a single module, a modified version of which was added to CIME in #17. `shr_flux_mod` still has its own, different method of determining the humidity at saturation.

Most of the reasons for the CAM changes don't really apply to `shr_flux_mod`. Any of the common approximation methods will give effectively the same answer at reasonable temperatures/pressures over the ocean, and this is not performance-critical code that needs optimization. Still, it's better practice to call the standard routine than to have a series of duplicated/hard-coded formulas, so this should probably be cleaned up some time.

The one caveat is that there's a factor of `0.98` applied to the humidity, which roughly adjusts for the ocean salinity. That factor needs to be kept, in the subroutines where it is present to begin with.

**Comment by billsacks** [comment]
This may already be fixed; need to check this

**Comment by billsacks** [comment]
@jedwards4b or @apcraig should check whether this has been addressed already

**Comment by jedwards4b** [comment]
Moved to ESMCI issue 854
