### ISSUE TITLE
alias naming convention

### ISSUE THREAD

**Issue by fvitt** [CESM-Development/cime#394]
Is there a guide anywhere on the convention used to name compset aliases?
Is see there is an alias "F1850W" and an alias "B1850W".  The "W" in these 2 aliases mean something entirely different.  In one it indicates WACCM and the other it seems to indicate WAV model (or something else).

**Comment by fvitt** [comment]
We will be adding more B compsets for WACCM and CAMChem and it would be nice to know how to name the aliases.

**Comment by billsacks** [comment]
@jedwards4b says yes, there is one. Not yet documented, will be for cesm2

**Comment by jedwards4b** [comment]
This issue was moved to ESMCI/cime#867
