### ISSUE TITLE
MAX_TASKS_PER_NODE and PES_PER_NODE compset dependent

### ISSUE THREAD

**Issue by fvitt** [CESM-Development/cime#397]
Is there a way to set the defaults of MAX_TASKS_PER_NODE and PES_PER_NODE differently depending on compest?   On yellowstone we would like MAX_TASKS_PER_NODE to default to 32 and PES_PER_NODE to default to 16 for some waccm compsets at 1-degrees rather than 30 and 15, respectively.

**Comment by jedwards4b** [comment]
This change is on the exp branch and I think that Bill Sacks is bringing it
to the trunk soon.

On Fri, Mar 18, 2016 at 6:12 PM, fvitt notifications@github.com wrote:

> Is there a way to set the defaults of MAX_TASKS_PER_NODE and PES_PER_NODE
> differently depending on compest? On yellowstone we would like
> MAX_TASKS_PER_NODE to default to 32 and PES_PER_NODE to default to 16 for
> some waccm compsets at 1-degrees rather than 30 and 15, respectively.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/397

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by billsacks** [comment]
Yes, see PR #398
