### ISSUE TITLE
Refactor in 1.1.0 to add perl5lib/Batch breaks unsupported machines

### ISSUE THREAD

**Issue by mnlevy1981** [CESM-Development/cime#40]
On my laptop I have a `~/.cesm/` directory with config_compilers.xml, config_machines.xml, config_pes.xml, and a couple of mkbatch files -- up through cime1.0.8 this worked as expected for creating small test cases, but as of cime1.1.0 I get the following error when running `cesm_setup`:

```
$ ./cesm_setup 
Creating Macros file for ackbar
Searching /Users/mlevy/.cesm/config_compilers.xml for gnu ackbar

Found UNSUPPORTED compiler settings for ackbar_gnu in : /Users/mlevy/.cesm/config_compilers.xml
Creating batch script C.T62_g16.so_ocean_output.003.run 
Could not find batch system for machine ackbar, aborting at /Users/mlevy/codes/CESM/cesm1_4_alpha05f+southern_ocean/cime/utils/perl5lib/Batch/BatchMaker.pm line 200.
```

perl5lib/Batch didn't exist in 1.0.8, so I don't know where to begin trouble-shooting... sorry!

**Comment by bandre-ucar** [comment]
I've patched perl5lib to re-enable userdefined machines in:

https://github.com/bandre-ucar/cime/tree/userdefined

You need to rename ~/.cesm to ~/.cime. Here is an updated config_machines entry:

``` xml
<?xml version="1.0"?>
<config_machines>
  <default_run_suffix>$config{'EXEROOT'}/cesm.exe >> cesm.log.$LID 2>&amp;1</default_run_suffix>
  <machine MACH="seaotter">
    <DESC>Ben Andre (homebrew)</DESC>
    <OS>Darwin</OS>
    <COMPILERS>gnu</COMPILERS>
    <MPILIBS>mpich,mpi-serial</MPILIBS>
    <CESMSCRATCHROOT>$ENV{HOME}/projects/scratch</CESMSCRATCHROOT>
    <RUNDIR>$ENV{HOME}/projects/scratch/$CASE/run</RUNDIR>
    <EXEROOT>$ENV{HOME}/projects/scratch/$CASE/bld</EXEROOT>
    <DIN_LOC_ROOT>$ENV{HOME}/projects/cesm-inputdata</DIN_LOC_ROOT>
    <DIN_LOC_ROOT_CLMFORC>$ENV{HOME}/projects/ptclm-data</DIN_LOC_ROOT_CLMFORC>
    <DOUT_S_ROOT>$ENV{HOME}/projects/scratch/archive/$CASE</DOUT_S_ROOT>
    <DOUT_L_MSROOT>csm/$CASE</DOUT_L_MSROOT>
    <CCSM_BASELINE>$ENV{HOME}/projects/baselines</CCSM_BASELINE>
    <!-- configure cprnc: cmake -DCMAKE_Fortran_COMPILER=/usr/local/bin/mpif90 -DHDF5_DIR=/usr/local -DNetcdf_INCLUDE_DIR=/usr/local/include .. -->
    <CCSM_CPRNC>$CIMEROOT/tools/cprnc/build/cprnc</CCSM_CPRNC>
    <SUPPORTED_BY>andre@ucar.edu</SUPPORTED_BY>
    <GMAKE_J>4</GMAKE_J>
    <MAX_TASKS_PER_NODE>4</MAX_TASKS_PER_NODE>
    <PES_PER_NODE>2</PES_PER_NODE>
    <batch_system type='none'/>
    <mpirun mpilib='mpi-serial'>
       <executable/>
    </mpirun>
    <mpirun mpilib='mpich'>
       <executable>/usr/local/bin/mpirun</executable>
       <arguments>
          <arg name="num_tasks"> -n {{ num_tasks }} </arg>
       </arguments>
    </mpirun>
  </machine>
</config_machines>
```

**Comment by mnlevy1981** [comment]
This worked for me, except I'm having trouble running pio_initdecomp from POP... but at least I can create a case and build an executable! I'll do some comparisons between my local machine and yellowstone tomorrow.

**Comment by jedwards4b** [comment]
Make sure that the pio build properly found the netcdf and/or pnetcdf
libraries.

On Tue, Jul 7, 2015 at 7:25 PM, Michael Levy notifications@github.com
wrote:

> This worked for me, except I'm having trouble running pio_initdecomp from
> POP... but at least I can create a case and build an executable! I'll do
> some comparisons between my local machine and yellowstone tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/40#issuecomment-119392704
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by billsacks** [comment]
@jedwards4b has fixed this in the python: can create a directory in which you put config_machines and config_compilers.

**Comment by jedwards4b** [comment]
Fixed in cime5
