### ISSUE TITLE
ConfigPes.pm fails to find some matches

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#403]
In creating a new "J" compset, I added the following to the bottom of cime_config/cesm/allactive/config_pes.xml:

```
  <!-- J compset (all active except data atmosphere)
       Laid out as follows:
       |LND|ICE|ATM|OCN|
       |ROF|
       |..CPL..|
       |......GLC......|
  -->
  <!-- Ideally, we wouldn't specify the atmosphere resolution here, because it
       is irrelevant. However, ConfigPES doesn't seem to match the grid properly
       unless the atmosphere resolution is specified. -->
  <grid name="a%0.9x1.25.+l%0.9x1.25.+oi%gx1">
     <mach name="any">
        <pes pesize="any" compset="DATM.+CLM.+CICE.+POP">
           <comment>Load balanced for 1850_DATM%CRU_CLM50%BGC_CICE_POP2_MOSART_CISM2_SWAV on yellowstone</comment>
           <ntasks>
              <ntasks_atm>-2</ntasks_atm>
              <ntasks_lnd>-18</ntasks_lnd>
              <ntasks_rof>-18</ntasks_rof>
              <ntasks_ice>-12</ntasks_ice>
              <ntasks_ocn>-32</ntasks_ocn>
              <ntasks_glc>-64</ntasks_glc>
              <ntasks_wav>1</ntasks_wav>
              <ntasks_cpl>-30</ntasks_cpl>
           </ntasks>
           <nthrds>
          <nthrds_atm>1</nthrds_atm>
          <nthrds_lnd>1</nthrds_lnd>
          <nthrds_rof>1</nthrds_rof>
          <nthrds_ice>1</nthrds_ice>
          <nthrds_ocn>1</nthrds_ocn>
          <nthrds_glc>1</nthrds_glc>
          <nthrds_wav>1</nthrds_wav>
          <nthrds_cpl>1</nthrds_cpl>
           </nthrds>
           <rootpe>
              <rootpe_atm>-30</rootpe_atm>
              <rootpe_lnd>0</rootpe_lnd>
              <rootpe_rof>0</rootpe_rof>
              <rootpe_ice>-18</rootpe_ice>
              <rootpe_ocn>-32</rootpe_ocn>
              <rootpe_glc>0</rootpe_glc>
              <rootpe_wav>0</rootpe_wav>
              <rootpe_cpl>0</rootpe_cpl>
           </rootpe>
        </pes>
     </mach>
  </grid>
```

However, ConfigPes.pm seemed not to find this block. It gave the following output:

```
ConfigPES: grid          is a%0.9x1.25_l%0.9x1.25_oi%gx1v6_r%r05_m%gx1v6_g%gland4_w%null 
ConfigPES: compset       is 1850_DATM%CRU_CLM50%BGC_CICE_POP2_MOSART_CISM2_SWAV 
ConfigPES: grid match    is a%0.9x1.25.+l%0.9x1.25.+oi%gx1 
ConfigPES: machine match is yellowstone
Use of uninitialized value $compset_match in concatenation (.) or string at
    /glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/cime/utils/perl5lib/Config/ConfigPes.pm line 270 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.

    To help you figure out what was undefined, perl will try to tell you the
    name of the variable (if any) that was undefined. In some cases it cannot
    do this, so it also tells you what operation you used the undefined value
    in.  Note, however, that perl optimizes your program and the operation
    displayed in the warning may not necessarily appear literally in your
    program.  For example, "that $foo" is usually optimized into "that "
    . $foo, and the warning will refer to the concatenation (.) operator,
    even though there is no . in your program.

ConfigPES: compset_match is 
Use of uninitialized value $pesize_match in concatenation (.) or string at
    /glade/scratch/sacks/cesm_code/cesm1_5_alpha06c_newCIME/cime/utils/perl5lib/Config/ConfigPes.pm line 271 (#1)
ConfigPES: pesize match  is  
```

If I understand this code correctly, what's happening is the following:
- ConfigPes tries to find the most specific match in terms of grid and mach
- In this case, there are some blocks that have specific grid and mach (yellowstone) that match (blocks other than the above block). So those take precedence over the above block, which uses mach="any".
- Then ConfigPes looks for compset / pesize matches within the set of blocks that match grid and mach. In this case there are none: The only block that matches the compset is the above block, which has mach="any"
- So ConfigPes defaults to the very first block (the one that matches anything)

**Comment by billsacks** [comment]
In talking this through with @mvertens , I believe what needs to be done is that the parsing of config_pes.xml should be split into two stages:

(1) Find all possible matches for the current case. This stage would consider all attributes (grid, mach, pesize and compset) together. Settings of "any" would match anything.

(2) Of the possible PE layouts identified in stage (1), pick the "best match". We need to make some subjective decisions as to what constitutes the "best match" - e.g., if one layout matches mach & grid, with pesize="any" and compset="any", and another matches pesize and compset (with mach="any" and grid="any"). Personally, I don't care how this prioritization is done.

The problem with the current code is that it tries to intermingle subsetting and prioritization, so that the universe of possibilities isn't necessarily complete. That is, a block can be excluded from the set of possible matches because, in the grid & mach matching stage, it has lower priority than some other block - since grid & mach matching are done first, and then pesize and compset matching are done later, in a totally separate step.

**Comment by jedwards4b** [comment]
fixed in cime5
