### ISSUE TITLE
Most of the time in strdata time interpolation is spent in getting the factors...

### ISSUE THREAD

**Issue by ekluzek** [CESM-Development/cime#427]
csm_share/shr/shr_strdata_mod.F90 spends too much time in getting the factors for the time-interpolation. This is for the ndep stream in CLM which is annual data, so the reads are minimal. Getting the factors is more expensive than actually doing the time-interpolation on the array.

ndepdyn_strd_adv_total                              1.0e+07    540     7.555     0.485     9.827 (   489)     7.386 (   391)
ndepdyn_strd_adv_readLBUB                           1.0e+07    540     0.151     0.006     0.175 (    89)     0.138 (   434)
ndepdyn_strd_adv_rearr                                  540    540     0.000     0.000     0.001 (    26)     0.000 (   522)
ndepdyn_strd_adv_tint                               1.0e+07    540     7.294     0.485     9.532 (   489)     7.140 (   291)
ndepdyn_strd_adv_tint_getFact                       1.0e+07    540     7.262     0.485     9.501 (   489)     7.109 (   291)

I can speed it up a good amount by changing the tint method to "nearest" and I can cut the time substantially by using the ESMF library rather than the 

Here's the section of the code that I'm concerned about...

```
 elseif (trim(SDAT%tintalgo(n)) /= trim(shr_strdata_nullstr)) then

    call t_startf(trim(lstr)//trim(timname)//'_tint')
    call t_startf(trim(lstr)//trim(timname)//'_tint_getFact')
    call shr_tInterp_getFactors(SDAT%ymdlb(n),SDAT%todlb(n),SDAT%ymdub(n),SDAT%todub(n), &
                                ymdmod(n),todmod,flb,fub, &
                                calendar=SDAT%stream(n)%calendar,algo=trim(SDAT%tintalgo(n)))
    if (debug > 0) then
       write(logunit,*) trim(subname),' interp = ',n,flb,fub
    endif
    call t_stopf(trim(lstr)//trim(timname)//'_tint_getFact')
    SDAT%avs(n)%rAttr(:,:) = SDAT%avFLB(n)%rAttr(:,:)*flb + SDAT%avFUB(n)%rAttr(:,:)*fub
    call t_stopf(trim(lstr)//trim(timname)//'_tint')
```

So there's an inordinate amount of time spent in shr_tInterp_getFactors. The code in shr_tInterp_getFactors isn't that complex, but it sets up and handles a bunch of complex ESMF objects. Some of these don't need to be created again with each call. A design change that would retain some of these might perform better.

**Comment by billsacks** [comment]
@ekluzek will send test cases to @apcraig to look at

**Comment by billsacks** [comment]
Closing this old issue; I'm not sure if it has been fixed. Feel free to reopen in ESMCI/cime if necessary.
