### ISSUE TITLE
num_inst_esp must be 1, but isn't for NCK tests

### ISSUE THREAD

**Issue by fischer-ncar** [CESM-Development/cime#429]
I'm getting the follow error messages for NCK tests.

   5: ERROR: (seq_mct_drv) ERROR: num_inst_esp must be 1
   5:Image              PC Routine            Line        Source
   5:cesm.exe           00000000039CD09D Unknown               Unknown  Unknown
   5:cesm.exe           00000000032A7C96 shr_sys_mod_mp_sh         401  shr_sys_mod.F90
   5:cesm.exe           000000000041B412 cesm_comp_mod_mp_        1562  cesm_comp_mod.F90
   5:cesm.exe           0000000000423ADB MAIN__                     92  cesm_driver.F90
   5:cesm.exe           000000000040CB3E Unknown               Unknown  Unknown
   5:libc.so.6          00002B2172ED0D5D Unknown               Unknown  Unknown
   5:cesm.exe           000000000040CA49 Unknown               Unknown  Unknown

These are a couple of the tests that failed.

NCK_Ld1.f10_f10.ICRUCLM45.yellowstone_intel.clm-default.GC.c1_5_a6h_int
NCK_Ld5.f19_g16.BC5L45BGCRG.yellowstone_intel.allactive-cism-test_coupling.GC.c1_5_a6h_int

**Comment by gold2718** [comment]
I fixed this by removing the num_inst_esp == 1 requirement for now. Also, found and fixed ESP configuration omissions in some build scripts (including NCK).
