### ISSUE TITLE
config_compilers element selection

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#43]
I've written a tentative schema for a new `config_compilers` format, to satisfy unit test requirements and clean up some odd quirks, e.g. using an `append="true"` attribute instead of the `ADD_` prefix. (This is coming soon, to a PR near you!) Going through the changes that are needed for `SetupTools.pm`, I'm trying to figure out how we can be more consistent about how to select elements to be included in the `Macros` file (or the equivalent CMake file).

Right now, the way that the `ADD_` prefix is handled is a little weird. If you have multiple `ADD_FFLAGS` entries with different attributes (e.g. `DEBUG=TRUE` on one and `MODEL=datm` on another), they will accumulate. However, if they have the same attributes _in the same order_, the last one will overwrite the others, whether or not they are in different `compiler` blocks. I'm just going to simplify this. The `ADD_` flag settings (or in my new format, the `append="true"` settings) should always accumulate, and never overwrite any previously-specified flags.

I feel pretty good about that change, but I'm less clear about what to do with settings that _do_ need to overwrite each other (especially the ones that aren't flags at all, e.g. paths). The options I've come up with:
1. Keep the current order dependence. When there are multiple elements that match the current run, the last one always wins. This is easy to implement. The problem is, it's easy to make the mistake of thinking that the most specific setting always wins, when it's actually the last one in the file. In fact, there are some elements in the "wrong" order in the file right now, e.g. the bluewaters+pgi section is before the generic bluewaters section, instead of after. This works correctly only if the two `compiler` elements happen to not set any of the same variables as each other.
2. Pick a setting based on how specific the `compiler` attributes are, regardless of order in the file:
   - A block with a matching `MACH` attribute is considered very specific, so it always takes precedence over one with `MACH` omitted.
   - If that's not enough to pick a unique setting for a given variable, a matching `OS` always takes precedence over an omitted `OS`.
   - If that's still not enough, a matching `COMPILER` wins over an omitted one.
   - I don't think that `MPILIB` really belongs here, but we could check that too.
   - If we haven't narrowed it down to one option after those checks, throw an error.
   
   This is also relatively simple to implement and understand. But we lose the ability to make any non-appended variables conditional on `DEBUG`, `compile_threaded`, and so on. We'd probably be forced to set some system paths in `env_mach_specific` instead.
   
   (We could add attributes like `DEBUG` to the above list, but I think that makes things too confusing. It's easy to say that a setting for yellowstone in particular is more specific than a setting that applies to any Linux system. But it's nonsense to say that a `DEBUG` setting is more specific than a `compile_threaded` setting.)
3. Do the same thing as option 2, but allow `DEBUG`, `compile_threaded`, etc., as long as we can unambiguously figure out what "more specific" is. So this is OK:
   
   ``` xml
   <SOME_LIB_DIR DEBUG="false">/path/to/whatever</SOME_LIB_DIR>
   <SOME_LIB_DIR DEBUG="false" compile_threaded="true">/path/to/whatever/else</SOME_LIB_DIR>
   ```
   
   This would not be OK, and `SetupTools` would give you some ambiguity error:
   
   ``` xml
   <SOME_LIB_DIR DEBUG="false">/path/to/whatever</SOME_LIB_DIR>
   <SOME_LIB_DIR compile_threaded="true">/path/to/whatever/else</SOME_LIB_DIR>
   ```
   
   I _think_ that this would be the best option, as long as the ambiguity error message was pretty clear. We wouldn't have to worry about the order of elements, it would let you do essentially the same things as you can do now, and it might catch some errors where you forget to handle two options that can interact. But the Perl code gets a little thornier.

I think @jedwards4b and @bertinia would be most interested in this (if I'm not making it too complex/wordy).

**Comment by jedwards4b** [comment]
I think that you want Option 3.   Is there anything currently in
config_compilers.xml that could not be expressed this way?

On Fri, Jul 10, 2015 at 4:28 PM, Sean Patrick Santos <
notifications@github.com> wrote:

> I've written a tentative schema for a new config_compilers format, to
> satisfy unit test requirements and clean up some odd quirks, e.g. using an
> append="true" attribute instead of the ADD_ prefix. (This is coming soon,
> to a PR near you!) Going through the changes that are needed for
> SetupTools.pm, I'm trying to figure out how we can be more consistent
> about how to select elements to be included in the Macros file (or the
> equivalent CMake file).
> 
> Right now, the way that the ADD_ prefix is handled is a little weird. If
> you have multiple ADD_FFLAGS entries with different attributes (e.g.
> DEBUG=TRUE on one and MODEL=datm on another), they will accumulate.
> However, if they have the same attributes _in the same order_, the last
> one will overwrite the others, whether or not they are in different
> compiler blocks. I'm just going to simplify this. The ADD_ flag settings
> (or in my new format, the append="true" settings) should always
> accumulate, and never overwrite any previously-specified flags.
> 
> I feel pretty good about that change, but I'm less clear about what to do
> with settings that _do_ need to overwrite each other (especially the ones
> that aren't flags at all, e.g. paths). The options I've come up with:
> 
>    1.
> 
>    Keep the current order dependence. When there are multiple elements
>    that match the current run, the last one always wins. This is easy to
>    implement. The problem is, it's easy to make the mistake of thinking that
>    the most specific setting always wins, when it's actually the last one in
>    the file. In fact, there are some elements in the "wrong" order in the file
>    right now, e.g. the bluewaters+pgi section is before the generic bluewaters
>    section, instead of after. This works correctly only if the two
>    compiler elements happen to not set any of the same variables as each
>    other.
>    2.
> 
>    Pick a setting based on how specific the compiler attributes are,
>    regardless of order in the file:
>     - A block with a matching MACH attribute is considered very specific,
>       so it always takes precedence over one with MACH omitted.
>       - If that's not enough to pick a unique setting for a given
>       variable, a matching OS always takes precedence over an omitted OS.
>       - If that's still not enough, a matching COMPILER wins over an
>       omitted one.
>       - I don't think that MPILIB really belongs here, but we could check
>       that too.
>       - If we haven't narrowed it down to one option after those checks,
>       throw an error.
> 
>    This is also relatively simple to implement and understand. But we
>    lose the ability to make any non-appended variables conditional on
>    DEBUG, compile_threaded, and so on. We'd probably be forced to set
>    some system paths in env_mach_specific instead.
> 
>    (We could add attributes like DEBUG to the above list, but I think
>    that makes things too confusing. It's easy to say that a setting for
>    yellowstone in particular is more specific than a setting that applies to
>    any Linux system. But it's nonsense to say that a DEBUG setting is
>    more specific than a compile_threaded setting.)
>     3.
> 
>    Do the same thing as option 2, but allow DEBUG, compile_threaded,
>    etc., as long as we can unambiguously figure out what "more specific" is.
>    So this is OK:
> 
>    <SOME_LIB_DIR DEBUG="false">/path/to/whatever</SOME_LIB_DIR>
>    <SOME_LIB_DIR DEBUG="false" compile_threaded="true">/path/to/whatever/else</SOME_LIB_DIR>
> 
>    This would not be OK, and SetupTools would give you some ambiguity
>    error:
> 
>    <SOME_LIB_DIR DEBUG="false">/path/to/whatever</SOME_LIB_DIR>
>    <SOME_LIB_DIR compile_threaded="true">/path/to/whatever/else</SOME_LIB_DIR>
> 
>    I _think_ that this would be the best option, as long as the ambiguity
>    error message was pretty clear. We wouldn't have to worry about the order
>    of elements, it would let you do essentially the same things as you can do
>    now, and it might catch some errors where you forget to handle two options
>    that can interact. But the Perl code gets a little thornier.
> 
> I think @jedwards4b https://github.com/jedwards4b and @bertinia
> https://github.com/bertinia would be most interested in this (if I'm
> not making it too complex/wordy).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/43.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by quantheory** [comment]
I don't think there's an issue. It gets a bit awkward if one variable references another, since that kind of forces one to be declared before the other. But I don't think that it's insurmountable; most of the variables referenced in `config_compilers` are set in the environment, so we can probably work out something for the very few cases where different Macros variables refer to each other.

Also, we need to sort out which is which anyway, since CMake uses different syntax to deal with environment variables than CMake variables.

**Comment by quantheory** [comment]
I am closing this in favor of #371, which encompasses this issue and much more.
