### ISSUE TITLE
NTASKS_ESP undefined causing some compset to not build

### ISSUE THREAD

**Issue by fischer-ncar** [CESM-Development/cime#430]
I'm getting NTASKS_ESP: Undefined variable, then the build fails.  Here's a lists of tests that failed.

ERP_Ld3.f19_f19.FW5SC.yellowstone_intel.cam-outfrq3d.GC.c1_5_a6h_int
ERP_Ln9.f09_f09.FC55CLUBB.yellowstone_intel.cam-outfrq9s.GC.c1_5_a6h_int
ERP_Ln9.f19_f19.FC4AQUAP.yellowstone_intel.cam-outfrq9s.GC.c1_5_a6h_int
ERP_Ln9.f19_f19.FMOZMAM.yellowstone_intel.cam-outfrq9s.GC.c1_5_a6h_int
ERP_Ln9.f19_f19.FSTRATMAM7.yellowstone_intel.cam-outfrq9s.GC.c1_5_a6h_int
ERP_Ln9.f19_f19.FSTRATVBSL45.yellowstone_intel.cam-outfrq9s.GC.c1_5_a6h_int
ERP_Ln9.f19_f19.FW5.yellowstone_intel.cam-outfrq9s.GC.c1_5_a6h_int
ERP_Ln9.f19_f19.FWX.yellowstone_intel.cam-outfrq9s.GC.c1_5_a6h_int
ERP_Ln9.f19_f19.FWXI.yellowstone_intel.cam-outfrq9s.GC.c1_5_a6h_int

**Comment by fischer-ncar** [comment]
Something that might be related to this issue are these warning message

No Match found for NTASKS_ESP, using 180 at /glade/u/home/fischer/code/cesm1_5_alpha06h/cime/utils/perl5lib/Config/ConfigPes.pm line 317.
No Match found for NTHRDS_ESP, using 2 at /glade/u/home/fischer/code/cesm1_5_alpha06h/cime/utils/perl5lib/Config/ConfigPes.pm line 321.
No Match found for ROOTPE_ESP, using 0 at /glade/u/home/fischer/code/cesm1_5_alpha06h/cime/utils/perl5lib/Config/ConfigPes.pm line 325.

One place I found these messages was ERS.f19_g16.B1850W.yellowstone_intel.

Chris

**Comment by gold2718** [comment]
I am testing fixes for this and related issues (a few instances of ESP settings were left out of the of the test build scripts). However, I have not modified the entries in the <cime>/scripts/Testing/t directory. Is that being used anymore?

**Comment by gold2718** [comment]
Fixed via pull request #428
