### ISSUE TITLE
ESMF test fails with ESP error

### ISSUE THREAD

**Issue by fischer-ncar** [CESM-Development/cime#439]
ERS_E_Ld7.f19_g16.B1850.yellowstone_intel.allactive-defaultio.GC test is failing with the following 
error message.

106: In esp register routine
106:MCT::m_AttrVect::indexRA_:: ERROR--attribute not found: "area" Traceback:
106:aa area -MCT::m_AttrVect::indexRA_
106:MCT::m_AttrVect::indexRA_:: ERROR--attribute not found: "aream" Traceback:
106:aa aream-MCT::m_AttrVect::indexRA_

**Comment by gold2718** [comment]
Is there a tag which exhibits this bug? What checkout do I use?

**Comment by fischer-ncar** [comment]
Use https://svn-ccsm-models.cgd.ucar.edu/cesm1/alphas/tags/cesm1_5_alpha06i/

**Comment by gold2718** [comment]
Over in #443, @fischer-ncar commented that the ESMF_E test still fails. Is this with an updated CIME that has the #443 fix? I tried the compset above using current CESM alpha branch (https://svn-ccsm-models.cgd.ucar.edu/cesm1/alphas/branches/cesm1_5_alpha07) and it completed. Files are in: /glade/scratch/goldy/ERS_E_Ld7.f19_g16.B1850.yellowstone_intel.allactive-defaultio.github439

**Comment by fischer-ncar** [comment]
Strange, I tried the ERS_E test with the alpha07 tag and it failed for me.  I'll try it again.

**Comment by gold2718** [comment]
If it does fail for you, please post the build and run directories along with the tag. I did this test from a fresh checkout of the alpha07 branch (not a tag). It is using cime4.5.12.

**Comment by fischer-ncar** [comment]
It passed for me.  Not sure why it didn't pass the first time.  I did do a clean checkout.

**Comment by billsacks** [comment]
fixed.
