### ISSUE TITLE
add python script to script/Tools that creates a complete restart set of files for a case

### ISSUE THREAD

**Issue by bertinia** [CESM-Development/cime#444]
Modify Matt Long's cesm_restart_pkg.py script to generate a complete CESM restart
directory. The current script had the following hardcoded values that need to
turned into command line arguments (examples below):
    refcase = 'b.e15.B1850.f09_g16.pi_control.all.59'
    refroot = '/glade/p/cesm0005/archive/'+refcase
    date = datetime(4,1,1)
    pathout = '/glade/scratch/aliceb/b.e15.B1850.f09_g16.pi_control.all.59/restart-0004-01-01'

Note: Matt used the datetime.strftime method which requires a patch to work with years prior to 1900.

**Comment by billsacks** [comment]
circumvented by new features in the python st_archive put in place by @mvertens
