### ISSUE TITLE
create_newcase: verbose is broken

### ISSUE THREAD

**Issue by cacraigucar** [CESM-Development/cime#450]
In both cime4.4.0 and the ESCMI version of cime, the help message says that there is a "-verbose" or "-v" option.  Whichever flag I use in either of the cime versions, I get a message that is an "unknown option"

**Comment by jedwards4b** [comment]
This option is working in both forms in esmci:
 ./create_newcase --verbose --case foo2 --compset B1850 --res f19_g16
**WARNING:CIME.utils:Log level set to VERBOSE**
CIME.case    INFO     Compset longname is 1850_CAM55_CLM50%BGC_CICE_POP2%ECO_MOSART_CISM1%NOEVOLVE_SWAV_BGC%BDRD 
CIME.case    INFO     Compset specification file is /glade/p/work/jedwards/sandboxes/cesm1_5_alpha06_esmci/cime/scripts/Tools/../../cime_config/cesm/allactive/config_compsets.xml
CIME.case    INFO     Pes     specification file is /glade/p/work/jedwards/sandboxes/cesm1_5_alpha06_esmci/cime/scripts/Tools/../../cime_config/cesm/allactive/config_pes.xml

Directory /glade/scratch/jedwards/foo2/bld already exists, (r)eplace, (a)bort, or (u)se existing?r

Directory /glade/scratch/jedwards/foo2/run already exists, (r)eplace, (a)bort, or (u)se existing?r
CIME.XML.pes INFO     Pes setting: grid          is a%1.9x2.5_l%1.9x2.5_oi%gx1v6_r%r05_m%gx1v6_g%gland5UM_w%null 
CIME.XML.pes INFO     Pes setting: compset       is 1850_CAM55_CLM50%BGC_CICE_POP2%ECO_MOSART_CISM1%NOEVOLVE_SWAV_BGC%BDRD 
CIME.XML.pes INFO     Pes setting: grid match    is a%1.9x2.5.+l%1.9x2.5.+oi%gx1 
CIME.XML.pes INFO     Pes setting: machine match is yellowstone 
CIME.XML.pes INFO     Pes setting: compset_match is any 
CIME.XML.pes INFO     Pes setting: pesize match  is any 
CIME.case    INFO      Compset is: 1850_CAM55_CLM50%BGC_CICE_POP2%ECO_MOSART_CISM1%NOEVOLVE_SWAV_BGC%BDRD 
CIME.case    INFO      Grid is: a%1.9x2.5_l%1.9x2.5_oi%gx1v6_r%r05_m%gx1v6_g%gland5UM_w%null 
CIME.case    INFO      Components in compset are: ['cam', 'clm', 'cice', 'pop', 'mosart', 'cism', 'swav', 'sesp'] 
CIME.utils   INFO     Using project from env ACCOUNT P93300606
CIME.case    INFO      Creating Case directory /glade/p/work/jedwards/sandboxes/cesm1_5_alpha06_esmci/cime/scripts/foo2
yslogin5: ~/sandboxes/cesm1_5_alpha06_esmci/cime/scripts
:) ./create_newcase -v --case foo2 --compset B1850 --res f19_g16
**WARNING:CIME.utils:Log level set to VERBOSE**
ERROR: Case directory /glade/p/work/jedwards/sandboxes/cesm1_5_alpha06_esmci/cime/scripts/foo2 already exists

**Comment by cacraigucar** [comment]
I'm not sure what I did wrong before, but now when I'm in the ESMCI version, it is working for me as well.  Sorry for the false alarm.
