### ISSUE TITLE
Subscript out of bounds for PE_LOC in driver...

### ISSUE THREAD

**Issue by ekluzek** [CESM-Development/cime#451]
In cesm1_5_beta06 with cime5.6.0 this test

ERS_D_Ld3.f09_g16_gl5.IG1850CRUCLM50BGCCROP.yellowstone_intel.clm-clm50KitchenSink

dies with the following error...

600:(seq_domain_areafactinit) : min/max mdl2drv    1.00000000000000       1.00000000000000    areafact_a_ATM
 600:(seq_domain_areafactinit) : min/max drv2mdl    1.00000000000000       1.00000000000000    areafact_a_ATM
 181:forrtl: severe (408): fort: (3): Subscript #1 of the array PE_LOC has value 1 which is less than the lower bound of 215635328
 181:
 181:Image              PC                Routine            Line        Source
 181:cesm.exe           000000000519C370  Unknown               Unknown  Unknown
 181:cesm.exe           0000000004B2C2F8  m_globalsegmap_mp        1150  m_GlobalSegMap.F90
 181:cesm.exe           0000000004B2E697  m_globalsegmap_mp        1471  m_GlobalSegMap.F90
 181:cesm.exe           0000000000728EDC  seq_io_mod_mp_seq        1641  seq_io_mod.F90
 181:cesm.exe           00000000007593BC  seq_rest_mod_mp_s         252  seq_rest_mod.F90
 181:cesm.exe           00000000004384FA  cesm_comp_mod_mp_        1901  cesm_comp_mod.F90
 181:cesm.exe           00000000004522B6  MAIN__                     92  cesm_driver.F90
 181:cesm.exe           00000000004179AE  Unknown               Unknown  Unknown
 181:libc.so.6          00002B120641BD5D  Unknown               Unknown  Unknown
 181:cesm.exe           00000000004178B9  Unknown               Unknown  Unknown

**Comment by ekluzek** [comment]
PGI tests fail as well. The output looks a little different, but looks like it's the same issue...

 264:Abort(2) on node 264 (rank 264 in comm 1140850688): application called MPI_Abort(MPI_COMM_WORLD, 2) - process 264
 264:INFO: 0031-306  pm_atexit: pm_exit_value is 1.
 229:MCT::m_AttrVect::lsize_: attribute array length mismatch error, stat =-3634
 182:MCT::m_AttrVect::lsize_: attribute array length mismatch error, stat =-143
 182:0B6.MCT(MPEU)::die.: from MCT::m_AttrVect::lsize_()
 182:Abort(2) on node 182 (rank 182 in comm 1140850688): application called MPI_Abort(MPI_COMM_WORLD, 2) - process 182
 182:INFO: 0031-306  pm_atexit: pm_exit_value is 1.
 229:0E5.MCT(MPEU)::die.: from MCT::m_AttrVect::lsize_()
 229:Abort(2) on node 229 (rank 229 in comm 1140850688): application called MPI_Abort(MPI_COMM_WORLD, 2) - process 229
 229:INFO: 0031-306  pm_atexit: pm_exit_value is 1.
 332:MCT::m_AttrVect::lsize_: attribute array length mismatch error, stat =-4
 106:0: Subscript out of range for array gsmap%pe_loc (/glade/scratch/erik/cesm1_5_beta06/cime/externals/mct/mct/m_GlobalSegMap.F90: 1150)
 106:    subscript=1, lower bound=0, upper bound=-1074790401, dimension=1

That's for the test: ERI_D_Ld9.f09_g16.ICLM45BGC.yellowstone_pgi.clm-default

**Comment by ekluzek** [comment]
All of the following tests also fail with the issue. There is one test that is not in DEBUG mode and it fails without giving indication of what's wrong, but the DEBUG version of the same test fails like the others.

451       ERI_D_Ld9.f09_g16.ICLM45BGC.yellowstone_pgi.clm-default
451 ....  ERS_D_Ld3.f09_g16_gl5.IG1850CRUCLM50BGCCROP.yellowstone_intel.clm-clm50KitchenSink
451       ERI_Ld9.f09_g16.I1850CRUCLM45BGC.yellowstone_pgi.clm-drydepnomegan
451       ERI_Ld9.f09_g16.ICLM45BGC.yellowstone_intel.clm-cn_conly   NOT debug
451       ERI_D_Ld9.f09_g16.ICLM45BGC.yellowstone_intel.clm-cn_conly
451 ..... ERI_D_Ld9.f09_g16.ICLM45BGC.yellowstone_intel.clm-default
451 ..... ERP_D_Ld5.hcru_hcru.ICRUCLM45BGC.yellowstone_pgi pe_loc in MCT...
451 ..... ERI_Ld9.f09_g16.ICLM45BGC.yellowstone_pgi.clm-drydepnomegan

**Comment by ekluzek** [comment]
A test with the gnu compiler also fails, but the output isn't as good...

This is for: ERS_D_Ld3.f09_g16_gl5.IG1850CRUCLM50BGCCROP.yellowstone_gnu.clm-clm50KitchenSink

 600:(seq_domain_areafactinit) : min/max mdl2drv    1.00000000000000       1.00000000000000    areafact_a_ATM
 600:(seq_domain_areafactinit) : min/max drv2mdl    1.00000000000000       1.00000000000000    areafact_a_ATM
   2:MCT::m_AttrVect::lsize_: attribute array length mismatch error, stat =3
   2:002.MCT(MPEU)::die.: from MCT::m_AttrVect::lsize_()
 589:MCT::m_AttrVect::lsize_: attribute array length mismatch error, stat =1
 589:24D.MCT(MPEU)::die.: from MCT::m_AttrVect::lsize_()
 595:MCT::m_AttrVect::lsize_: attribute array length mismatch error, stat =1
 595:253.MCT(MPEU)::die.: from MCT::m_AttrVect::lsize_()
 457:MCT::m_AttrVect::lsize_: attribute array length mismatch error, stat =1690653987
 417:MCT::m_AttrVect::lsize_: attribute array length mismatch error, stat =1
 417:1A1.MCT(MPEU)::die.: from MCT::m_AttrVect::lsize_()
 419:MCT::m_AttrVect::lsize_: attribute array length mismatch error, stat =1
 419:1A3.MCT(MPEU)::die.: from MCT::m_AttrVect::lsize_()
 471:MCT::m_AttrVect::lsize_: attribute array length mismatch error, stat =1
 471:1D7.MCT(MPEU)::die.: from MCT::m_AttrVect::lsize_()
   2:Abort(2) on node 2 (rank 2 in comm 1140850688): application called MPI_Abort(MPI_COMM_WORLD, 2) - process 2
   2:INFO: 0031-306  pm_atexit: pm_exit_value is 1.
 479:MCT::m_AttrVect::lsize_: attribute array length mismatch error, stat =194111359
 479:1DF.MCT(MPEU)::die.: from MCT::m_AttrVect::lsize_()
 503:MCT::m_AttrVect::lsize_: attribute array length mismatch error, stat =1275069467

**Comment by billsacks** [comment]
@mvertens says that @jedwards4b says that this is fixed in the esmci. From a brief look at the code diffs around the stack trace, I'm wondering if the fix is:

```
[roo2:~/cime]$ git diff -w cime4.5.10...esmci_master -- driver_cpl/driver/seq_rest_mod.F90
diff --git a/driver_cpl/driver/seq_rest_mod.F90 b/driver_cpl/driver/seq_rest_mod.F90
index e8c5555..fa26e06 100644
--- a/driver_cpl/driver/seq_rest_mod.F90
+++ b/driver_cpl/driver/seq_rest_mod.F90
@@ -183,7 +183,7 @@ subroutine seq_rest_read(rest_file, infodata, &
         ocn_present=ocn_present,        &
         glc_present=glc_present,        &
         wav_present=wav_present,        &
-        esp_present=wav_present,        &
+        esp_present=esp_present,        &
         atm_prognostic=atm_prognostic,      &
         lnd_prognostic=lnd_prognostic,      &
         ice_prognostic=ice_prognostic,      &
```

**Comment by billsacks** [comment]
@jedwards4b and @mvertens - can you comment on whether you expect the above patch to fix this problem?

**Comment by jedwards4b** [comment]
That bug is fixed both in cesm-development and esmci - what cime are you
testing?

On Thu, Jun 2, 2016 at 5:15 PM, Bill Sacks notifications@github.com wrote:

> @jedwards4b https://github.com/jedwards4b and @mvertens
> https://github.com/mvertens - can you comment on whether you expect the
> above patch to fix this problem?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/CESM-Development/cime/issues/451#issuecomment-223450238,
> or mute the thread
> https://github.com/notifications/unsubscribe/AF16GNi6dj9y0kQqmNBQieYMrtL4Bdwhks5qH2P7gaJpZM4IsvZI
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by billsacks** [comment]
@ekluzek mentioned 5.6.0 - I assume he meant 4.6.0, which was the version in cesm1_5_beta06.

**Comment by fischer-ncar** [comment]
I think he's testing cime4.6.0 which I tagged incorrectly, it should have been cime4.5.10 in beta06.  I retagged cime4.6.0 as cime4.5.10.  We're at cime4.5.14 now, so this was probably fixed.

**Comment by ekluzek** [comment]
Fixing the issue that Bill pointed out for the first test -- it now works! So I'm verifying it fixes the others. And I'll also test with cime4.5.14 and see if that works for us.
