### ISSUE TITLE
ESMF test fails with ESP error for ERP tests

### ISSUE THREAD

**Issue by fischer-ncar** [CESM-Development/cime#453]
This is related to issue #439, but wasn't fixed with #443.  @ekluzek ran into this error while doing
testing with cime4.5.14.  A test that's failing is 

ERP_E_Ld5.f19_g16.I1850CRUCLM45CN.yellowstone_intel.clm-default

Getting the following error during the restart.
 30:MCT::m_AttrVect::indexRA_:: ERROR--attribute not found: "aream" Traceback:  
 30:aa aream->MCT::m_AttrVect::indexRA_

This test will pass if it's an ERS tests.  The difference between the ERS and ERP tests is the ERP
test changes the processor layout for the restart.  The latest cesm alpha tag reproduces this error.
https://svn-ccsm-models.cgd.ucar.edu/cesm1/alphas/tags/cesm1_5_alpha07c/

Chris

**Comment by billsacks** [comment]
Should this be closed as a wont-fix because we're ditching esmf?

**Comment by jedwards4b** [comment]
Won't fix, esmf coupler no longer supported.
