### ISSUE TITLE
hobart_intel doesn't build if you have compiler/nag module loaded

### ISSUE THREAD

**Issue by mnlevy1981** [CESM-Development/cime#456]
I load the `compiler/nag` module every time I log on to hobart (via my `.bashrc` file). If I run the following:

```
$ cd $CESMDIR/cime/scripts
$ ./create_newcase -compset [doesn't matter] -res [doesn't matter] -mach hobart -compiler intel -case CASEDIR
$ cd CASEDIR
$ ./case_setup
$ ./case_build
```

I get an error in the PIO build about having trouble with the MPI and netCDF libraries. However, a well-placed `module purge`:

```
$ cd $CESMDIR/cime/scripts
$ ./create_newcase -compset [doesn't matter] -res [doesn't matter] -mach hobart -compiler intel -case CASEDIR2
$ cd CASEDIR2
$ ./case_setup
$ module purge
$ ./case_build
```

builds successfully. I haven't dug into `scripts` to try to track this down, so I don't have a fix to suggest. This appears to be the case in both `cime4.5.10` (cesm1_5_beta06) and `cime4.5.16` (latest tag to date) -- I've tentatively added this to the cesm2 milestone, thinking it would be good to see if the problem still exists after the python refactor (I assume the Machines files will all look different?) before trying too hard to find a solution.

**Comment by jedwards4b** [comment]
Fixed in cime5 (verified).
