### ISSUE TITLE
Don't allow -generate and -compare to point to the same thing in create_test

### ISSUE THREAD

**Issue by ekluzek** [CESM-Development/cime#458]
In what will be clm4_5_8_r182 using a branch of cime off of cime4.5.14, I was able to have both the -generate and -compare point to clm4_5_8_r181, which then screwed up some of my baseline directories for clm4_5_8_r181. create_test should check to make sure the two aren't identical and if they are die with an error.

**Comment by ekluzek** [comment]
It would also be good if it would check that the -compare directory exists, and that the -generate directory does NOT exist.

**Comment by jedwards4b** [comment]
Fixed in cime5
