### ISSUE TITLE
Bug in regular expression match in xmlchange

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#460]
Helping Cecilia Bitz port cesm1_5_beta06 to the U Washington machine, perl (5.16?) complained about the regular expression match on line 146 of xmlchange:

```
       if ( $varval =~ /^(\w+)=(.*+)$/ ){
```

Specifically, it doesn't like '(.*+)'. Should this just be '(.+)' ???

**Comment by billsacks** [comment]
cc @fischer-ncar

**Comment by fischer-ncar** [comment]
Hobart uses perl 5.16.3, and there hasn't been any perl script issues.

**Comment by billsacks** [comment]
Presumably no longer relevant with the python port
