### ISSUE TITLE
compare_namelist.pl fails to find differences and mislabels differences that it does find

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#468]
I ran a test suite comparing https://svn-ccsm-models.cgd.ucar.edu/clm2/branch_tags/mountain_glaciers_old_behavior_tags/mountain_glaciers_old_behavior_n11_clm4_5_9_r184 (soon to be clm4_5_9_r185) with clm4_5_9_r184. These clm tags use tag clm4_5_8_r180_cime4.5.14, which is identical to the head of cime in terms of compare_namelist.pl.

I expected namelist differences for all clm45 and clm50 cases. Indeed, that seems to be the case when spot checking a few by hand. But the namelist comparison test is listed as pass for most tests.

It picks up differences for a handful of tests, where there is just one difference, like this:

```
[yslogin1:/glade/p/cesmdata/cseg/ccsm_baselines]$ test=ERS_D_Ld3.f09_g16_gl5.IG1850CRUCLM50BGCCROP.yellowstone_intel.clm-clm50KitchenSink
[yslogin1:/glade/p/cesmdata/cseg/ccsm_baselines]$ diff -u clm4_5_9_r184/$test/CaseDocs/lnd_in mountain_glaciers_old_behavior_n11_clm4_5_9_r184/$test/CaseDocs/lnd_in
--- clm4_5_9_r184/ERS_D_Ld3.f09_g16_gl5.IG1850CRUCLM50BGCCROP.yellowstone_intel.clm-clm50KitchenSink/CaseDocs/lnd_in    2016-07-02 19:52:37.705217000 -0600
+++ mountain_glaciers_old_behavior_n11_clm4_5_9_r184/ERS_D_Ld3.f09_g16_gl5.IG1850CRUCLM50BGCCROP.yellowstone_intel.clm-clm50KitchenSink/CaseDocs/lnd_in 2016-07-07 01:51:59.551402000 -0600
@@ -148,6 +148,7 @@
 /
 &clm_glacier_behavior
  glacier_region_behavior = 'single_at_atm_topo','virtual','multiple'
+ glacier_region_melt_behavior = 'remains_in_place','replaced_by_ice','replaced_by_ice'
 /
 &ch4par_in
  fin_use_fsat = .false.
```

But misses differences for the majority of tests, where there are two consecutive differences, like this:

```
[yslogin1:/glade/p/cesmdata/cseg/ccsm_baselines]$ test=ERP_D_Ld5.f19_g16.ICRUCLM50BGC.yellowstone_intel.clm-default
[yslogin1:/glade/p/cesmdata/cseg/ccsm_baselines]$ diff -u clm4_5_9_r184/$test/CaseDocs/lnd_in mountain_glaciers_old_behavior_n11_clm4_5_9_r184/$test/CaseDocs/lnd_in
--- clm4_5_9_r184/ERP_D_Ld5.f19_g16.ICRUCLM50BGC.yellowstone_intel.clm-default/CaseDocs/lnd_in  2016-07-02 19:53:22.070625000 -0600
+++ mountain_glaciers_old_behavior_n11_clm4_5_9_r184/ERP_D_Ld5.f19_g16.ICRUCLM50BGC.yellowstone_intel.clm-default/CaseDocs/lnd_in   2016-07-07 01:51:50.223256000 -0600
@@ -141,6 +141,8 @@
  ncrit = 1.d-9
 /
 &clm_glacier_behavior
+ glacier_region_behavior = 'single_at_atm_topo','virtual','multiple'
+ glacier_region_melt_behavior = 'remains_in_place','replaced_by_ice','replaced_by_ice'
 /
 &ch4par_in
  fin_use_fsat = .false.
```

Furthermore, for the tests where it picks up a difference, the difference listed in TestStatus.log is wrong:

FAIL namelist compare:  lnd_in differs
   NEW:        &clm_humanindex_inparm
   BASELINE: &cnmresp_inparm
   NEW:        &cnmresp_inparm
   BASELINE: &photosyns_inparm
   NEW:        &cnfire_inparm
   BASELINE: &lifire_inparm
   NEW:        &clm_canopy_inparm
   BASELINE:

**Comment by billsacks** [comment]
cc @jedwards4b @mnlevy1981 . I'm not sure if this is something that is newly-broken by @mnlevy1981 's recent changes, or something that would have worked incorrectly even before those changes. (Although I feel like the difference listed in TestStatus.log has nearly always been wrong, so suspect that at least that part pre-dates @mnlevy1981 's changes.)

**Comment by jedwards4b** [comment]
compare_namelists.pl is scheduled to be replaced by a python version in the
esmci code - can you update this issue in the context of that utility?

On Thu, Jul 7, 2016 at 7:02 AM, Bill Sacks notifications@github.com wrote:

> cc @jedwards4b https://github.com/jedwards4b @mnlevy1981
> https://github.com/mnlevy1981 . I'm not sure if this is something that
> is newly-broken by @mnlevy1981 https://github.com/mnlevy1981 's recent
> changes, or something that would have worked incorrectly even before those
> changes. (Although I feel like the difference listed in TestStatus.log has
> nearly always been wrong, so suspect that at least that part pre-dates
> @mnlevy1981 https://github.com/mnlevy1981 's changes.)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/CESM-Development/cime/issues/468#issuecomment-231070757,
> or mute the thread
> https://github.com/notifications/unsubscribe/AF16GFSnvJ29kh43SYwEAumnTAmMbEm3ks5qTPjggaJpZM4JHDYX
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by billsacks** [comment]
Moving this to esmci: https://github.com/ESMCI/cime/issues/241
