### ISSUE TITLE
Set BARRIER_N/OPTION for datm_CLM...

### ISSUE THREAD

**Issue by ekluzek** [CESM-Development/cime#470]
Set BARRIER_N/OPTION in the driver namelist

March 7, 2016 

Where should BARRIER_N go?

There were opinions for both CLM's config_compsets.xml (which does have some other similar xml variable settings) and for the driver's config_component.xml. We lean slightly towards driver's config_component.xml.

Ideally this would apply to any compsets that are datm with non-dlnd – which is part of the argument for having this in the driver rather than clm. However, "not" is hard to do in the xml, so for now match clm + datm.

**Comment by ekluzek** [comment]
When this is done the setting of these in CLM's config_component.xml can be removed.

**Comment by mvertens** [comment]
In the clm branch that is needed for compatibility with CIME5 - this must
be moved to config_compsets.xml in order to get anything to work.

See
https://svn-ccsm-models.cgd.ucar.edu/clm2/branches/clm4_5_8_r174_esmciport/components/clm

The only changes are in cime_config.

**Comment by ekluzek** [comment]
This is already done.
