### ISSUE TITLE
Wrong pio_iotype being set

### ISSUE THREAD

**Issue by fischer-ncar** [CESM-Development/cime#475]
PIO_TYPENAME=pnetcdf in env_run.xml isn't being carried over to the model run.  The pio_iotype in the cpl.log shows it's being set to 6, serial netcdf, instead of 5 for pnetcdf.  This started happening with cesm1_5_alpha07d, with the cime5.4.16 tag, pull request #454.  This bug is also in cesm2.
@Katetc @mvertens @ekluzek @jedwards4b

**Comment by jedwards4b** [comment]
Fixed in cime5.
