### ISSUE TITLE
DIN_LOC_ROOT_CLMFORC on cheyenne needs to change

### ISSUE THREAD

**Issue by ekluzek** [CESM-Development/cime#484]
in config_machines.xml for CESM for Cheyenne the following needs to change..

    <DIN_LOC_ROOT_CLMFORC>$ENV{CESMDATAROOT}/lmwg</DIN_LOC_ROOT_CLMFORC>

to

 <DIN_LOC_ROOT_CLMFORC>$ENV{CESMROOT}/lmwg</DIN_LOC_ROOT_CLMFORC>

**Comment by jedwards4b** [comment]
Why don't you just make a link in the filesystem?

**Comment by jedwards4b** [comment]
I went ahead and made this link, it should not require a change in cime.

**Comment by billsacks** [comment]
Should this be closed? And is it a duplicate of https://github.com/ESMCI/cime/issues/1064 ?

**Comment by ekluzek** [comment]
The softlink fixes this issue.
