### ISSUE TITLE
Wallclock max of 2:00 was dropped in batch refactor

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#49]
Before the batch refactor, the *.test scripts on yellowstone had a max wallclock time of 2:00. This was useful, since it resulted in less queue wait time. (Shorter wallclock time is always better in that respect, but on yellowstone there is an additional (unadvertised, I think) factor, which is that a certain number of slots are reserved for jobs of duration 2:00 or less.)

Would there be a way to bring back this behavior?

**Comment by billsacks** [comment]
For now I'm working around this by putting the following diff in my sandbox before beginning testing. This is NOT a solution to the problem; I'm just documenting my workaround:

```
Index: machines/config_machines.xml
===================================================================
--- machines/config_machines.xml    (revision 5151)
+++ machines/config_machines.xml    (working copy)
@@ -1077,8 +1077,8 @@
         <walltimes>
           <walltime default="true">2:00</walltime>
           <walltime ccsm_estcost="-1">2:00</walltime>
-          <walltime ccsm_estcost="0">4:00</walltime>
-          <walltime ccsm_estcost="1">8:00</walltime>
+          <walltime ccsm_estcost="0">2:00</walltime>
+          <walltime ccsm_estcost="1">2:00</walltime>
         </walltimes>
       </batch_system>
       <mpirun mpilib="mpi-serial">
```

**Comment by quantheory** [comment]
In the CAM test driver, for a couple of machines, we have queues and their times hard-coded for certain machines. So for instance, if you set `CAM_BATCHQ=small` on yellowstone, it will shorten the wall clock limit to 2:00 automatically. It might be worth adding something like that to config_batch, just for the convenience of testers if nothing else.

**Comment by billsacks** [comment]
@quantheory : While that seems like a useful feature, we do not generally want to use the small queue for testing: We generally get quick turnaround with regular (as long as the wallclock limit is 2:00 or less), and small results in higher charges.

**Comment by billsacks** [comment]
Until this can be fixed in a more robust way: Would it be possible to change the yellowstone entries so that we just always get a 2:00 wall-clock time? I think that will significantly improve the turnaround time for test suites.

**Comment by billsacks** [comment]
cc'ing @bandre-ucar @ekluzek @mvertens

**Comment by bandre-ucar** [comment]
This drastically limits how quickly tests get through the queue. Can we bump the priority up to critical?

**Comment by mvertens** [comment]
This is in transition and will be addressed within the cime3.0.x series.

**Comment by apcraig** [comment]
I am testing cesm1_5_beta04 and am finding that all jobs on yellowstone have a walltime of 12 hours, even small X configurations.   this seems to be related to the cost estimate which is no longer working properly in the system as far as i can tell.  That cost estimate is used by the batch xml to set the wall time.  I have been manually reducing the wall times in env_batch.xml, but this will have an impact on automated testing as well as testing as part of development.  Don't know how long things have been that way.

**Comment by billsacks** [comment]
@apcraig : @jedwards4b introduced a -walltime argument to create_test, so that you can at least set the max wallclock time for tests. That said, I'd still like to see a change so that the default is 2:00 for tests, since I often forget to give the -walltime argument.

**Comment by jedwards4b** [comment]
It's coming.

On Thu, Jan 28, 2016 at 2:15 PM, Bill Sacks notifications@github.com
wrote:

> @apcraig https://github.com/apcraig : @jedwards4b
> https://github.com/jedwards4b introduced a -walltime argument to
> create_test, so that you can at least set the max wallclock time for tests.
> That said, I'd still like to see a change so that the default is 2:00 for
> tests, since I often forget to give the -walltime argument.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/49#issuecomment-176422309
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jedwards4b** [comment]
Default time for run script is maximum wallclock for the given queue.   Defaults for tests are tunable.  In both cases user can now adjust wallclock time at runtime
