### ISSUE TITLE
Q compset DOCN streams not zeroing land mask with SE dycore

### ISSUE THREAD

**Issue by zarzycki** [CESM-Development/cime#497]
https://github.com/CESM-Development/cime/tags/cime5.4.0-alpha.03
https://github.com/CESM-Development/cime_config/tags/cime_config0.1.0.alpha.02/
https://svn-ccsm-models.cgd.ucar.edu/cam1/branches/physgrid/components/cam

-------------------

./create_newcase --case ~/work/QPC6/QPC6.ne30 --compset QPC6 --res ne30_ne30_mg16 --project XXXXXXXXX --run-unsupported

This configuration works as expected if one of the analytic SST profiles is chosen for aquaplanet simulations.

However, if I try to read a data stream... add user_docn.streams.txt.aquapfile (glade example at /glade/p/work/zarzycki/initial/SST/user_docn.streams.txt.aquapfile) and set DOCN_MODE to "sst_aquapfile"
... CAM happily runs and loads the correct SST stream file but does NOT zero out the land mask. I have reproduced this with both a user-generated variable-resolution SE grid/domain file and one of the default grids/domain files in the repo (ne30)

Jim Benedict tried this user_docn.streams file with FV and it behaved correctly, so it appears this problem is only with A) the SE core and then B) only when a data stream file is being read for DOCN. Perhaps an issue with the unstructured grid and zeroing out the mask?

**Comment by jedwards4b** [comment]
@zarzycki Please post this issue in the esmci github at https://github.com/ESMCI/

**Comment by jedwards4b** [comment]
Moved to esmci #1960
