### ISSUE TITLE
yellowstone_pgi threading runs take a LONG time starting with cime1.1.0

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#51]
I noticed that CLM runs on yellowstone with pgi take a much longer time starting with cime1.1.0. I'm not sure why this is. It doesn't seem to be the case for intel. But it seems to be the case for pgi 15.1 as well as pgi 14.7.

Steps to reproduce:

(1) Check out https://svn-ccsm-models.cgd.ucar.edu/clm2/trunk_tags/clm4_5_1_r113

(2) Switch cime to cime1.0.8

(3) Run SMS_P15x2.f10_f10.IHISTCLM45BGC.yellowstone_pgi.clm-monthly

(4) Notice dt in the cpl log file: about 2 seconds

(5) Switch to cime1.1.0; also merge in (cherry-pick / rebase) changes made in cime1.1.8 relative to cime1.1.7 (otherwise the requested number of PEs is wrong).

(6) Create and run a new version of SMS_P15x2.f10_f10.IHISTCLM45BGC.yellowstone_pgi.clm-monthly

(7) Notice dt in the cpl log file: close to 30 seconds

**Comment by billsacks** [comment]
cc @mvertens @jedwards4b @ekluzek @bandre-ucar

**Comment by billsacks** [comment]
The same slow-down appears if using cime1.1.10. My instructions were just meant to demonstrate that the problem appeared in cime1.1.0. I haven't tried cime versions more recent than 1.1.10.

**Comment by jedwards4b** [comment]
Can you pinpoint the source of the slowdown in the timing files?

**Comment by billsacks** [comment]
Good point, @jedwards4b . From what I can see, the slowdown seems to be in pieces that require communication - including i/o. So datm sees a particularly marked slow-down, with datm_scatter being a particularly large culprit: this takes about 1000 times longer now. I have put old and new timing files here: /glade/scratch/sacks/timing_files

**Comment by mnlevy1981** [comment]
We have a similar slowdown with POP, and it's even noticeable before POP starts running. This is timing from the first few days of a cesm1_4_beta05 / C compset intel run:

```
 tStamp_write: model date =    10102       0 wall clock = 2015-07-15 12:04:14 dt =     0.22
 tStamp_write: model date =    10103       0 wall clock = 2015-07-15 12:04:24 dt =     9.80
 tStamp_write: model date =    10104       0 wall clock = 2015-07-15 12:04:32 dt =     7.87
 tStamp_write: model date =    10105       0 wall clock = 2015-07-15 12:04:40 dt =     8.09
 tStamp_write: model date =    10106       0 wall clock = 2015-07-15 12:04:48 dt =     7.92
```

and here's the same using pgi

```
 tStamp_write: model date =    10102       0 wall clock = 2015-07-15 12:09:48 dt =     8.73
 tStamp_write: model date =    10103       0 wall clock = 2015-07-15 12:14:17 dt =   269.16
 tStamp_write: model date =    10104       0 wall clock = 2015-07-15 12:18:10 dt =   233.14
 tStamp_write: model date =    10105       0 wall clock = 2015-07-15 12:21:48 dt =   217.92
 tStamp_write: model date =    10106       0 wall clock = 2015-07-15 12:25:22 dt =   213.42
```

I haven't dug deeper into the timing logs to see where the slowdown occurs, but I wanted to add another data point to this issue. The 40x increase in time on day 1 [logged at 010102-00000] is especially interesting because POP doesn't start running until day 2... so that's entirely in the data models and coupler (I assume initialization isn't counted in the first day's timing?).

edit: I stripped out the avg dt values because they aren't very useful...

**Comment by jedwards4b** [comment]
I tried this with the alpha06 sandbox:

SMS_P15x2.f10_f10.IHISTCLM45BGC.yellowstone_pgi.clm-monthly

 tStamp_write: model date = 18500102       0 wall clock = 2015-07-15
12:34:58 avg dt =     4.63 dt =     4.63

 tStamp_write: model date = 18500103       0 wall clock = 2015-07-15
12:35:00 avg dt =     3.20 dt =     1.78

 tStamp_write: model date = 18500104       0 wall clock = 2015-07-15
12:35:02 avg dt =     2.73 dt =     1.78

 tStamp_write: model date = 18500105       0 wall clock = 2015-07-15
12:35:03 avg dt =     2.49 dt =     1.78

 tStamp_write: model date = 18500106       0 wall clock = 2015-07-15
12:35:05 avg dt =     2.41 dt =     2.08

 Then I updated clm to
https://svn-ccsm-models.cgd.ucar.edu/clm2/trunk_tags/clm4_5_1_r113/components/clm

and got the same result...

On Wed, Jul 15, 2015 at 12:50 PM, Michael Levy notifications@github.com
wrote:

> We have a similar slowdown with POP, and it's even noticeable before POP
> starts running. This is timing from the first few days of a cesm1_4_beta05
> / C compset intel run:
> 
>  tStamp_write: model date =    10102       0 wall clock = 2015-07-15 12:04:14 avg dt =     0.22 dt =     0.22
>  tStamp_write: model date =    10103       0 wall clock = 2015-07-15 12:04:24 avg dt =     5.01 dt =     9.80
>  tStamp_write: model date =    10104       0 wall clock = 2015-07-15 12:04:32 avg dt =     5.96 dt =     7.87
>  tStamp_write: model date =    10105       0 wall clock = 2015-07-15 12:04:40 avg dt =     6.50 dt =     8.09
>  tStamp_write: model date =    10106       0 wall clock = 2015-07-15 12:04:48 avg dt =     6.78 dt =     7.92
> 
> and here's the same using pgi
> 
>  tStamp_write: model date =    10102       0 wall clock = 2015-07-15 12:09:48 avg dt =     8.73 dt =     8.73
>  tStamp_write: model date =    10103       0 wall clock = 2015-07-15 12:14:17 avg dt =   138.94 dt =   269.16
>  tStamp_write: model date =    10104       0 wall clock = 2015-07-15 12:18:10 avg dt =   170.34 dt =   233.14
>  tStamp_write: model date =    10105       0 wall clock = 2015-07-15 12:21:48 avg dt =   182.24 dt =   217.92
>  tStamp_write: model date =    10106       0 wall clock = 2015-07-15 12:25:22 avg dt =   188.47 dt =   213.42
> 
> I haven't dug deeper into the timing logs to see where the slowdown
> occurs, but I wanted to add another data point to this issue. The 40x
> increase in time on day 1 [logged at 010102-00000] is especially
> interesting because POP doesn't start running until day 2... so that's
> entirely in the data models and coupler (I assume initialization isn't
> counted in the first day's timing?).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/51#issuecomment-121710541
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jedwards4b** [comment]
Also not seeing the pop performance issue in the alpha06 sandbox...

 tStamp_write: model date =    10102       0 wall clock = 2015-07-15
13:06:03 avg dt =     0.24 dt =     0.24

 tStamp_write: model date =    10103       0 wall clock = 2015-07-15
13:07:11 avg dt =    33.88 dt =    67.52

 tStamp_write: model date =    10104       0 wall clock = 2015-07-15
13:08:16 avg dt =    44.39 dt =    65.42

 tStamp_write: model date =    10105       0 wall clock = 2015-07-15
13:09:21 avg dt =    49.67 dt =    65.51

 tStamp_write: model date =    10106       0 wall clock = 2015-07-15
13:10:27 avg dt =    52.82 dt =    65.43

 tStamp_write: model date =    10107       0 wall clock = 2015-07-15
13:11:44 avg dt =    56.93 dt =    77.44

 tStamp_write: model date =    10108       0 wall clock = 2015-07-15
13:12:50 avg dt =    58.18 dt =    65.66

 tStamp_write: model date =    10109       0 wall clock = 2015-07-15
13:13:55 avg dt =    59.08 dt =    65.43

 tStamp_write: model date =    10110       0 wall clock = 2015-07-15
13:15:01 avg dt =    59.78 dt =    65.38

 tStamp_write: model date =    10111       0 wall clock = 2015-07-15
13:16:06 avg dt =    60.32 dt =    65.18

 tStamp_write: model date =    10112       0 wall clock = 2015-07-15
13:17:13 avg dt =    60.88 dt =    66.51

On Wed, Jul 15, 2015 at 12:52 PM, Jim Edwards jedwards@ucar.edu wrote:

> I tried this with the alpha06 sandbox:
> 
> SMS_P15x2.f10_f10.IHISTCLM45BGC.yellowstone_pgi.clm-monthly
> 
>  tStamp_write: model date = 18500102       0 wall clock = 2015-07-15
> 12:34:58 avg dt =     4.63 dt =     4.63
> 
>  tStamp_write: model date = 18500103       0 wall clock = 2015-07-15
> 12:35:00 avg dt =     3.20 dt =     1.78
> 
>  tStamp_write: model date = 18500104       0 wall clock = 2015-07-15
> 12:35:02 avg dt =     2.73 dt =     1.78
> 
>  tStamp_write: model date = 18500105       0 wall clock = 2015-07-15
> 12:35:03 avg dt =     2.49 dt =     1.78
> 
>  tStamp_write: model date = 18500106       0 wall clock = 2015-07-15
> 12:35:05 avg dt =     2.41 dt =     2.08
> 
>  Then I updated clm to
> https://svn-ccsm-models.cgd.ucar.edu/clm2/trunk_tags/clm4_5_1_r113/components/clm
> 
> and got the same result...
> 
> On Wed, Jul 15, 2015 at 12:50 PM, Michael Levy notifications@github.com
> wrote:
> 
> > We have a similar slowdown with POP, and it's even noticeable before POP
> > starts running. This is timing from the first few days of a cesm1_4_beta05
> > / C compset intel run:
> > 
> >  tStamp_write: model date =    10102       0 wall clock = 2015-07-15 12:04:14 avg dt =     0.22 dt =     0.22
> >  tStamp_write: model date =    10103       0 wall clock = 2015-07-15 12:04:24 avg dt =     5.01 dt =     9.80
> >  tStamp_write: model date =    10104       0 wall clock = 2015-07-15 12:04:32 avg dt =     5.96 dt =     7.87
> >  tStamp_write: model date =    10105       0 wall clock = 2015-07-15 12:04:40 avg dt =     6.50 dt =     8.09
> >  tStamp_write: model date =    10106       0 wall clock = 2015-07-15 12:04:48 avg dt =     6.78 dt =     7.92
> > 
> > and here's the same using pgi
> > 
> >  tStamp_write: model date =    10102       0 wall clock = 2015-07-15 12:09:48 avg dt =     8.73 dt =     8.73
> >  tStamp_write: model date =    10103       0 wall clock = 2015-07-15 12:14:17 avg dt =   138.94 dt =   269.16
> >  tStamp_write: model date =    10104       0 wall clock = 2015-07-15 12:18:10 avg dt =   170.34 dt =   233.14
> >  tStamp_write: model date =    10105       0 wall clock = 2015-07-15 12:21:48 avg dt =   182.24 dt =   217.92
> >  tStamp_write: model date =    10106       0 wall clock = 2015-07-15 12:25:22 avg dt =   188.47 dt =   213.42
> > 
> > I haven't dug deeper into the timing logs to see where the slowdown
> > occurs, but I wanted to add another data point to this issue. The 40x
> > increase in time on day 1 [logged at 010102-00000] is especially
> > interesting because POP doesn't start running until day 2... so that's
> > entirely in the data models and coupler (I assume initialization isn't
> > counted in the first day's timing?).
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/CESM-Development/cime/issues/51#issuecomment-121710541
> > .
> 
> ## 
> 
> Jim Edwards
> 
> CESM Software Engineer
> National Center for Atmospheric Research
> Boulder, CO

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by billsacks** [comment]
Well, there's something weird going on here. When I update to the latest cime, either in a CLM checkout or using the alpha06 branch, I get wall clock times of about 16 sec, not 2 sec. Granted, this is still better than the 30 sec that I saw before....

Steps to reproduce:

(1) checkout https://svn-ccsm-models.cgd.ucar.edu/cesm1/alphas/branches/cesm1_4_alpha06 (r71733)

(2) blow away cime, do a git clone, use latest master (18340e243dc54b8eb773348b3b9f3829b3abfcd7)

(3) cd components/clm; svn switch https://svn-ccsm-models.cgd.ucar.edu/clm2/trunk_tags/clm4_5_1_r113/components/clm

(4) create SMS_P15x2.f10_f10.IHISTCLM45BGC.yellowstone_pgi.clm-monthly; build & run it

(5) look in logs/cpl.log.*:

 tStamp_write: model date = 18500102       0 wall clock = 2015-07-15 13:58:01 avg dt =    19.22 dt =    19.22
 tStamp_write: model date = 18500103       0 wall clock = 2015-07-15 13:58:17 avg dt =    17.58 dt =    15.95
 tStamp_write: model date = 18500104       0 wall clock = 2015-07-15 13:58:33 avg dt =    17.04 dt =    15.95
 tStamp_write: model date = 18500105       0 wall clock = 2015-07-15 13:58:48 avg dt =    16.62 dt =    15.37

**Comment by mnlevy1981** [comment]
I ran cesm1_4_beta04 with pgi, and the numbers are about 40% longer per timestep than what [I posted from Intel](https://github.com/CESM-Development/cime/issues/51#issuecomment-121710541) in cesm1_4_beta05:

```
 tStamp_write: model date =    10102       0 wall clock = 2015-07-15 16:38:41 dt =     0.77
 tStamp_write: model date =    10103       0 wall clock = 2015-07-15 16:38:55 dt =    14.12
 tStamp_write: model date =    10104       0 wall clock = 2015-07-15 16:39:05 dt =    10.32
 tStamp_write: model date =    10105       0 wall clock = 2015-07-15 16:39:15 dt =    10.40
 tStamp_write: model date =    10106       0 wall clock = 2015-07-15 16:39:25 dt =    10.11
```

Running out of the 1_4_alpha06 tag (in @jedwards4b /work directory) is still significantly slower for me (and takes 3x as long as [Jim's example](https://github.com/CESM-Development/cime/issues/51#issuecomment-121719216) out of the same sandbox!)

```
 tStamp_write: model date =    10102       0 wall clock = 2015-07-15 17:03:03 dt =     2.90
 tStamp_write: model date =    10103       0 wall clock = 2015-07-15 17:06:02 dt =   178.21
 tStamp_write: model date =    10104       0 wall clock = 2015-07-15 17:08:32 dt =   150.11
 tStamp_write: model date =    10105       0 wall clock = 2015-07-15 17:10:53 dt =   140.98
 tStamp_write: model date =    10106       0 wall clock = 2015-07-15 17:13:10 dt =   137.48
```

Looking at the `Macros` file, the only difference in compiler flags is that we dropped `-Mlist` but adding it back in doesn't change the timings at all.

It's worth noting I do get the following module error in the alpha06 tag, though I don't think it came up in beta05:

```
Lmod Error: Can not load: "netcdf-mpi/4.3.3.1" module because these modules are loaded:
  netcdf


The following have been reloaded with a version change:
  1) pnetcdf/1.4.1 => pnetcdf/1.6.0
```

**Comment by billsacks** [comment]
I'm not seeing that Lmod error - unless I'm not looking in the right place.

**Comment by billsacks** [comment]
To try to see if this is a user environment problem: I just tried blowing away my .profile and using Jim's .bash_profile. This was very disorienting -- and still led to long run times with the SMS_P15x2.f10_f10.IHISTCLM45BGC.yellowstone_pgi.clm-monthly case (dt around 16 sec.).

**Comment by sholly** [comment]
I did 2 of these tests in cesm1_5_alpha01a, with these results: 

SMS_P15x2.f10_f10.IHISTCLM45BGC.yellowstone_pgi.clm-monthly:
tStamp_write: model date = 18500102       0 wall clock = 2015-09-18 12:00:07 avg dt =     4.99 dt =     4.99
 tStamp_write: model date = 18500103       0 wall clock = 2015-09-18 12:00:08 avg dt =     3.40 dt =     1.81
 tStamp_write: model date = 18500104       0 wall clock = 2015-09-18 12:00:10 avg dt =     2.87 dt =     1.80
 tStamp_write: model date = 18500105       0 wall clock = 2015-09-18 12:00:12 avg dt =     2.59 dt =     1.77
 tStamp_write: model date = 18500106       0 wall clock = 2015-09-18 12:00:14 avg dt =     2.50 dt =     2.12

SMS_P15x2.f10_f10.IHISTCLM45BGC.yellowstone_intel.clm-monthly
 tStamp_write: model date = 18500102       0 wall clock = 2015-09-18 13:44:11 avg dt =     5.76 dt =     5.76
 tStamp_write: model date = 18500103       0 wall clock = 2015-09-18 13:44:13 avg dt =     3.71 dt =     1.66
 tStamp_write: model date = 18500104       0 wall clock = 2015-09-18 13:44:14 avg dt =     3.01 dt =     1.61
 tStamp_write: model date = 18500105       0 wall clock = 2015-09-18 13:44:16 avg dt =     2.65 dt =     1.58
 tStamp_write: model date = 18500106       0 wall clock = 2015-09-18 13:44:18 avg dt =     2.50 dt =     1.89

Seeing as how the performance numbers are now similar, I believe we can close this issue...
