### ISSUE TITLE
BatchMaker queue selection tweak

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#53]
Here's a little enhancement request, as a present for @sholly when he gets back.

If I'm reading it right (and I fully admit that this is just based on reading the code rather than actually testing it), this is the current behavior of BatchMaker in `SetQueue`:
1. If there is no "default" queue, die.
2. If there is any queue that defines a jobmin and a jobmax, and the current case falls into that range, pick that queue (overwriting any default). If there are multiple matches, the last one wins.
3. Otherwise, use the default.

This is a little weird, because if you have queues with a wide jobmin/jobmax range, the last one of those will usually be picked, so the "default" doesn't usually matter in those cases, only the order of the queue elements. Also, if you are using too many pes for any of the queues, you will get the default queue rather than an error.

I think that it might be better to do something like this:
1. If there is a default queue **without** a jobmin/jobmax range, always pick it, no matter what. (I'm assuming for now that there's only going to be one default queue per machine.)
2. If there is a default queue **with** a jobmin/jobmax range, pick it if and only if the current case is in that range.
3. If there is no default queue, pick a queue with a matching jobmin/jobmax range. (If there are multiple matches, maybe it should error, but we could settle for taking the first or last match.)
4. If we still haven't found a queue, die.

For bonus points:

 0. Add a `QUEUE` variable to ~~`env_mach_specific`~~ I mean `env_mach_pes`, allowing the user to override the queue that would otherwise be selected by `BatchMaker`.

**Comment by jedwards4b** [comment]
bonus points piece is complete.  needs to be tested in python

**Comment by jedwards4b** [comment]
Fixed in python
