### ISSUE TITLE
env_mach_specific environment 

### ISSUE THREAD

**Issue by fvitt** [CESM-Development/cime#54]
I am having issues with the fortran compiler module not being loaded when cam's configure tries to build the chemistry preprocessor.  It seems that cam's configure does not inherit the environment that is specified in env_mach_specific.  The configure script is invoked by buildnml which is presumably invoked by cesm_setup.  Is the environment in env_mach_specific not set up by cesm_setup?

**Comment by jedwards4b** [comment]
It should be.  Are you using the cime trunk?  What machine?

**Comment by fvitt** [comment]
I am using trunk tag cime1.0.8 on yellowstone.
I can try the latest trunk tag.

**Comment by fvitt** [comment]
I have the same problem with cime1.1.15
The only work around I found is the load the module myself before invoking make:

```
my $cmd = "$gmake -f $makefile > $log_file 2>&1";
if (run_shell_command("module list") ){
    $cmd = "module purge; module load $fc; " . $cmd;
}
run_shell_command($cmd) or die "Failed: $cmd";
```

**Comment by jedwards4b** [comment]
Can you tell me how to reproduce this and I'll have a look?   What is the
module list output?

On Thu, Jul 16, 2015 at 9:11 AM, fvitt notifications@github.com wrote:

> I have the same problem with cime1.1.15
> The only work around I found is the load the module myself before invoking
> make:
> 
> my $cmd = "$gmake -f $makefile > $log_file 2>&1";
> if (run_shell_command("module list") ){
>     $cmd = "module purge; module load $fc; " . $cmd;
> }
> run_shell_command($cmd) or die "Failed: $cmd";
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/54#issuecomment-121986999
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by fvitt** [comment]
the module list seems to be empty
checkout cam branch:
https://svn-ccsm-models.cgd.ucar.edu/cam1/branches/chemproc_cam5_4_01

go to cime/scripts and run test:
create_test -xml_mach yellowstone -xml_compiler pgi -xml_category chemproc -testroot $TMP/chem_preproc_tests -testid chem_preproc

**Comment by jedwards4b** [comment]
@fvitt I think that this is fixed, please close if you agree.

**Comment by jedwards4b** [comment]
Closing as fixed
