### ISSUE TITLE
create_test on pleiades

### ISSUE THREAD

**Issue by fvitt** [CESM-Development/cime#57]
I get the following error message with create_test on pleiades,  This is tag cime1.1.16

Creating testroot /nobackupp8/fvitt/cime_tests
mkdir /nobackupp8/fvitt/cime_tests
Can't locate object method "getAttribute" via package "XML::LibXML::Text" at create_test line 815.

**Comment by jedwards4b** [comment]
Version of perl or of XML::LibXML is too old - is there a newer perl
installed as a module?

On Fri, Jul 17, 2015 at 10:04 AM, fvitt notifications@github.com wrote:

> I get the following error message with create_test on pleiades, This is
> tag cime1.1.16
> 
> Creating testroot /nobackupp8/fvitt/cime_tests
> mkdir /nobackupp8/fvitt/cime_tests
> Can't locate object method "getAttribute" via package "XML::LibXML::Text"
> at create_test line 815.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/57.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by fvitt** [comment]
Use of module perl/5.20.1 has fixed the problem.
Thanks.
