### ISSUE TITLE
preview_namelist -verbose option 

### ISSUE THREAD

**Issue by jedwards4b** [CESM-Development/cime#60]
This option should be passed to and used by component scripts called by preview_namelists

**Comment by mnlevy1981** [comment]
POP has been using this option to print to screen all variables changed by user_nl_pop settings - is this still the desired behavior of the flag? For example:

```
$ cat user_nl_pop 
solverchoice='ChronGear'
preconditionerchoice = 'diagonal'
dt_count=12
ldiag_bsf=.true.
vmix_choice='kpp'
```

Leads to

```
$ ./preview_namelists -verbose
[snip]
 - The following values have been set in user_nl_pop:
   * dt_count = 12 in &time_manager_nml
   * vmix_choice = 'kpp' in &vertical_mix_nml
   * solverchoice = 'ChronGear' in &solvers
   * preconditionerchoice = 'diagonal' in &solvers
   * ldiag_bsf = .true. in &bsf_diagnostic_nml
```

**Comment by jedwards4b** [comment]
Yes, we should have all components do this...

On Mon, Jul 20, 2015 at 2:17 PM, Michael Levy notifications@github.com
wrote:

> POP has been using this option to print to screen all variables changed by
> user_nl_pop settings - is this still the desired behavior of the flag? For
> example:
> 
> $ cat user_nl_pop
> solverchoice='ChronGear'
> preconditionerchoice = 'diagonal'
> dt_count=12
> ldiag_bsf=.true.
> vmix_choice='kpp'
> 
> Leads to
> 
> $ ./preview_namelists -verbose
> [snip]
> - The following values have been set in user_nl_pop:
>   - dt_count = 12 in &time_manager_nml
>   - vmix_choice = 'kpp' in &vertical_mix_nml
>   - solverchoice = 'ChronGear' in &solvers
>   - preconditionerchoice = 'diagonal' in &solvers
>   - ldiag_bsf = .true. in &bsf_diagnostic_nml
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/60#issuecomment-123017684
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by ekluzek** [comment]
The verbose option works a bit differently for CLM, but it does give more
verbose output. Changing it to look the same as how POP does it would take
some work. But, we can easily connect it so that if "-verbose" is on in
preview_namelist it will turn it on for CLM build-namelist.

_Erik Kluzek, (CGD at NCAR)_

_National Center for Atmospheric Research_

*Boulder CO, *

_(off) (303)497-1326 (fax) (303)497-1348_

_(skype) ekluzek    (cell) (303)859-0183_

_Pronouns: he/his/him_

_------------------ Home page ------------------------_
- ```
       http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*
  ```
- ```
       https://staff.ucar.edu/users/erik
  ```
  
  https://staff.ucar.edu/users/erik*

_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_

**Comment by bandre-ucar** [comment]
verbose is useful for debugging type output, that normally isn’t desired. Maybe we can create a new option like ‘-user-summary’ or something that prints this info?

**Comment by mnlevy1981** [comment]
@ekluzek What does the verbose tag do in CLM? I'm not trying to push POP's approach so much as I just want the behavior to be as uniform as possible across components.

**Comment by jedwards4b** [comment]
mostly I just noticed that adding the verbose flag to preview_namelists
does not invoke verbose for cam's build-namelist

On Mon, Jul 20, 2015 at 2:38 PM, Michael Levy notifications@github.com
wrote:

> @ekluzek https://github.com/ekluzek What does the verbose tag do in
> CLM? I'm not trying to push POP's approach so much as I just want the
> behavior to be as uniform as possible across components.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/60#issuecomment-123027695
> .

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by jedwards4b** [comment]
We have a verbose option in the python but I don't it gives the same functionality.  Do we need another option?   --user-summary ?

**Comment by billsacks** [comment]
Once this is in cime's preview_namelists, we'll open tickets for components to listen to this flag and act appropriately.

**Comment by jedwards4b** [comment]
Fixed in python.

**Comment by billsacks** [comment]
@jedwards4b - do we need to make changes to all components for this to work right? (that was implied by the comment April 27, which I think came out of the cime bug review meeting)
