### ISSUE TITLE
Possible shr_scam_getCloseLatLon issue

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#65]
This issue from [Bugzilla](http://bugs.cgd.ucar.edu/show_bug.cgi?id=1065) seems to be a low priority, but still valid. Tony's description:

> after a quick review for re-implementation in datm8, it looks like shr_scam_getCloseLatLon doesn't handle the wraparound lon properly. it also may not reset lons to [0,360] if lon values are ever less than -360.  these probably don't cause any serious problems but could be fixed quite easily too.  it also assumes a 2d regular lat lon grid. this could also easily be extended to more general grids.

**Comment by mvertens** [comment]
SCAM is really problematic. We need to look at scam before June and revisit this problem periodically.

**Comment by jedwards4b** [comment]
Moved to ESMCI issue 856
