### ISSUE TITLE
shr_orb_cosz accuracy issue

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#66]
From [Bugzilla](http://bugs.cgd.ucar.edu/show_bug.cgi?id=1288), I note an old bug that Nancy Norton filed. The proposal was to work around machine-specific issues that cause a loss of accuracy in `shr_orb_cosz`. Specifically, the expression `cos(jday*2.0_SHR_KIND_R8*pi + lon)` would be replaced by `cos((jday-floor(jday))*2.0_SHR_KIND_r8*pi + lon)`.

**Comment by mvertens** [comment]
This should go into cesm1_5_beta02.

**Comment by mvertens** [comment]
This should be merged into cime by accepting pull request #118.

**Comment by billsacks** [comment]
Re-merge #118 when we can bring in answer changes.

**Comment by jedwards4b** [comment]
Done esmci 437
