### ISSUE TITLE
INFO_DBUG/info_debug documentation

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#67]
From [Bugzilla](http://bugs.cgd.ucar.edu/show_bug.cgi?id=1182) I noticed a bug that mentioned that changing the value of this variable from 1 to 2 did not seem to produce any additional output when running the model. In fact, aside from being passed around to various places, I can't see any place where it is used at all.

Perhaps it should be removed. Even if we do want to resurrect this as a verbosity flag, we should probably rename it, since `INFO_DBUG` is kind of a silly name...

**Edit:** I got this wrong, see below.

**Comment by apcraig** [comment]
INFO_DBUG still does work and is critical for many of us that develop, are checking bit-for-bit between runs, and want to diagnose where bit-for-bit diverges, whether in exact restart or elsewhere.

There is a problem in the current implementation where a test will reset the INFO_DBUG under the covers in test mode.  I have reported this problem elsewhere.  I still believe there is benefit to having INFO_DBUG set to 2 by default for all tests and would argue we should actually bring that feature back.

**Comment by quantheory** [comment]
Oh, I see. I was somehow missing cesm_comp_mod in my grep, which is almost the only place where this value is actually checked. I suppose that it has never been particularly relevant to me, because the CAM logs (and instantaneous history outputs) are much better for figuring out where CAM runs diverge...

It does seem that the `INFO_DBUG` documentation is incorrect (and somewhat vague). The only check that I can see is to test whether the value is greater than 1 or not, so it is not the case that the values 0, 1, 2, and 3 are all meaningfully different, as the documentation suggests. That at least should be changed.

**Comment by apcraig** [comment]
The env variable INFO_DBUG gets translated into info_debug in the driver namelist and then plays a large role in the driver/coupler about what and how things get diagnosed.  There also may be other components that use the INFO_DBUG value to set some namelist.  INFO_DBUG of 1 and 2 are the main values used.  I don't believe 3 adds any other information beyond 2 and 0 also may not do anything different than 1.  But the idea was that if we wanted to use 0, 3, 4 and other values, we could.

**Comment by quantheory** [comment]
> There also may be other components that use the INFO_DBUG value to set some namelist.

Ah, OK. It looks like POP also checks for `$INFO_DBUG > 1`, though no other component seems to.

> I don't believe 3 adds any other information beyond 2 and 0 also may not do anything different than 1. But the idea was that if we wanted to use 0, 3, 4 and other values, we could.

I guess my point is simply that if there's no plans to do that right now, the documentation should probably be adjusted to simply suggest using values `1` or `2`. Unless this is something that you want to encourage more of the components to use?

(I still think that `INFO_DBUG`, compared to `INFO_DEBUG` or simply `VERBOSITY`, is not the best name.)

**Comment by apcraig** [comment]
I don't disagree that INFO_DBUG isn't the best name.  But I also don't think there is any reason to change it at this point.  It has existed for over a decade and people are used to it.

**Comment by quantheory** [comment]
> But I also don't think there is any reason to change it at this point.

I think that unusual abbreviations like `INFO_DBUG` tend to make the interface seem jargony and slapdash, not to mention that there's the potential for mixups coming from the fact that the coupler namelist variable is called `info_debug`, just one character off. So I would say that those are all good reasons to change the name.

> It has existed for over a decade and people are used to it.

If it has been around for a decade and is still highly useful, then I imagine that there's a good chance that it will be around for another decade. So it's probably worth fixing it for the benefit of new and future users, and now is the time to be looking at tweaks like this. Once CESM 2.0 is released, being a major release, it's going to be used and supported for a very long time.

Plus, I doubt that veteran users will have trouble adapting to a change as minor as spelling out `INFO_DEBUG`.
