### ISSUE TITLE
What is `-pecount`?

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#68]
As noted on [Bugzilla](http://bugs.cgd.ucar.edu/show_bug.cgi?id=1086), the documentation is a little vague. Actually, it's not clear to me how we should view this, anyway. I think that most of the use for this is in automated testing, and I'm not sure that you actually reliably get enough out of this option that a regular user would actually want it...

**Comment by jedwards4b** [comment]
Python version has enhanced documentation of usage of this flag.
