### ISSUE TITLE
adding back tag version information into env_run.xml 

### ISSUE THREAD

**Issue by bertinia** [CESM-Development/cime#69]
Prior to introducing CIME, the CCSM_REPOTAG env var was written to the env_run.xml file by
create_newcase. With CIME, the default settings in env_run.xml are now:

env_run.xml: entry id="CIME_REPOTAG"   value="UNSET"  
env_run.xml: entry id="CCSM_REPOTAG"   value="" 

Any objections to adding code in create_newcase to query SVN and parsing the SVN_EXTERNALS_DIRECTORIES to retrieve this info? Is there a cleaner way to get this
info from a downloaded version of the model? 

Note: for living alpha tags in testing, the CCSM_REPOTAG may not reflect the correct sequence
(i.e. alpha05a, alpha05b) but rather just the living alpha branch (i.e. alpha05).

**Comment by bandre-ucar** [comment]
I think we need to distinguish between the repo tags the case was created from and the current state of the repos. Those variables should probably be CIME_INITIAL_REPO_TAG and CESM_INITIAL_REPO_TAG.

The code can be different between the initial tag and what was actually used for a run. It would be great if every time a build or run script was executed it would append the results of {git | svn} status to the case docs. I'm not sure how to handle source mods changes.....

**Comment by jedwards4b** [comment]
Current status - the svn revision from the ChangeLog (for cesm) or the git revision (for acme)
is added to the MODEL_VERSION field in each case.  Establishing provanence is an important goal and several means of doing so are a work in progress for cesm2.  I'm closing this issue.
