### ISSUE TITLE
Use transient aerosol file for DATM_PRESAERO=clim_2000 conditions

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#70]
I'm simply copying an issue that Erik opened on GitHub. The settings mentioned below are obviously not in this file anymore (since `datm.cpl7.template` doesn't even exist anymore), but the options mentioned in this issue are still in the datm namelist defaults XML file, and still seem to have the old values.

```
In datm8_100612 the aerosoldep_monthly_2000_mean_1.9x2.5_c090421.nc file is used, but to be consitent with CAM and with transient conditions we should use the updated transient aerosol file cycling over year 2000. The older 2000 file has data that is inconsistent with the transient file.

So the following change should take place...

Index: datm.cpl7.template
===================================================================
--- datm.cpl7.template  (revision 23838)
+++ datm.cpl7.template  (working copy)
@@ -154,10 +154,10 @@
    set year_last_aero  = 1
    set year_align_aero = 1
 else if ($DATM_PRESAERO == 'clim_2000') then
-   set file_aero = aerosoldep_monthly_2000_mean_1.9x2.5_c090421.nc
+   set file_aero = aerosoldep_monthly_1849-2006_1.9x2.5_c090803.nc
    set path_aero = atm/cam/chem/trop_mozart_aero/aero
-   set year_first_aero = 1
-   set year_last_aero  = 1
+   set year_first_aero = 2000
+   set year_last_aero  = 2000
    set year_align_aero = 1
 else if ($DATM_PRESAERO == 'trans_1850-2000') then
    set file_aero = aerosoldep_monthly_1849-2006_1.9x2.5_c090803.nc
```

**Comment by billsacks** [comment]
@ekluzek : do we still want this done, and fixed for cesm2?

**Comment by ekluzek** [comment]
This is really just a consistency issue. It makes the scripts more uniform
and easy to understand. But, it's not something really required.

_Erik Kluzek, (CGD at NCAR)_

_National Center for Atmospheric Research_

*Boulder CO, *

_(off) (303)497-1326 (fax) (303)497-1348_

_(skype) ekluzek    (cell) (303)859-0183_

_Pronouns: he/his/him_

_------------------ Home page ------------------------_
- ```
       http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*
  ```
- ```
       https://staff.ucar.edu/users/erik
  ```
  
  https://staff.ucar.edu/users/erik*

_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_

**Comment by jedwards4b** [comment]
@ekluzek I'm closing this issue - if there are still outstanding aspects please go ahead and open an esmci issue and reference this one.   Thanks
