### ISSUE TITLE
Running preview_namelists before cesm_setup give a slightly strange error message

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#71]
Inspired by a bug filed by Jim forever ago. The current error message is:

```
*** can't open file: /glade/p/work/santos/tmp/whatever/user_nl_cpl
ERROR preview_namelists: /glade/p/work/santos/tmp/whatever/Buildconf/cpl.buildnml /glade/p/work/santos/tmp/whatever failed: 512
```

We should probably check that `cesm_setup` has been run before `preview_namelists` tries to actually do anything. I'm not sure what the standard way of doing that would be. Checking that the `user_nl_*` files exist? Checking if `LockedFiles/env_mach_pes.xml.locked` exists?

**Comment by jedwards4b** [comment]
Replaced by ESMCI issue 845
