### ISSUE TITLE
Tab characters should be removed from strings in streams files

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#72]
From a Bugzilla issue from Bill Sacks:

A user ran into a problem when editing a streams file (`dlnd.streams.txt.sno.cplhist`): there were some tab characters in the file both before and after some strings. It looks like these tab characters are not stripped from the strings (e.g., using `shr_string_leftAlign`). This led to an error that looked like this in the lnd log file:

```
(shr_sys_abort) ERROR: (shr_stream_getCalendar)  ERROR: nf90_open file      /glade/scratch/gailg        /           IG_spinup_smb4.cpl.hs2x.0067.4avgmax.nc
```

Since tabbing is a natural thing to do when editing text files, it seems it would be good to extend the `shr_string` utilities to strip tabs as well as spaces.

**Comment by billsacks** [comment]
This just caused some scientists a few days of lost time... we should try to fix it for the cesm2 release.

**Comment by mvertens** [comment]
This should be fixed in the next CIME tag that gets brought in.

**Comment by mvertens** [comment]
Tony, if you could take this one on, given your expertise in the shr_stream code, that would be great.

**Comment by jedwards4b** [comment]
@apcraig has this been addressed?  If not please reopen in esmci.

**Comment by billsacks** [comment]
Moved to https://github.com/ESMCI/cime/issues/862
