### ISSUE TITLE
CaseStatus file with create_clone

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#73]
From an old Bugzilla issue from Nancy Norton:

> When create_clone is used to create a new case, the resulting CaseStatus file is copied from the cloned case to the new case.
> 
> I would like to see the new case's CaseStatus file contain just a single line when the new case  is created, with information that says the case was cloned from $CLONED_CASE_NAME.
> 
> Ditto for README.case

I'm not sure if this is still the case, but I didn't see any special handling of CaseStatus, so I presume that it's still just copied. It might be good to at least separate the lines from the old case from the ones in the clone, even if we keep the old CaseStatus information.

**Comment by bandre-ucar** [comment]
I find having the old case status info useful. I'd prefer to just have clear delimiter between the old and new info.

**Comment by sholly** [comment]
Fixing this, keeping the old case info, appending create_clone + args to CaseStatus file

**Comment by sholly** [comment]
fixed in #296
