### ISSUE TITLE
Change CPLHIST streams into: nonSolarFlux, State, and SolarFlux (make consistent between ocn and lnd)

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#77]
From Erik via Bugzilla:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=2080

**Comment by billsacks** [comment]
@ekluzek - should this be a priority for cesm?

**Comment by ekluzek** [comment]
I think we should do this and make it happen for cesm2.

_Erik Kluzek, (CGD at NCAR)_

_National Center for Atmospheric Research_

*Boulder CO, *

_(off) (303)497-1326 (fax) (303)497-1348_

_(skype) ekluzek    (cell) (303)859-0183_

_Pronouns: he/his/him_

_------------------ Home page ------------------------_
- ```
       http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*
  ```
- ```
       https://staff.ucar.edu/users/erik
  ```
  
  https://staff.ucar.edu/users/erik*

_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_

**Comment by ekluzek** [comment]
I'm pretty sure this has been done. So I'm just closing.
