### ISSUE TITLE
 Add DIN_LOC_ROOT_CPLHIST for location of coupler history data for spinup

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#78]
From Bugzilla, from Erik:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=2087

**Comment by billsacks** [comment]
@ekluzek - should this be done for cesm2?

**Comment by ekluzek** [comment]
I think so.

_Erik Kluzek, (CGD at NCAR)_

_National Center for Atmospheric Research_

*Boulder CO, *

_(off) (303)497-1326 (fax) (303)497-1348_

_(skype) ekluzek    (cell) (303)859-0183_

_Pronouns: he/his/him_

_------------------ Home page ------------------------_
- ```
       http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*
  ```
- ```
       https://staff.ucar.edu/users/erik
  ```
  
  https://staff.ucar.edu/users/erik*

_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_

**Comment by billsacks** [comment]
Closing this old issue; I'm not sure if it has been fixed. Feel free to reopen in ESMCI/cime if necessary.
