### ISSUE TITLE
Resolve environment variable references in env_*.xml files

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#80]
Tony [reported some time ago](http://bugs.cgd.ucar.edu/show_bug.cgi?id=1778) that it is not possible to use arbitrary system-defined environment variables, e.g. `$WORKDIR`, in scripts directories such as `EXEROOT` and `RUNDIR`.

Assuming that this is still the case (I haven't checked, but I think it is), it would be nice to improve that situation.

**Comment by billsacks** [comment]
Jim thinks this is fixed already.
