### ISSUE TITLE
Check on coupling frequencies

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#81]
Tony [proposed some time ago](http://bugs.cgd.ucar.edu/show_bug.cgi?id=1740) that the following checks be added to the coupler, to ensure that the various NCPL variables are set in a consistent way:

ATM_NCPL >= ROF_NCPL
ATM_NCPL >= OCN_NCPL

**Comment by billsacks** [comment]
This issue was moved to ESMCI/cime#1324
