### ISSUE TITLE
long term archiver steps on short term archiver files with HSI command

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#82]
I'm not clear on whether or not this is still a problem given the batch refactoring, but if it's not, I'm curious what prevents the short and long term archivers from interfering with each other. Or for that matter, what prevents two short term archiving jobs from interfering with each other, or two long term archiving jobs.

This is the issue filed by Nancy Collins on Bugzilla:

> it used to be that when both the long term and short term archiver were active, they avoided interfering with each other by having the short term archiver create files in an .sta subdirectory and only when the contents were complete was the directory moved into the normal archive dir.  that way the long term archiver didn't "see" it until the contents were complete. 
> 
> but now the HSI section of the lt archive script uses 'put -dPR *' to put all files from the archive dir onto the HPSS, and delete them when they transfer successfully.  it turns out this wildcard matches even hidden dirs, so the .sta dir can get copied to the HPSS and then deleted from the archive dir.  plus you now have hidden dirs out on the HPSS (which you can see with "hsi> ls -al" but not otherwise).
> 
> this leads to a race condition where some files might be long term archived under the .sta directory and some under the normal location and neither are complete.
> 
> i have 2 suggestions if you're interested.  1) if the put command will take multiple filenames, do an 'filelist=`ls`' in the archive dir and then 'put -dPR $filelist' so you won't copy the .sta dir.   2) if it won't, loop over the filelist and put one dir at a time.  or 3) change .sta to something visible but distinct like 'partial_archive' so it's not hidden and mysterious, and when constructing the list of dirs to archive, make it 'ls | grep -v partial_archive' so that dir isn't on the list of things to put.
> 
> we may be seeing this problem more than others because we're doing 80 instances of cam - lots more files for the archivers to move/copy, and because we're stopping more often than other uses.  but a race condition is a race condition, and if you try to long-term archive things while a job is currently running you risk having a corrupted archive.

**Comment by sholly** [comment]
closed, fixed with #260
