### ISSUE TITLE
Set MP_INFOLEVEL differently on yellowstone by default?

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#83]
See the following bug from Nancy Collins, mentioning the spam that we tend to see in the CESM log:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=1756

My first comment there notwithstanding, it turns out that we actually _can_ do something different for yellowstone, namely to set `$MP_INFOLEVEL` to 1 (the default) or 0 (quiet) rather than our current setting of 2 (verbose). That gets rid of almost all of the output that occurs before the first CESM log message (which is usually something like this):

```
0:(seq_comm_setcomm)  initialize ID (  1 GLOBAL          ) pelist   =     0    29     1 ( npes =    30) ( nthreads =  1)
```

Unless there's some important reason to do otherwise, maybe we should only set `$MP_INFOLEVEL` to 2 for DEBUG runs.

**Comment by billsacks** [comment]
Jim thinks this has been fixed.
