### ISSUE TITLE
Comparison of history files in _N2 tests looks buggy

### ISSUE THREAD

**Issue by billsacks** [CESM-Development/cime#84]
In component_compare_test.sh, the _N2 comparison looks like this:

```
        compare_result=`${tools_dir}/component_compare.sh -baseline_dir "$rundir" -test_dir "$rundir" -baseline_hist "$hist1_0001" -test_hist "$hist1_0002" -cprnc_exe "$cprnc_exe"`
        print_status "$compare_status" "$compare_info" "${testcase_base}.${model}.${extension}.nc : test compare ${model}.${extension} (.${suffix1} for _0001 and .${suffix2} for _0001)"

        compare_result=`${tools_dir}/component_compare.sh -baseline_dir "$rundir" -test_dir "$rundir" -baseline_hist "$hist2_0002" -test_hist "$hist2_0002" -cprnc_exe "$cprnc_exe"`
        print_status "$compare_status" "$compare_info" "${testcase_base}.${model}.${extension}.nc : test compare ${model}.${extension} (.${suffix1} for _0002 and .${suffix2} for _0002)"
```

Notice that the second comparison compares hist2_0002 with itself, and for the first comparison, the print_status does not match what is actually being compared. It's not clear to me what the intended behavior is here, but the current behavior does not look correct.

Note that there were also some typos in the file checks in nearby lines, but I have fixed those typos on a branch: billsacks/cime@9672c7bef6d4b7abafd8668042fe4ea60ed355d2

**Comment by jedwards4b** [comment]
Fixed in cime5
