### ISSUE TITLE
Simple namelist settings to turn on changes for data assimilation

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#90]
See the bugzilla bug here:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=1804

Specifically:

> Talking in the hall, we thought this should be a namelist parameter for each active model component (because typically you only assimilate into one model) and it should be called:
> 
> assim_mode
> 
> as it doesn't have to be DART -- it could be another Data Assimilation model.

I'm putting this here in the CIME repo because the original proposal was to have a `DART_MODE` option in the scripts to flip this on for every component, but it's not clear to me whether or not this still involves CIME, as opposed to the various science models.

**Comment by billsacks** [comment]
@gold2718 - we're assigning this to you... but it may already be addressed to some extent now that data assimilation is in cime.

**Comment by gold2718** [comment]
Fixed in ESMCI/cime (several PRs, e.g., ESMCI/cime#2751)
