### ISSUE TITLE
Inaccurate shr_dmodel_mod code for grids in SCAM that are not purely lat/lon

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#93]
From Bugzilla, with a proposed fix:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=1951

See also #65.

**Comment by mvertens** [comment]
This should be bundled in with the #65 bug as one bug.

**Comment by jedwards4b** [comment]
Moved to ESMCI issue 856
