### ISSUE TITLE
datm strm_datadir path inconsistency

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#94]
From Bugzilla:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=2028

> https://svn-ccsm-models.cgd.ucar.edu/datm7/trunk_tags/datm8_140723/bld/namelist_files/namelist_defaults_datm.xml
> 
> All the _supported_ CLM1PT paths looking something like:
> 
> atm/datm7/CLM1PT_data/__NAME__
> 
> See:
> 
> <strm_datdir     stream="CLM1PT.1x1_mexicocityMEX">$DIN_LOC_ROOT/atm/datm7/CLM1PT_data/mexicocityMEX.c080124</strm_datdir>
> 
> <strm_datdir     stream="CLM1PT.1x1_vancouverCAN">$DIN_LOC_ROOT/atm/datm7/CLM1PT_data/vancouverCAN.c080124 </strm_datdir>
> 
> <strm_datdir     stream="CLM1PT.1x1_urbanc_alpha">$DIN_LOC_ROOT/atm/datm7/CLM1PT_data/urbanc_alpha.c080416 </strm_datdir>
> 
> But the path when CLM_USRDAT_NAME (PTCLM or manually) is inconsistent:
> 
> CLMFORC/__NAME__/CLM1PT_data
> 
> See:
> 
> <strm_datdir     stream="CLM1PT.CLM_USRDAT">$DIN_LOC_ROOT_CLMFORC/$CLM_USRDAT_NAME/CLM1PT_data</strm_datdir>
> 
> This inconsistency is a bit confusing to users who are looking at the cesm input data as an example to build point data manually. It would be better to have everything be consistent. It probably makes the most sense to adopt the PTCLM/CLM_USRDAT for the predefined cases.

**Comment by billsacks** [comment]
@ekluzek and @bandre-ucar - should this be fixed for cesm2?

**Comment by billsacks** [comment]
Closing this old issue; I'm not sure if it has been fixed. Feel free to reopen in ESMCI/cime if necessary.
