### ISSUE TITLE
Allow 20TR simulations to easily cycle through "precursor" data

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#95]
From Bugzilla:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=2034

Note particularly:

> The longer term solution is to extend the streams files so that an optional offset or year, could be after the filename.
> 
> Something like...
> 
> <1901-01-01-filename> 1850-01-01
> 
> So it would change the date of the data on the given file to be 1850-01-01 rather than using the 1901 date on the actual data in the file.

**Comment by billsacks** [comment]
@ekluzek - should this be fixed for cesm2?

**Comment by billsacks** [comment]
@ekluzek - I assume this isn't going to make it for cesm2?

**Comment by ekluzek** [comment]
Yeah, this can wait for the update after cesm2.0. I think it's a great idea, but needs some development to prove the concept and make sure it works correctly. So it can wait.

**Comment by billsacks** [comment]
Closing this old issue; I'm not sure if it has been fixed. Feel free to reopen in ESMCI/cime if necessary.
