### ISSUE TITLE
Make csm_share's include/lib directories discoverable outside of the CESM Makefile

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#96]
From Bugzilla:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=2052

Apparently, MPAS's build needs to know where the csm_share include/lib directories are, presumably via environment variable.

**Comment by jedwards4b** [comment]
I think that this is related to the desire to separate csm_share into
fortran utility libraries and cesm specific library and
will be addressed by that change - is there a ticket for that?

On Tue, Aug 4, 2015 at 11:58 AM, Sean Patrick Santos <
notifications@github.com> wrote:

> Assigned #96 https://github.com/CESM-Development/cime/issues/96 to
> @jedwards4b https://github.com/jedwards4b.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CESM-Development/cime/issues/96#event-373328694.

## 

Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by quantheory** [comment]
It's #18.

**Comment by jedwards4b** [comment]
Moved to ESMCI issue 852
