### ISSUE TITLE
Better validation of longnames for `-user_compset` cases

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#97]
From [Bugzilla](http://bugs.cgd.ucar.edu/show_bug.cgi?id=2075):

> The -user_compset option to create_newcase currently doesn't validate that the components of the name are correct. It should validate that each of the components of the name are correct, and if not abort rather than creating a case that is ill-defined (ending up on relying on arbitrary defaults rather than what the user intended to do).

**Comment by mvertens** [comment]
This will be resolved in the upcoming scripts refactor.

**Comment by jedwards4b** [comment]
Fixed in cime5
