### ISSUE TITLE
 Add CPLHIST option to prescribed aerosol mode in datm

### ISSUE THREAD

**Issue by quantheory** [CESM-Development/cime#99]
From Bugzilla:

http://bugs.cgd.ucar.edu/show_bug.cgi?id=2076

**Comment by billsacks** [comment]
@ekluzek - should this be fixed for cesm2?

**Comment by ekluzek** [comment]
Yes.

_Erik Kluzek, (CGD at NCAR)_

_National Center for Atmospheric Research_

*Boulder CO, *

_(off) (303)497-1326 (fax) (303)497-1348_

_(skype) ekluzek    (cell) (303)859-0183_

_Pronouns: he/his/him_

_------------------ Home page ------------------------_
- ```
       http://www.cgd.ucar.edu/~erik <http://www.cgd.ucar.edu/~erik>*
  ```
- ```
       https://staff.ucar.edu/users/erik
  ```
  
  https://staff.ucar.edu/users/erik*

_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_

**Comment by billsacks** [comment]
This issue was moved to ESMCI/cime#1529
